<?php 
return array (
  //退单信息
  'sell_return_code' =>             array ('title' => '退单号','type'=>'1'),
  'shop_name' =>                    array ('title' => '店铺'),
  'return_type' =>                  array ('title' => '退单类型','type'=>4,'func'=>'return_order_type'),
  'return_order_status_txt' =>      array ('title' => '退单状态'),
  'return_name' =>                  array ('title' => '退货人'),
  'return_mobile' =>                array ('title' => '退货人手机','type'=>'1'),
  'store_code' =>                   array ('title' => '退货仓库','type'=>'5','func'=>'store'),
  'return_reason_name' =>           array ('title' => '退单原因','type'=>'1'),
  'return_buyer_memo' =>            array ('title' => '买家退单说明'),
  'return_remark' =>                array ('title' => '卖家退单备注','type'=>'1'),
  'sell_record_code' =>             array ('title' => '原单号','type'=>'1'),
  'deal_code' =>                    array ('title' => '交易号','type'=>'1'),
  'express_name' =>                 array ('title' => '原单快递公司'),
  'yl_express_no' =>                 array ('title' => '原单物流单号','type'=>1),
  'buyer_name' =>                   array ('title' => '买家昵称'),
  'refund_total_fee' =>             array ('title' => '实际应退款总额'),
  'buyer_express_money' =>          array ('title' => '卖家承担运费'),
  'fx_express_money' =>          array ('title' => '分销结算运费'),
  'adjust_money' =>                 array ('title' => '手工调整金额'),
  'compensate_money' =>             array ('title' => '赔付金额'),
  'return_mobile' =>                array ('title' => '退货人电话','type'=>'1'),
  'return_address' =>               array ('title' => '退货人地址'),
  'return_zip_code' =>              array ('title' => '退货人邮编','type'=>'1'),
  'return_email' =>                 array ('title' => '退货人Email'),
  'return_express_name' =>          array ('title' => '买家退货快递公司'),
  'return_express_no' =>            array ('title' => '买家退货物流单号','type'=>'1'),
  'is_exchange_goods' =>            array ('title' => '有无换货','type'=>'3'), 
  'create_time' =>                  array ('title' => '退单创建时间'),
  'data_type' =>                    array ('title' => '商品类型','type'=>'4','func'=>'goods_type',),
  'receive_time' =>                 array ('title' => '确认收货时间'),
  'agreed_refund_time'=>            array('title'=>'确认退款时间'),
  'receive_person'=>                array('title'=>'验收入库人'),
  'agree_refund_person'=>           array('title'=>'财务确认退款人'),
  //退|换货商品信息
  'goods_name' =>                   array ('title' => '商品名称'),
  'goods_code' =>                   array ('title' => '商品编码'),
  'spec1_name' =>                   array ('title' => '颜色'),
  'spec2_name' =>                   array ('title' => '尺码'),
  'barcode' =>                      array ('title' => '商品条形码','type'=>'1'),
  'note_num' =>                     array ('title' => '申请退货数量','type'=>'1'),
  'recv_num' =>                     array ('title' => '实际退货数量','type'=>'1'),
  'num' =>                          array ('title' => '换货商品数量','type'=>'1'),
  'goods_price' =>                  array ('title' => '吊牌价'),
  'return_avg_money' =>             array ('title' => '实际应退款'),
  'change_avg_money' =>             array ('title' => '实际应收款'),
) ;