DROP TABLE IF EXISTS `api_order`;
CREATE TABLE `api_order` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `tid` varchar(30) DEFAULT '' COMMENT '平台交易号',
  `sell_record_code` varchar(30) DEFAULT '' COMMENT '业务系统单据编号(订单号)',
  `source` varchar(15) DEFAULT '' COMMENT '平台来源标识符,淘宝：taobao，后台：houtai，京东：jingdong，唯品会：weipinhui，当当：dangdang，拍拍：paipai，1号店：yihaodian，亚马逊：yamaxun，凡客：vjia，优购：yougou，聚美优品：jumei，麦网：m18，库巴：coo8，苏宁：suning，名鞋库：scn，阿里巴巴：alibaba，微购物：weigou，口袋通:koudaitong,工行:gonghang,银泰:yintai,走秀网:zouxiu,贝贝网:beibei,蘑菇街:mogujie,拍鞋网:paixie,好乐买:okbuy,乐蜂:lefeng',
  `shop_code` varchar(50) DEFAULT '' COMMENT '业务系统店铺代码',
  `status` tinyint(1) DEFAULT '0' COMMENT '0：不可转单 1：可转单  允许转单规则：已付款未发货',
  `trade_from` varchar(10) DEFAULT '' COMMENT 'WAP(手机);HITAO(嗨淘);TOP(TOP平台);TAOBAO(普通淘宝);JHS(聚划算)',
  `pay_type` tinyint(1) unsigned DEFAULT NULL COMMENT '平台支付类型（转化后),淘宝type=cod为1，非cod为0',
  `pay_time` datetime DEFAULT NULL COMMENT '平台支付时间',
  `seller_nick` varchar(30) DEFAULT '' COMMENT '平台卖家昵称',
  `buyer_nick` varchar(30) DEFAULT '' COMMENT '平台买家昵称',
  `receiver_name` varchar(30) DEFAULT '' COMMENT '平台收货人名称',
  `receiver_country` varchar(50) DEFAULT '' COMMENT '国家（转化后）',
  `receiver_province` varchar(50) DEFAULT '' COMMENT '省（转化后）',
  `receiver_city` varchar(50) DEFAULT '' COMMENT '市（转化后）',
  `receiver_district` varchar(50) DEFAULT '' COMMENT '区（转化后）',
  `receiver_street` varchar(100) DEFAULT '' COMMENT '街道（转化后）',
  `receiver_address` varchar(300) DEFAULT '' COMMENT '地址（含省市区）',
  `receiver_addr` varchar(200) DEFAULT '' COMMENT '地址（不含省市区）',
  `receiver_zip_code` varchar(10) DEFAULT '' COMMENT '平台邮政编码',
  `receiver_mobile` varchar(11) DEFAULT '' COMMENT '平台电话',
  `receiver_phone` varchar(12) DEFAULT '' COMMENT '平台固定电话',
  `receiver_email` varchar(30) DEFAULT '' COMMENT '平台email',
  `express_code` varchar(20) DEFAULT '' COMMENT '配送方式CODE',
  `express_no` varchar(20) DEFAULT '' COMMENT '平台快递单号',
  `hope_send_time` datetime DEFAULT NULL COMMENT '期望配送时间',
  `num` tinyint(4) DEFAULT NULL COMMENT '平台数量',
  `sku_num` tinyint(4) DEFAULT NULL COMMENT '平台sku种类数量（转化后）',
  `goods_weight` float(7,2) DEFAULT '0.00' COMMENT '平台商品总重量(g)',
  `buyer_remark` varchar(255) DEFAULT '' COMMENT '平台买家留言',
  `seller_remark` varchar(255) DEFAULT '' COMMENT '平台商家备注',
  `seller_flag` varchar(10) DEFAULT '' COMMENT '平台订单的旗帜',
  `order_money` double(10,2) DEFAULT '0.00' COMMENT '平台实付金额',
  `express_money` float(7,2) DEFAULT '0.00' COMMENT '平台运费',
  `delivery_money` double(10,2) DEFAULT '0.00' COMMENT '配送手续费',
  `commission_fee` float(7,2) DEFAULT '0.00' COMMENT '交易佣金',
  `gift_coupon_money` float(5,2) DEFAULT '0.00' COMMENT '买家支付礼券金额',
  `gift_money` float(5,2) DEFAULT '0.00' COMMENT '买家支付礼品卡金额',
  `buyer_money` double(10,2) DEFAULT '0.00' COMMENT '买家已付款，买家真实付款',
  `alipay_no` varchar(40) DEFAULT NULL,
  `integral_change_money` float(5,2) DEFAULT NULL COMMENT '买家实际使用积分兑换金额',
  `coupon_change_money` float(5,2) DEFAULT NULL COMMENT '平台抵扣金额。如：优惠劵',
  `balance_change_money` float(5,2) DEFAULT NULL COMMENT '余额抵扣金额',
  `is_lgtype` tinyint(1) DEFAULT NULL COMMENT '平台是否需要物流宝发货的标识,如果为true，则需要可以用物流宝来发货，如果未false，则该订单不能用物流宝发货',
  `seller_rate` tinyint(1) DEFAULT '0' COMMENT '卖家是否已评价',
  `buyer_rate` tinyint(1) DEFAULT '0' COMMENT '买家是否已评价',
  `invoice_type` varchar(10) DEFAULT '' COMMENT '平台发票类型',
  `invoice_title` varchar(50) DEFAULT '' COMMENT '平台发票抬头',
  `invoice_content` varchar(100) DEFAULT '' COMMENT '平台发票内容',
  `invoice_money` decimal(7,2) DEFAULT NULL COMMENT '平台发票金额',
  `invoice_pay_type` varchar(20) DEFAULT '' COMMENT '平台发票支付方式',
  `change_remark` varchar(200) DEFAULT '' COMMENT '转单日志',
  `is_detail` tinyint(1) DEFAULT '0' COMMENT '0：不处理 1：需要处理',
  `is_change` tinyint(1) DEFAULT '0' COMMENT '0：未转单 1：已转单',
  `order_last_update_time` datetime DEFAULT NULL COMMENT '平台订单最后一次更新订单时间',
  `order_first_insert_time` datetime DEFAULT NULL COMMENT '平台订单第一次插入订单时间',
  `last_update_time` datetime DEFAULT NULL COMMENT '最后一次更新订单时间,数据在本平台的更新时间',
  `first_insert_time` datetime DEFAULT NULL COMMENT '第一次插入订单时间,数据在本平台的更新时间',
  `lastchanged` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `api_data` text COMMENT '在业务中用到的接口数据以json格式保存',
  `type` varchar(30) DEFAULT NULL COMMENT '交易类型',
  `buyer_alipay_no` varchar(50) DEFAULT '' COMMENT '买家支付宝账号',
  `sale_mode` varchar(10) NOT NULL DEFAULT 'stock' COMMENT '销售模式：现货stock，预售presale',
  `pay_code` varchar(20) NOT NULL DEFAULT '' COMMENT '支付方式代码',
  PRIMARY KEY (`id`),
  UNIQUE KEY `tid` (`tid`) USING BTREE,
  KEY `source` (`source`) USING BTREE,
  KEY `shop_code` (`shop_code`) USING BTREE,
  KEY `trade_from` (`trade_from`) USING BTREE,
  KEY `seller_nick` (`seller_nick`) USING BTREE,
  KEY `buyer_nick` (`buyer_nick`) USING BTREE,
  KEY `shop_code_order_last_update_time` (`shop_code`,`order_last_update_time`),
  KEY `order_last_update_time` (`order_last_update_time`),
  KEY `shop_code_order_first_insert_time` (`shop_code`,`order_first_insert_time`),
  KEY `created` (`order_first_insert_time`),
  KEY `index1` (`status`,`is_change`) USING BTREE,
  KEY `index2` (`pay_type`) USING BTREE,
  KEY `index3` (`pay_time`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='平台订单表';

