DROP TABLE IF EXISTS `api_taobao_fx_trade`;
CREATE TABLE `api_taobao_fx_trade` (
  `ttid` int(11) unsigned AUTO_INCREMENT,
  `shop_code` varchar(50) DEFAULT '' COMMENT '店铺nick',
  `id` varchar(50) DEFAULT '' COMMENT '供应商交易ID 非采购单ID，如果改发货状态 是需要该ID，ID在用户未付款前为0，付款后有具体值（发货时使用该ID）',
  `buyer_payment` varchar(50) DEFAULT '' COMMENT '买家支付给分销商的总金额。注意买家购买的商品可能不是全部来自同一供货商，请同时参考子单上的相关金额。（精确到2位小数单位:元。如:200.07，表示:200元7分）',
  `buyer_nick` varchar(50) DEFAULT '' COMMENT '买家nick，供应商查询不会返回买家昵称，分销商查询才会返回',
  `consign_time` varchar(50) DEFAULT '' COMMENT '物流发货时间',
  `distributor_from` varchar(50) DEFAULT '' COMMENT '分销商来源网站（taobao）',
  `distributor_username` varchar(50) DEFAULT '' COMMENT '',
  `distributor_payment` varchar(50) DEFAULT '' COMMENT '分销商实付金额。(精确到2位小数单位:元。如:200.07，表示:200元7分 )',
  `receiver_address` varchar(255) DEFAULT '' COMMENT '收货人的详细地址信息',
  `receiver_district` varchar(50) DEFAULT '' COMMENT '区/县',
  `receiver_city` varchar(50) DEFAULT '' COMMENT '收货人的城市',
  `receiver_phone` varchar(50) DEFAULT '' COMMENT '固定电话',
  `receiver_name` varchar(50) DEFAULT '' COMMENT '收货人全名',
  `receiver_mobile_phone` varchar(50) DEFAULT '' COMMENT '移动电话',
  `receiver_zip` varchar(50) DEFAULT '' COMMENT '邮政编码',
  `receiver_state` varchar(50) DEFAULT '' COMMENT '收货人所在省份',
  `end_time` varchar(50) DEFAULT '' COMMENT '交易结束时间',
  `fenxiao_id` varchar(50) DEFAULT '' COMMENT '分销流水号，分销平台产生的主键',
  `created` datetime DEFAULT '0000-00-00 00:00:00' COMMENT '采购单创建时间',
  `modified` datetime DEFAULT '0000-00-00 00:00:00' COMMENT '交易修改时间',
  `logistics_company_name` varchar(50) DEFAULT '' COMMENT '物流公司',
  `logistics_id` varchar(50) DEFAULT '' COMMENT '运单号',
  `memo` text DEFAULT '' COMMENT '采购单留言',
  `status` varchar(50) DEFAULT '' COMMENT '采购单交易状态。可选值：WAIT_BUYER_PAY(等待付款),WAIT_SELLER_SEND_GOODS(已付款，待发货）,WAIT_BUYER_CONFIRM_GOODS(已付款，已发货),TRADE_FINISHED(交易成功),TRADE_CLOSED(交易关闭),WAIT_BUYER_CONFIRM_GOODS_ACOUNTED(已付款（已分账），已发货。只对代销分账支持),PAY_ACOUNTED_GOODS_CONFIRM （已分账发货成功）,PAY_WAIT_ACOUNT_GOODS_CONFIRM（已付款，确认收货）',
  `alipay_no` varchar(50) DEFAULT '' COMMENT '支付宝交易号',
  `pay_time` varchar(50) DEFAULT '' COMMENT '付款时间',
  `pay_type` varchar(50) DEFAULT '' COMMENT '支付方式：ALIPAY_SURETY（支付宝担保交易）、ALIPAY_CHAIN（分账交易）、TRANSFER（线下转账）、PREPAY（预存款）、IMMEDIATELY（即时到账）、CASHGOODS（先款后货）',
  `post_fee` varchar(50) DEFAULT '' COMMENT '采购单邮费。(精确到2位小数单位:元。如:200.07，表示:200元7分 )',
  `shipping` varchar(50) DEFAULT '' COMMENT '配送方式，FAST(快速)、EMS、ORDINARY(平邮)、SELLER(卖家包邮)',
  `supplier_from` varchar(50) DEFAULT '' COMMENT '供应商来源网站, values: taobao, alibaba',
  `supplier_username` varchar(50) DEFAULT '' COMMENT '供应商在来源网站的帐号名',
  `supplier_flag` varchar (50) DEFAULT '' COMMENT '返回供应商备注旗帜 vlaue在1-5之间。非1-5之间，都采用1作为默认。 1:红色 2:黄色 3:绿色 4:蓝色 5:粉红色',
  `tc_order_id` varchar(50) DEFAULT '' COMMENT '主订单ID',
  `total_fee` varchar(50) DEFAULT '' COMMENT '采购单总额（不含邮费,精确到2位小数单位:元。如:200.07，表示:200元7分 )',
  `trade_type` varchar(50) DEFAULT '' COMMENT '分销方式：AGENT（代销）、DEALER（经销）',
  `is_change` TINYINT(1) DEFAULT '0' COMMENT '0：未转单 1：已转单',
  `sell_record_code` VARCHAR(30) DEFAULT '' COMMENT '系统分销(订单号)',
  `change_remark` VARCHAR(200) DEFAULT '' COMMENT '转单日志',
  `is_invo` TINYINT(1) DEFAULT '0' COMMENT '0：不可转单 1：可转单  ',
  PRIMARY KEY (`ttid`),
  unique KEY(`fenxiao_id`),
  KEY(`shop_code`),
  KEY(`alipay_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT '淘宝分销订单';