
DROP TABLE IF EXISTS `api_taobao_item`;
CREATE TABLE `api_taobao_item` (
  `Id` int(11) NOT NULL AUTO_INCREMENT,
  `goods_id` mediumint(9) DEFAULT NULL,
  `goods_sn` varchar(255) DEFAULT NULL,
  `goods_name` varchar(255) DEFAULT NULL,
  `shop_code` varchar(50) NOT NULL COMMENT '商店code',
  `sddm` varchar(255) DEFAULT NULL,
  `outer_id` varchar(255) DEFAULT NULL COMMENT '商品外部ID',
  `title` varchar(255) DEFAULT NULL,
  `price` decimal(10,2) DEFAULT NULL COMMENT '价格',
  `type` varchar(255) DEFAULT NULL,
  `stuff_status` varchar(255) DEFAULT NULL,
  `desc` text,
  `state` varchar(255) DEFAULT NULL,
  `city` varchar(255) DEFAULT NULL,
  `approve_status` varchar(255) DEFAULT NULL COMMENT '状态 onsale 在售 instock 在库',
  `cid` varchar(255) DEFAULT NULL,
  `props` varchar(600) NOT NULL DEFAULT '',
  `freight_payer` varchar(255) DEFAULT NULL,
  `valid_thru` varchar(255) DEFAULT NULL,
  `has_invoice` varchar(255) DEFAULT NULL,
  `has_warranty` varchar(255) DEFAULT NULL,
  `has_showcase` varchar(255) DEFAULT NULL,
  `seller_cids` varchar(255) DEFAULT NULL,
  `has_discount` varchar(255) DEFAULT NULL,
  `post_fee` decimal(10,2) DEFAULT NULL,
  `express_fee` decimal(10,2) DEFAULT NULL,
  `ems_fee` decimal(10,2) DEFAULT NULL,
  `list_time` varchar(255) DEFAULT NULL,
  `increment` varchar(255) DEFAULT NULL,
  `image` varchar(255) DEFAULT NULL,
  `postage_id` varchar(255) DEFAULT NULL,
  `auction_point` varchar(255) DEFAULT NULL,
  `property_alias` varchar(255) DEFAULT NULL,
  `input_pids` varchar(255) DEFAULT NULL,
  `sku_properties` varchar(255) DEFAULT NULL,
  `sku_quantities` varchar(255) DEFAULT NULL,
  `sku_prices` varchar(255) DEFAULT NULL,
  `sku_outer_ids` varchar(255) DEFAULT NULL,
  `lang` varchar(255) DEFAULT NULL,
  `product_id` varchar(255) DEFAULT NULL,
  `pic_path` varchar(255) DEFAULT NULL,
  `auto_fill` varchar(255) DEFAULT NULL,
  `input_str` varchar(255) DEFAULT NULL,
  `is_taobao` varchar(255) DEFAULT NULL,
  `is_ex` varchar(255) DEFAULT NULL,
  `is_3D` varchar(255) DEFAULT NULL,
  `sell_promise` varchar(255) DEFAULT NULL,
  `after_sale_id` varchar(255) DEFAULT NULL,
  `cod_postage_id` varchar(255) DEFAULT NULL,
  `is_lightning_consignment` varchar(255) DEFAULT NULL,
  `weight` varchar(255) DEFAULT NULL,
  `is_xinpin` varchar(255) DEFAULT NULL,
  `sub_stock` varchar(255) DEFAULT NULL,
  `detail_url` varchar(255) DEFAULT NULL,
  `num_iid` varchar(30) NOT NULL COMMENT '商品数字ID',
  `nick` varchar(255) DEFAULT NULL,
  `skus` varchar(255) DEFAULT NULL,
  `props_name` varchar(255) DEFAULT NULL,
  `created` varchar(255) DEFAULT NULL,
  `promoted_service` varchar(255) DEFAULT NULL,
  `is_fenxiao` varchar(255) DEFAULT NULL,
  `volume` varchar(255) DEFAULT NULL,
  `template_id` varchar(255) DEFAULT NULL,
  `addition_skus` varchar(255) DEFAULT NULL,
  `pic_url` varchar(255) DEFAULT NULL,
  `num` int(11) DEFAULT NULL,
  `delist_time` varchar(255) DEFAULT NULL,
  `location` varchar(255) DEFAULT NULL,
  `price2` decimal(10,2) DEFAULT NULL COMMENT '从淘宝下载到的价格',
  `item_imgs` varchar(255) DEFAULT NULL,
  `prop_imgs` varchar(255) DEFAULT NULL,
  `is_virtual` varchar(255) DEFAULT NULL,
  `is_timing` varchar(255) DEFAULT NULL,
  `videos` varchar(255) DEFAULT NULL,
  `score` varchar(255) DEFAULT NULL,
  `one_station` varchar(255) DEFAULT NULL,
  `second_kill` varchar(255) DEFAULT NULL,
  `violation` varchar(255) DEFAULT NULL,
  `is_prepay` varchar(255) DEFAULT NULL,
  `ww_status` varchar(255) DEFAULT NULL,
  `wap_desc` varchar(255) DEFAULT NULL,
  `wap_detail_url` varchar(255) DEFAULT NULL,
  `presale_type` varchar(255) DEFAULT NULL,
  `presale_value` varchar(255) DEFAULT NULL,
  `is_sale` tinyint(1) DEFAULT '0' COMMENT '是否上架：0 否，1是',
  `is_release` tinyint(3) DEFAULT '0' COMMENT '是否上传过，默认0，未上传',
  `is_relation` tinyint(3) DEFAULT '0',
  `is_del` tinyint(3) DEFAULT '0',
  `is_synckc` tinyint(3) DEFAULT '0',
  `is_wlb` tinyint(3) DEFAULT '0',
  `is_update` tinyint(3) DEFAULT '1' COMMENT '是否更新（用于下载商品，删除未更新到的垃圾商品数据）',
  `updated` datetime DEFAULT NULL COMMENT '最新更新时间',
  `modified` varchar(30) DEFAULT '' COMMENT '修改时间',
  `sale_mode` varchar(20) NOT NULL COMMENT '销售模式：预售presale',
  `delivery_mode` varchar(20) NOT NULL COMMENT 'days承诺发货天数 ; time预售发货时间',
  `delivery_days_or_time` varchar(20) NOT NULL COMMENT '存放承诺发货期或预售发货时间',
  `local_kc` int(11) DEFAULT '-1' COMMENT '本地库存',
  `local_kc_updated` datetime DEFAULT NULL COMMENT '本地库存汇总时间',
  `last_suc_kc` int(11) DEFAULT '-1' COMMENT '最后一次同步库存数',
  `last_suc_updated` datetime DEFAULT NULL COMMENT '最后一次同步库存时间',
  `last_suc_log` text COMMENT '最后一次同步库存日志',
  `last_update_kc_sl` int(11) NOT NULL DEFAULT '-1' COMMENT '最后一次更新的库存数量',
  `last_update_kc_time` datetime NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '最后一次更新的库存时间',
  `last_update_success` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否更新成功',
  `last_update_err` varchar(100) NOT NULL DEFAULT '' COMMENT '更新失败信息',
  `efast_cl_sl` int(11) NOT NULL DEFAULT '-1' COMMENT 'efast库存分配数量',
  `gb_code` varchar(50) DEFAULT NULL COMMENT '商品国标码',
  PRIMARY KEY (`Id`),
  UNIQUE KEY `shop_num_iid` (`shop_code`,`num_iid`) USING BTREE,
  KEY `num_iid` (`num_iid`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=330 DEFAULT CHARSET=utf8;
