DROP TABLE IF EXISTS `api_taobao_fx_product`;
CREATE TABLE `api_taobao_fx_product` (
  `api_taobao_fx_product_id` int(11) unsigned AUTO_INCREMENT,
  `shop_code` varchar(50) DEFAULT '' COMMENT '店铺nick',
  `pid` varchar(50) DEFAULT '' COMMENT '产品ID',
  `name` varchar(50) DEFAULT '' COMMENT '产品名称',
  `productcat_id` varchar(50) DEFAULT '' COMMENT '产品线ID',
  `cost_price` varchar(50) DEFAULT '' COMMENT '采购价格，单位：元。',
  `retail_price_low` varchar(50) DEFAULT '' COMMENT '最低零售价，单位：分。',
  `retail_price_high` varchar(50) DEFAULT '' COMMENT '最高零售价，单位：分。',
  `outer_id` varchar(50) DEFAULT '' COMMENT '商家编码',
  `quantity` varchar(50) DEFAULT '' COMMENT '产品库存',
  `alarm_number` varchar(50) DEFAULT '' COMMENT '警戒库存',
  `pictures` varchar(50) DEFAULT '' COMMENT '产品图片路径',
  `desc_path` varchar(50) DEFAULT '' COMMENT '产品描述路径，通过http请求获取',
  `prov` varchar(50) DEFAULT '' COMMENT '所在地：省',
  `city` varchar(50) DEFAULT '' COMMENT '所在地：市',
  `postage_type` varchar(50) DEFAULT '' COMMENT '运费类型，可选值：seller（供应商承担运费）、buyer（分销商承担运费）',
  `postage_id` varchar(50) DEFAULT '' COMMENT '运费模板ID',
  `postage_ordinary` varchar(50) DEFAULT '' COMMENT '平邮费用，单位：元',
  `postage_fast` varchar(50) DEFAULT '' COMMENT '快递费用，单位：元',
  `postage_ems` varchar(50) DEFAULT '' COMMENT 'ems费用，单位：元',
  `have_invoice` varchar(50) DEFAULT '' COMMENT '是否有发票，可选值：false（否）、true（是）',
  `have_guarantee` varchar(50) DEFAULT '' COMMENT '是否有保修，可选值：false（否）、true（是）',
  `status` varchar(50) DEFAULT '' COMMENT '发布状态，可选值：up（上架）、down（下架）',
  `items_count` varchar(50) DEFAULT '' COMMENT '下载人数',
  `orders_count` varchar(50) DEFAULT '' COMMENT '累计采购次数',
  `created` varchar(50) DEFAULT '' COMMENT '创建时间',
  `modified` varchar(50) DEFAULT '' COMMENT '更新时间',
  `discount_id` varchar(50) DEFAULT '' COMMENT '折扣ID（新增参数）',
  `trade_type` varchar(50) DEFAULT '' COMMENT '分销方式：AGENT（只做代销，默认值）、DEALER（只做经销）、ALL（代销和经销都做）',
  `standard_price` varchar(50) DEFAULT '' COMMENT '采购基准价，单位：元。',
  `upshelf_time` varchar(50) DEFAULT '' COMMENT '铺货时间',
  `is_authz` varchar(50) DEFAULT '' COMMENT '查询产品列表时，查询入参增加is_authz:yes|no yes:需要授权 no:不需要授权',
  `category_id` varchar(50) DEFAULT '' COMMENT '类目id',
  `properties` text DEFAULT '' COMMENT '产品属性，格式为pid:vid;pid:vid',
  `property_alias` text DEFAULT '' COMMENT '属性别名，格式为pid:vid:alias;pid:vid:alias',
  `input_properties` text DEFAULT '' COMMENT '自定义属性，格式为pid:value;pid:value',
  `description` text DEFAULT '' COMMENT '产品描述的内容',
  `dealer_cost_price` varchar(50) DEFAULT '' COMMENT '经销采购价',
  `item_id` varchar(50) DEFAULT '' COMMENT '导入的商品ID',
  `scitem_id` varchar(50) DEFAULT '' COMMENT '关联的后端商品id',
  `standard_retail_price` varchar(50) DEFAULT '' COMMENT '零售基准价，单位：元',
  `images` text DEFAULT '' COMMENT '产品图片',
  `query_item_id` varchar(50) DEFAULT '' COMMENT '根据商品ID查询时，返回这个产品对应的商品ID，只对分销商查询接口有效',
  `reserved_quantity` varchar(50) DEFAULT '' COMMENT '预扣库存',
  `quota_quantity` varchar(50) DEFAULT '' COMMENT '配额可用库存',
  `spu_id` varchar(50) DEFAULT '' COMMENT '产品spu id',
  `last_update_time` timestamp DEFAULT '0000-00-00 00:00:00' COMMENT '最后更新时间',
  `is_allow_sync_inv` tinyint(3) DEFAULT '0' COMMENT '1:允许 0：不允许',
  PRIMARY KEY (`api_taobao_fx_product_id`),
  unique KEY(`pid`),
  KEY(`shop_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT '淘宝分销产品原始数据';