-- ----------------------------
-- Table structure for api_aliexpress_trade 速卖通订单主表
-- ----------------------------
DROP TABLE IF EXISTS `api_aliexpress_trade`;
CREATE TABLE `api_aliexpress_trade` (
  `api_aliexpress_trade_id` int(11) NOT NULL AUTO_INCREMENT,
  `gmtModified` varchar(50) DEFAULT '' COMMENT '交易创建时间',
  `gmtCreate` varchar(50) DEFAULT '' COMMENT '修改订单时间',
  `gmtTradeEnd` varchar(50) DEFAULT '' COMMENT '交易结束时间',
  `zip` varchar(50) DEFAULT '' COMMENT '邮政编码',
  `phoneNumber` varchar(50) DEFAULT '' COMMENT '电话号码',
  `province` varchar(50) DEFAULT '' COMMENT '省',
  `address2` varchar(50) DEFAULT '' COMMENT '地址',
  `phoneArea` varchar(50) DEFAULT '' COMMENT '手机区号',
  `phoneCountry` varchar(50) DEFAULT '' COMMENT '手机国家号',
  `contactPerson` varchar(50) DEFAULT '' COMMENT '收件人全名',
  `mobileNo` varchar(50) DEFAULT '' COMMENT '手机号',
  `city` varchar(50) DEFAULT '' COMMENT '市',
  `country` varchar(50) DEFAULT '' COMMENT '国家',
  `detailAddress` varchar(50) DEFAULT '' COMMENT '详细地址',
  `buyerInfoLastName` varchar(50) DEFAULT '' COMMENT '买家信息LastName',
  `buyerInfoLoginId` varchar(50) DEFAULT '' COMMENT '买家ID',
  `buyerInfoEmail` varchar(50) DEFAULT '' COMMENT '买家邮箱',
  `buyerInfoFirstName` varchar(50) DEFAULT '' COMMENT '买家信息FirstName',
  `buyerInfoCountry` varchar(50) DEFAULT '' COMMENT '买家国籍',
  `buyerloginid` varchar(50) DEFAULT '' COMMENT '买家ID',
  `issueStatus` varchar(50) DEFAULT '' COMMENT '纠纷状态("NO_ISSUE"无纠纷；"IN_ISSUE"纠纷中；“END_ISSUE”纠纷结束。)',
  `id` varchar(50) DEFAULT '' COMMENT '主订单id',
  `frozenStatus` varchar(50) DEFAULT '' COMMENT '冻结状态("NO_FROZEN"无冻结；"IN_FROZEN"冻结中；)',
  `logisticsStatus` varchar(50) DEFAULT '' COMMENT '物流状态（"WAIT_SELLER_SEND_GOODS"等待卖家发货;"SELLER_SEND_PART_GOODS"卖家部分发货；"SELLER_SEND_GOODS"卖家已发货；"BUYER_ACCEPT_GOODS"买家已确认收货；"NO_LOGISTICS"没有物流流转信息）',
  `sellerSignerFullname` varchar(50) DEFAULT '' COMMENT '卖家名称',
  `sellerOperatorLoginId` varchar(50) DEFAULT '' COMMENT '负责人loginId',
  `sellerOperatorAliidloginid` varchar(50) DEFAULT '' COMMENT '卖家子帐号',
  `paymentType` varchar(50) DEFAULT '' COMMENT '付款方式（migs信用卡支付走人民币渠道；migs102MasterCard支付并且走人民币渠道；migs101Visa支付并且走人民币渠道；pp101PayPal；mbMoneyBooker渠道；tt101BankTransfer支付；wu101WestUnion支付；wp101Visa走美金渠道的支付；wp102Mastercard走美金渠道的支付；qw101QIWI支付；cybs101Visa走CYBS渠道的支付；cybs102Mastercard走CYBS渠道的支付；wm101WebMoney支付；ebanx101巴西Beloto支付；）',
  `orderStatus` varchar(50) DEFAULT '' COMMENT '订单状态',
  `buyerSignerFullname` varchar(50) DEFAULT '' COMMENT '买家全名',
  `gmtPaySuccess` varchar(50) DEFAULT '' COMMENT '支付成功时间（与订单列表中gmtPayTime字段意义相同）',
  `loanStatus` varchar(50) DEFAULT '' COMMENT '放款状态',
  `fundStatus` varchar(50) DEFAULT '' COMMENT '资金状态(NOT_PAY,未付款；PAY_SUCCESS,付款成功；WAIT_SELLER_CHECK，卖家验款)',
  `LAAmount` varchar(50) DEFAULT '' COMMENT '物流金额',
  `LACent` varchar(50) DEFAULT '' COMMENT '',
  `LACurrencyCode` varchar(50) DEFAULT '' COMMENT '',
  `LACentFactor` varchar(50) DEFAULT '' COMMENT '',
  `LACurrencyDefaultFractionDigits` varchar(50) DEFAULT '' COMMENT '',
  `LACurrencyCurrencyCode` varchar(50) DEFAULT '' COMMENT '',
  `LACurrencySymbol` varchar(50) DEFAULT '' COMMENT '',
  `OAAmount` varchar(50) DEFAULT '' COMMENT '订单金额',
  `OACent` varchar(50) DEFAULT '' COMMENT '',
  `OACurrencyCode` varchar(50) DEFAULT '' COMMENT '',
  `OACentFactor` varchar(50) DEFAULT '' COMMENT '',
  `OACurrencyDefaultFractionDigits` varchar(50) DEFAULT '' COMMENT '',
  `OACurrencyCurrencyCode` varchar(50) DEFAULT '' COMMENT '',
  `OACurrencySymbol` varchar(50) DEFAULT '' COMMENT '',
  `IAAmount` varchar(50) DEFAULT '' COMMENT '产品总金额',
  `IACent` varchar(50) DEFAULT '' COMMENT '',
  `IACurrencyCode` varchar(50) DEFAULT '' COMMENT '',
  `IACentFactor` varchar(50) DEFAULT '' COMMENT '',
  `IACurrencyDefaultFractionDigits` varchar(50) DEFAULT '' COMMENT '',
  `IACurrencyCurrencyCode` varchar(50) DEFAULT '' COMMENT '',
  `IACurrencySymbol` varchar(50) DEFAULT '' COMMENT '',
  `refundInfo` varchar(50) DEFAULT '' COMMENT '退款信息(退款原因,退款状态,(WAIT_REFUND("wait_refund"),等待退款REFUND_OK("refund_ok"),退款成功REFUND_FROZEN("refund_frozen");退款冻结))',
  `loanInfo` varchar(50) DEFAULT '' COMMENT '放款信息("loan_none"无放款；"wait_loan"等待放款；"loan_ok"放款成功)',
  `logisticsTypeCode` varchar(50) DEFAULT '' COMMENT '物流公司类型',
  `gmtReceived` varchar(50) DEFAULT '' COMMENT '妥投时间',
  `logisticsNo` varchar(50) DEFAULT '' COMMENT '物流追踪号',
  `logisticsServiceName` varchar(50) DEFAULT '' COMMENT  '发货物流服务key',
  `gmtSend` varchar(50) DEFAULT '' COMMENT  '发货时间',
  `receiveStatus` varchar(50) DEFAULT '' COMMENT '妥投状态',
  PRIMARY KEY (`api_aliexpress_trade_id`),
  UNIQUE KEY `id` (`id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 ROW_FORMAT=COMPACT COMMENT '速卖通订单原始数据';