DROP TABLE IF EXISTS `api_taobao_ncm_order_detail`;
CREATE TABLE `api_taobao_ncm_order_detail` (
	`taobao_ncm_order_detail_id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
	`pid` int(11) DEFAULT '0',
	`status` varchar(32) COMMENT '交易状态',
	`refund_fee` decimal(20,2) COMMENT '退款金额',
	`id` varchar(128) COMMENT 'Number,子采购单id，淘宝交易主键，采购单未付款时为0.（只有支付宝 付款才有这个id，其余付款形式该字段为0）--示例:5552',
	`fenxiao_id` varchar(128) COMMENT 'Number,分销平台的子采购单主键--示例:1000',
	`sku_id` varchar(128) COMMENT 'Number,商品的SKU id。当存在时才会有值，建议使用sku_outer_id，sku_properties这两个值--示例:555',
	`tc_order_id` varchar(128) COMMENT 'Number,TC子订单ID（经销不显示）--示例:10000',
	`item_id` varchar(128) COMMENT 'Number,分销平台上的产品id，同FenxiaoProduct 的pid--示例:5555',
	`order_200_status` varchar(128) COMMENT 'String,代销采购单对应下游200订单状态。 可选值： WAIT_SELLER_SEND_GOODS(已付款，待发货) WAIT_BUYER_CONFIRM_GOODS(已付款，已发货) TRADE_CLOSED(已退款成功) TRADE_REFUNDING(退款中) TRADE_FINISHED(交易成功) TRADE_CLOSED_BY_TAOBAO(交易关闭)--示例:PAID_SEND_GOODS',
	`auction_price` decimal(20,2) COMMENT 'Price,分销商店铺中宝贝一口价--示例:100.1',
	`num` varchar(128) COMMENT 'Number,产品的采购数量。取值范围:大于零的整数--示例:50',
	`title` varchar(128) COMMENT 'String,采购的产品标题。--示例:裙子',
	`price` decimal(20,2) COMMENT 'Price,产品的采购价格。（精确到2位小数;单位:元。如:200.07，表示:200元7分）--示例:50',
	`total_fee` decimal(20,2) COMMENT 'Price,分销商应付金额=num(采购数量)*price(采购价)。（精确到2位小数;单位:元。如:200.07，表示:200元7分）--示例:200.07',
	`distributor_payment` decimal(20,2) COMMENT 'Price,分销商实付金额=total_fee（分销商应付金额）+改价-优惠。（精确到2位小数;单位:元。如:200.07，表示:200元7分）--示例:200.07',
	`buyer_payment` decimal(20,2) COMMENT 'Price,买家订单上对应的子单零售金额，除以num（数量）后等于最终宝贝的零售价格（精确到2位小数;单位:元。如:200.07，表示:200元7分）--示例:200.07',
	`bill_fee` decimal(20,2) COMMENT 'Price,发票应开金额。根据买家实际付款去除邮费后，按各个子单(商品)金额比例进行分摊后的金额，仅供开发票时做票面金额参考。--示例:100.1',
	`sc_item_id` varchar(128) COMMENT 'Number,后端商品id--示例:100000000',
	`tc_preferential_type` varchar(128) COMMENT 'String,商品优惠类型：聚划算、秒杀或其他--示例:聚划算',
	`tc_discount_fee` varchar(128) COMMENT 'Number,优惠金额，始终为正数，单位是分，不带小数--示例:1000',
	`tc_adjust_fee` varchar(128) COMMENT 'Number,商品的卖出金额调整，金额增加时为正数，金额减少时为负数，单位是分，不带小数--示例:1000',
	`discount_fee` decimal(20,2) COMMENT 'Price,优惠活动的折扣金额--示例:11.11',
	`promotion_type` varchar(128) COMMENT 'String,优惠活动类型 0=无优惠 1=限时折--示例:1',
	`features` varchar(128) COMMENT 'Feature [],Feature对象列表 目前已有的属性： attr_key为 www，attr_value为1 表示是www子订单 attr_key为 wwwStoreCode，attr_value 是www子订单发货的仓库编码 attr_key为isWt,attr_value为1 表示是网厅子订单 attr_key为wtInfo,attr_value为网厅相关合约信息--示例:查看',
	`old_sku_properties` varchar(128) COMMENT 'String,老的SKU属性值。如: 颜色:红色:别名;尺码:L:别名--示例:颜色:红色',
	`item_outer_id` varchar(128) COMMENT 'String,分销平台上商品商家编码。--示例:555',
	`sku_outer_id` varchar(128) COMMENT 'String,SKU商家编码。--示例:5555',
	`sku_properties` varchar(128) COMMENT 'String,SKU属性值。如: 颜色:红色:别名;尺码:L:别名--示例:颜色:红色',
	`snapshot_url` varchar(128) COMMENT 'String,快照地址。--示例:www.vancl.com',
	`created` date COMMENT 'Date,创建时间。格式 yyyy-MM-dd HH:mm:ss 。--示例:2000-1-1 0:00',
  	PRIMARY KEY (`taobao_ncm_order_detail_id`)
) ENGINE=INNODB DEFAULT CHARSET=utf8 COMMENT='api分销订单表';