DROP TABLE IF EXISTS `api_goods_sku`;
CREATE TABLE `api_goods_sku` (
  `api_goods_sku_id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `shop_code` varchar(128) DEFAULT '' COMMENT '店铺代码, 业务系统店铺代码',
  `goods_from_id` varchar(64) DEFAULT '' COMMENT '商品ID, 淘宝平台：num_iid',
  `source` varchar(64) DEFAULT '' COMMENT '来源 淘宝：taobao，后台：houtai，京东：jingdong，唯品会：weipinhui，当当：dangdang，拍拍：paipai，1号店：yihaodian，亚马逊：yamaxun，凡客：vjia，优购：yougou，聚美优品：jumei，麦网：m18，库巴：coo8，苏宁：suning，名鞋库：scn，阿里巴巴：alibaba，微购物：weigou，口袋通:koudaitong,工行:gonghang,银泰:yintai,走秀网:zouxiu,贝贝网:beibei,蘑菇街:mogujie,拍',
  `sku_id` varchar(255) DEFAULT '' COMMENT '平台sku_id 淘宝平台：sku_id',
  `goods_barcode` varchar(255) DEFAULT '' COMMENT '外部网店自己定义的Sku编号 淘宝平台：outer_id',
  `status` int(4) DEFAULT '1' COMMENT '平台SKU状态 0：删除 1：正常, 淘宝平台：status',
  `num` int(8) DEFAULT '0' COMMENT '数量 淘宝平台：quantity',
  `inv_num` int(8) DEFAULT '-1' COMMENT '业务系统库存数量',
  `price` decimal(20,2) DEFAULT '0.00' COMMENT '单价 淘宝平台：price',
  `stock_type` int(4) DEFAULT '0' COMMENT '平台商品库存扣减规则, 主表冗余字段 1：拍下减少库存 2：付款减少库存',
  `with_hold_quantity` varchar(64) DEFAULT '' COMMENT '平台sku预扣库存 淘宝平台：with_hold_quantity',
  `sku_properties` varchar(255) DEFAULT '' COMMENT '平台sku属性值。如：1243:1215;5626:5125, 淘宝平台：properties',
  `sku_properties_name` varchar(255) DEFAULT '' COMMENT '平台sku属性值。如：机身颜色:黑色;手机套餐:官方标配, 淘宝平台：properties_name',
  `inv_update_time` datetime DEFAULT NULL COMMENT '业务系统向本表更新库存时间',
  `sys_update_time` datetime DEFAULT '0000-00-00 00:00:00' COMMENT '业务库存变化时间',
  `inv_down_time` datetime DEFAULT NULL COMMENT '从第三方平台库存下载时间',
  `inv_up_time` datetime DEFAULT NULL COMMENT '向第三方平台库存上传时间',
  `first_insert_time` datetime DEFAULT NULL COMMENT '平台SKU数据第一次插入时间',
  `last_update_time` datetime DEFAULT NULL COMMENT '平台SKU数据最后一次更新时间',
  `lastchanged` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后修改时间',
  `is_allow_sync_inv` int(4) DEFAULT '0' COMMENT '业务系统是否允许同步库存, 1:允许 0：不允许',
  `is_sync_inv` int(4) DEFAULT '0' COMMENT '平台同步库存结果 1：已同步 0：未同步',
  `sale_mode` varchar(10) NOT NULL DEFAULT 'stock' COMMENT '销售模式：现货stock，预售presale',
  PRIMARY KEY (`api_goods_sku_id`),
  UNIQUE KEY `sku_id_and_source` (`sku_id`,`source`) USING BTREE,
  KEY `_goods_barcode` (`goods_barcode`) USING BTREE,
  KEY `_sys_update_time` (`sys_update_time`) USING BTREE,
  KEY `_is_allow_sync_inv` (`is_allow_sync_inv`) USING BTREE,
  KEY `_status` (`status`) USING BTREE,
  KEY `_shop_code` (`shop_code`) USING BTREE,
  KEY `index1` (`goods_from_id`) USING BTREE
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COMMENT='api商品sku表';
