DROP TABLE IF EXISTS `api_goods`;
CREATE TABLE `api_goods` (
  `api_goods_id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `shop_code` varchar(128) DEFAULT '' COMMENT '店铺代码, 业务系统店铺代码',
  `goods_name` varchar(128) DEFAULT '' COMMENT '商品名称, 淘宝平台：title',
  `goods_code` varchar(64) DEFAULT '' COMMENT '商品代码, 淘宝平台: outer_id ',
  `goods_from_id` varchar(64) DEFAULT '' COMMENT '商品ID, 淘宝平台：num_iid',
  `num` varchar(64) DEFAULT '' COMMENT '商品数量, 淘宝平台：num',
  `seller_nick` varchar(255) DEFAULT NULL COMMENT '卖家昵称, 淘宝平台：卖家主旺旺号 nick',
  `source` varchar(64) DEFAULT '' COMMENT '来源 淘宝：taobao，后台：houtai，京东：jingdong，唯品会：weipinhui，当当：dangdang，拍拍：paipai，1号店：yihaodian，亚马逊：yamaxun，凡客：vjia，优购：yougou，聚美优品：jumei，麦网：m18，库巴：coo8，苏宁：suning，名鞋库：scn，阿里巴巴：alibaba，微购物：weigou，口袋通:koudaitong,工行:gonghang,银泰:yintai,走秀网:zouxiu,贝贝网:beibei,蘑菇街:mogujie,拍鞋网:paixie,好乐买:okbuy,乐蜂:lefeng',
  `status` int(4) DEFAULT '0' COMMENT '0：在库 1：在售 淘宝平台：approve_status',
  `stock_type` int(4) DEFAULT '1' COMMENT '1：拍下减少库存 2：付款减少库存 淘宝平台：sub_stock',
  `onsale_time` datetime DEFAULT NULL COMMENT '上架时间 淘宝平台：list_time',
  `has_sku` int(4) DEFAULT '0' COMMENT 'sku是否存在 1:存在 0：不存在',
  `price` decimal(20,2) DEFAULT '0.00' COMMENT '单价 淘宝平台：price',
  `goods_img` varchar(128) DEFAULT '' COMMENT '主图地址 淘宝平台：pic_url',
  `goods_desc` text COMMENT '详细描述 淘宝平台：desc',
  `is_lock_inv` int(4) DEFAULT '0' COMMENT '是否锁库存 0：未锁 1：锁库存, 业务系统维护',
  `sale_start_time` datetime DEFAULT NULL COMMENT '业务系统开始时间',
  `sale_end_time` datetime DEFAULT NULL COMMENT '业务系统结束时间',
  `first_insert_time` datetime DEFAULT NULL COMMENT '平台第一次数据下载时间',
  `last_update_time` datetime DEFAULT NULL COMMENT '平台最后一次更新时间',
  `lastchanged` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '数据变更时间戳',
  `is_allow_sync_inv` int(4) DEFAULT '0' COMMENT '1:允许 0：不允许',
  `is_sync_inv` int(4) DEFAULT '0' COMMENT '平台同步库存结果 1：已同步 0：未同步',
  `invalid_status` int(4) DEFAULT '1' COMMENT '0：无效平台不存在1：有效',
  `invalid_time` datetime DEFAULT NULL COMMENT '标记为删除状态的时间',
  `cat` varchar(255) DEFAULT NULL COMMENT '分类',
  `brand` varchar(255) DEFAULT NULL COMMENT '品牌',
  PRIMARY KEY (`api_goods_id`),
  UNIQUE KEY `id_and_source` (`goods_from_id`,`source`) USING BTREE,
  KEY `index1` (`shop_code`) USING BTREE,
  KEY `index2` (`is_allow_sync_inv`) USING BTREE,
  KEY `index3` (`is_sync_inv`) USING BTREE,
  KEY `index4` (`invalid_status`) USING BTREE
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COMMENT='api商品表';

