DROP TABLE IF EXISTS `api_taobao_order`;
CREATE TABLE `api_taobao_order` (
  `id` int(11) unsigned AUTO_INCREMENT,
  `ttid` int(11) unsigned COMMENT '父ID',
  `tid` varchar(30) DEFAULT '' COMMENT '父订单的交易编号',
  `shop_code` varchar(30) DEFAULT '' COMMENT '店铺nick',
  `total_fee` float(7,2) COMMENT '应付金额（商品价格 * 商品数量 + 手工调整金额 - 子订单级订单优惠金额）',
  `discount_fee` float(5,2) COMMENT '子订单级订单优惠金额',
  `adjust_fee` float(7,2) COMMENT '手工调整金额',
  `payment` float(7,2) COMMENT '子订单实付金额',
  `modified` datetime COMMENT '订单修改时间，目前只有taobao.trade.ordersku.update会返回此字段',
  `item_meal_id` int unsigned COMMENT '套餐ID',
  `status` varchar(30) COMMENT '交易状态。可选值: TRADE_NO_CREATE_PAY(没有创建支付宝交易)  WAIT_BUYER_PAY(等待买家付款) SELLER_CONSIGNED_PART(卖家部分发货) WAIT_SELLER_SEND_GOODS(等待卖家发货,即:买家已付款) WAIT_BUYER_CONFIRM_GOODS(等待买家确认收货,即:卖家已发货) TRADE_BUYER_SIGNED(买家已签收,货到付款专用) TRADE_FINISHED(交易成功) TRADE_CLOSED(付款以后用户退款成功，交易自动关闭) TRADE_CLOSED_BY_TAOBAO(付款以前，卖家或买家主动关闭交易) PAY_PENDING(国际信用卡支付付款确认中) WAIT_PRE_AUTH_CONFIRM(0元购合约中)',
  `iid` varchar(20) COMMENT '商品的字符串编号(注意：iid近期即将废弃，请用num_iid参数)',
  `sku_id` int unsigned COMMENT '商品的最小库存单位Sku的id.可以通过taobao.item.sku.get获取详细的Sku信息',
  `sku_properties_name` varchar(30) COMMENT 'SKU的值。如：机身颜色:黑色;手机套餐:官方标配',
  `item_meal_name` varchar(30) COMMENT '套餐的值。如：M8原装电池:便携支架:M8专用座充:莫凡保护袋',
  `num` tinyint unsigned COMMENT '购买数量。取值范围:大于零的整数',
  `title` varchar(200) COMMENT '商品标题',
  `price` float(7,2) COMMENT '商品价格',
  `pic_path` varchar(50) COMMENT '商品图片的绝对路径,http开头',
  `seller_nick` varchar(30) COMMENT '卖家昵称',
  `buyer_nick` varchar(30) COMMENT '买家昵称',
  `refund_status` varchar(30) COMMENT '退款状态',
  `oid` varchar(30) COMMENT '子订单编号',
  `outer_iid` varchar(30) COMMENT '商家外部编码(可与商家外部系统对接)。外部商家自己定义的商品Item的id，可以通过taobao.items.custom.get获取商品的Item的信息',
  `outer_sku_id` varchar(20) COMMENT '外部网店自己定义的sku编号',
  `snapshot_url` varchar(30) COMMENT '订单快照URL',
  `snapshot` text COMMENT '订单快照详细信息',
  `timeout_action_time` datetime COMMENT '订单超时到期时间',
  `buyer_rate` tinyint(1) COMMENT '买家是否已评价。可选值：true(已评价)，false(未评价)',
  `seller_rate` tinyint(1) COMMENT '卖家是否已评价。可选值：true(已评价)，false(未评价)',
  `refund_id` int unsigned COMMENT '最近退款ID',
  `seller_type` char(1) COMMENT '卖家类型，可选值为：B（商城商家），C（普通卖家）',
  `num_iid` varchar(20) COMMENT '商品数字ID',
  `cid` varchar(10) COMMENT '交易商品对应的类目ID',
  `is_oversold` tinyint(1) COMMENT '是否超卖',
  `error_code` varchar(10) COMMENT '错误代码',
  `error_msg` varchar(30) COMMENT '错误消息',
  `divide_order_fee` float(7,2) COMMENT '分摊之后的实付金额',
  `part_mjz_discount` float(5,2) COMMENT '优惠分摊',
  `logistics_company` varchar(20) COMMENT '子订单发货的快递公司名称',
  `invoice_no` varchar(20) COMMENT '子订单所在包裹的运单号',
  `end_time` datetime COMMENT '子订单的交易结束时间',
  PRIMARY KEY (`id`),
  unique key(`oid`),
  KEY(`ttid`),
  KEY(`tid`),
  KEY(`shop_code`),
  KEY(`seller_nick`),
  KEY(`buyer_nick`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT '淘宝订单明细';