-- ----------------------------
-- Table structure for api_mogujie_trade 蘑菇街订单主表
-- ----------------------------
DROP TABLE IF EXISTS `api_mogujie_trade`;
CREATE TABLE `api_mogujie_trade` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `tid` varchar(30) DEFAULT '' COMMENT '交易编号(交易ID)',
  `title` varchar(30) DEFAULT '' COMMENT '交易标题',
  `created` varchar(40) DEFAULT '' COMMENT '交易创建时间',
  `tradetype` varchar(30) DEFAULT '' COMMENT '交易类型。可选值:fixed(一口价) presell(预售)',
  `status` varchar(255) DEFAULT '' COMMENT '交易状态,可选值: TRADE_ACTIVE:交易处理中,TRADE_CLOSED:交易作废即交易关闭, TRADE_FINISHED:交易成功, TRADE_UNPAYED :未付款',
  `pay_status` varchar(100) DEFAULT '' COMMENT '交易支付状态,可选值:PAY_NO:未付款, PAY_FINISH:已付款, PAY_ PART:部分付款, REFUND_PART:部分退款, REFUND_ALL:全额退款,REFUNDING:正在退 款中',
  `ship_status` varchar(30) DEFAULT '' COMMENT '交易物流状态,可选值:SHIP_NO:未发货 SHIP_PREPARE:配货中 SHIP_RECEIVED:已收到货',
  `total_trade_fee` varchar(30) DEFAULT '' COMMENT '交易应付总额(包括商品价格 + 配送费用)',
  `payed_fee` varchar(30) DEFAULT '' COMMENT '已支付金额',
  `shipping_type` varchar(30) DEFAULT '' COMMENT '交易物流方式名称',
  `payment_tid` varchar(30) DEFAULT '' COMMENT '支付方式ID',
  `payment_type` varchar(255) DEFAULT '' COMMENT '支付方式名称',
  `pay_time` varchar(255) DEFAULT '' COMMENT '付款时间',
  `lastmodify` varchar(255) DEFAULT '' COMMENT '订单修改时间',
  `end_time` varchar(30) DEFAULT '' COMMENT '交易成功时间',
  `confirm_time` varchar(30) DEFAULT '' COMMENT '订单确认时间',
  `goods_discount_fee` varchar(255) DEFAULT '' COMMENT '商品优惠金额',
  `orders_discount_fee` varchar(30) DEFAULT '' COMMENT '订单优惠金额',
  `consign_time` varchar(30) DEFAULT '' COMMENT '卖家发货时间',
  `receiver_name` varchar(30) NOT NULL COMMENT '收货人的姓名',
  `receiver_mobile` varchar(255) DEFAULT '' COMMENT '收货人的手机号码',
  `receiver_email` varchar(50) DEFAULT '' COMMENT '收货人email地址',
  `receiver_state` varchar(30) DEFAULT '' COMMENT '收货人的所在省份',
  `receiver_city` varchar(30) DEFAULT '' COMMENT '收货人的所在城市',
  `receiver_district` varchar(100) DEFAULT '' COMMENT '收货人的所在地区',
  `receiver_address` varchar(255) DEFAULT '' COMMENT '收货人的详细地址',
  `receiver_zip` varchar(50) DEFAULT '' COMMENT '收货人的邮编',
  `receiver_phone` varchar(50) DEFAULT '' COMMENT '收货人的电话号码',
  `seller_id` varchar(50) DEFAULT '' COMMENT '卖家ID',
  `seller_uname` varchar(50) DEFAULT '' COMMENT '卖家帐号',
  
  `buyer_name` varchar(50) DEFAULT '' COMMENT '买家姓名',
  `buyer_id` varchar(50) DEFAULT '' COMMENT '买家(会员)ID',
  `buyer_uname` varchar(50) DEFAULT '' COMMENT '买家帐号',
  `buyer_email` varchar(50) DEFAULT '' COMMENT '买家email',
  `buyer_memo` varchar(50) DEFAULT '' COMMENT '买家备注',
  `buyer_rate` varchar(50) DEFAULT '' COMMENT '买家是否已评价。可选值:true(已评价),false(未评价)',
  `orders_number` varchar(50) DEFAULT '' COMMENT '当前交易下订单数量',
  `trade_memo` varchar(50) DEFAULT '' COMMENT '交易的备注内容',
  `logistics_name` varchar(50) DEFAULT '' COMMENT '快递名称',
  `logistics_no` varchar(50) DEFAULT '' COMMENT '快递单号',
  `cod_status` varchar(50) DEFAULT '' COMMENT '是否签收 0-买家触发,1-快递签收触发( 自动),2-超时触发(自动)',
  `step_trade_status` varchar(50) DEFAULT '' COMMENT '分阶段订单状态: FRONT_NOPAID_FINAL_NOPAID(定金未付尾款 未付),FRONT_PAID_FINAL_NOPAID(定金已 付尾款未付),FRONT_PAID_FINAL_PAID(定 金和尾款都付)',
  `step_paid_fee` varchar(50) DEFAULT '' COMMENT '分阶段付款金额',
  `mark_desc` varchar(50) DEFAULT '' COMMENT '异常订单处理意见',
  `is_errortrade` varchar(50) DEFAULT '' COMMENT '是否为异常订单,true:是 false:否',
  
  `shop_code` varchar(255) DEFAULT '' COMMENT 'efast商店代码',
  PRIMARY KEY (`id`),
  UNIQUE KEY `tid` (`tid`) USING BTREE,
  KEY `shop_code` (`shop_code`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 ROW_FORMAT=COMPACT;