DROP TABLE IF EXISTS `api_vipshop_trade`;

CREATE TABLE `api_vipshop_trade` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '唯品会订单列表',
  `order_sn` varchar(50) NOT NULL COMMENT '订单编号',
  `stat` varchar(50) DEFAULT '0' COMMENT '订单状态编码',
  `buyer` varchar(50) DEFAULT '0' COMMENT '收货人',
  `address` varchar(100) DEFAULT NULL COMMENT '收货地址',
  `mobile` varchar(50) DEFAULT NULL COMMENT '手机号码',
  `tel` varchar(50) NOT NULL COMMENT '联系电话',
  `postcode` varchar(50) NOT NULL COMMENT '邮政编码',
  `city` varchar(50) DEFAULT NULL COMMENT '城市',
  `state` varchar(50) DEFAULT NULL COMMENT '省份',
  `country_id` varchar(50) DEFAULT NULL COMMENT '国家ID',
  `invoice` varchar(50) DEFAULT NULL COMMENT '发票抬头',
  `carriage` varchar(50) DEFAULT NULL COMMENT '快递金额（计算 整张出库单商品金额总和+快递费用 == 订单金额）',
  `remark` varchar(255) DEFAULT NULL COMMENT '备注',
  `transport_day` varchar(50) DEFAULT '0' COMMENT '期望收货时间',
  `vendor_id` varchar(50) DEFAULT NULL COMMENT '供应商ID',
  `vendor_name` varchar(50) DEFAULT NULL COMMENT '供应商名称',
  `ex_fav_money` varchar(50) DEFAULT NULL COMMENT '促销优惠金额',
  `favourable_money` varchar(50) DEFAULT NULL COMMENT '优惠金额',
  `goods_money` varchar(50) DEFAULT NULL COMMENT '整张出库单商品金额总和(计算发票金额 == 整张出库单商品金额总和 + 快递费用 - 优惠金额 - 促销优惠金额)',
  `add_time` varchar(50) DEFAULT NULL COMMENT '订单下单时间',
  `po` varchar(50) DEFAULT NULL COMMENT 'po号',
  `county` varchar(100) DEFAULT NULL COMMENT '区',
  `shop_code` int(10) DEFAULT NULL COMMENT 'efast商店代码',
  `efast_order_sn` varchar(20) DEFAULT NULL COMMENT 'efast交易号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `order_sn` (`order_sn`) USING BTREE,
  KEY `tel` (`tel`) USING BTREE,
  KEY `add_time` (`add_time`) USING BTREE,
  KEY `po` (`po`) USING BTREE,
  KEY `goods_money` (`goods_money`) USING BTREE,
  KEY `shop_code` (`shop_code`) USING BTREE
) ENGINE=InnoDB  DEFAULT CHARSET=utf8