DROP TABLE IF EXISTS `api_taobao_ncm_order`;
CREATE TABLE `api_taobao_ncm_order` (
	`taobao_ncm_order_id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
	`fenxiao_id` varchar(128) COMMENT 'Number,分销流水号，分销平台产生的主键--示例:1001',
	`pay_type` varchar(128) COMMENT 'String,支付方式：ALIPAY_SURETY（支付宝担保交易）、ALIPAY_CHAIN（分账交易）、TRANSFER（线下转账）、PREPAY（预存款）、IMMEDIATELY（即时到账）、CASHGOODS（先款后货）--示例:ALIPAY_SURETY',
	`trade_type` varchar(128) COMMENT 'String,分销方式：AGENT（代销）、DEALER（经销）--示例:AGENT',
	`distributor_from` varchar(128) COMMENT 'String,分销商来源网站（taobao）。--示例:taobao',
	`id` varchar(128) COMMENT 'Number,供应商交易ID 非采购单ID，如果改发货状态 是需要该ID，ID在用户未付款前为0，付款后有具体值（发货时使用该ID）--示例:555',
	`status` varchar(50) COMMENT 'String,采购单交易状态。可选值：--示例:TRADE_FINISHED(交易成功)',
	`buyer_nick` varchar(128) COMMENT 'String,买家nick，供应商查询不会返回买家昵称，分销商查询才会返回。--示例:zhangsan',
	`memo` varchar(128) COMMENT 'String,采购单留言。（代销模式下信息包括买家留言和分销商留言）--示例:留言。',
	`tc_order_id` varchar(128) COMMENT 'Number,主订单ID （经销不显示）--示例:112233',
	`receiver` varchar(255) COMMENT 'Receiver,买家详细的信息。--示例:查看',
	`shipping` varchar(255) COMMENT 'String,配送方式，FAST(快速)、EMS、ORDINARY(平邮)、SELLER(卖家包邮)--示例:FAST',
	`logistics_company_name` varchar(255) COMMENT 'String,物流公司--示例:EMS',
	`logistics_id` varchar(255) COMMENT 'String,运单号--示例:123123',
	`isv_custom_key` varchar(255) COMMENT 'String [],自定义key--示例:isv_custom_key',
	`isv_custom_value` varchar(255) COMMENT 'String [],自定义值--示例:isv_custom_value',
	`end_time` date COMMENT 'Date,交易结束时间--示例:2000-1-1 0:00',
	`supplier_flag` varchar(255) COMMENT 'Number,返回供应商备注旗帜 vlaue在1-5之间。非1-5之间，都采用1作为默认。 1:红色 2:黄色 3:绿色 4:蓝色 5:粉红色--示例:1',
	`buyer_payment` decimal(20,2) COMMENT 'Price,买家支付给分销商的总金额。注意买家购买的商品可能不是全部来自同一供货商，请同时参考子单上的相关金额。（精确到2位小数;单位:元。如:200.07，表示:200元7分）--示例:200.07',
	`order_messages` varchar(255) COMMENT 'OrderMessage [],采购单留言列表--示例:查看',
	`sub_purchase_orders` varchar(255) COMMENT 'SubPurchaseOrder [],子订单的详细信息列表。--示例:查看',
	`buyer_taobao_id` varchar(255) COMMENT 'String,加密后的买家淘宝ID，长度为32位--示例:F21121542129F21121542129F2112154',
	`features` varchar(255) COMMENT 'Feature [],主订单属性信息，key-value形式： orderNovice ：订单发票抬头； orderNoviceContent ：代表发票明细--示例:查看',
	`supplier_from` varchar(255) COMMENT 'String,供应商来源网站, values: taobao, alibaba--示例:values: taobao',
	`supplier_username` varchar(255) COMMENT 'String,供应商在来源网站的帐号名。--示例:zhangsan',
	`distributor_username` varchar(255) COMMENT 'String,分销商在来源网站的帐号名。--示例:zhangsan',
	`created` date COMMENT 'Date,采购单创建时间。格式:yyyy-MM-dd HH:mm:ss--示例:2000-1-1 0:00',
	`alipay_no` varchar(255) COMMENT 'String,支付宝交易号。--示例:5588',
	`total_fee` decimal(20,2) COMMENT 'Price,采购单总额（不含邮费,精确到2位小数;单位:元。如:200.07，表示:200元7分 )--示例:200.07',
	`post_fee` decimal(20,2) COMMENT 'Price,采购单邮费。(精确到2位小数;单位:元。如:200.07，表示:200元7分 )--示例:200.07',
	`distributor_payment` decimal(20,2) COMMENT 'Price,分销商实付金额。(精确到2位小数;单位:元。如:200.07，表示:200元7分 )--示例:200.07',
	`snapshot_url` varchar(255) COMMENT 'String,订单快照URL--示例:www.vancl.com',
	`pay_time` date COMMENT 'Date,付款时间。格式:yyyy-MM-dd HH:mm:ss--示例:2000-1-1 0:00',
	`consign_time` date COMMENT 'Date,物流发货时间。格式:yyyy-MM-dd HH:mm:ss--示例:2000-1-1 0:00',
	`modified` date COMMENT 'Date,交易修改时间。格式:yyyy-MM-dd HH:mm:ss--示例:2000-1-1 0:00',
  	PRIMARY KEY (`taobao_ncm_order_id`)
) ENGINE=INNODB DEFAULT CHARSET=utf8 COMMENT='api分销订单表';
alter table api_taobao_ncm_order add UNIQUE fenxiao_id(fenxiao_id);