DROP TABLE IF EXISTS `api_taobao_record`;
CREATE TABLE `api_taobao_record` (
  `taobao_record_id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `shop_code` VARCHAR(128) DEFAULT '' COMMENT '店铺代码',
  `end_time` datetime DEFAULT NULL COMMENT '交易结束时间。交易成功时间(更新交易状态为成功的同时更新)/确认收货时间或者交易关闭时间 。格式:yyyy-MM-dd HH:mm:ss',
  `buyer_message` varchar(255) DEFAULT NULL COMMENT '买家留言',
  `shipping_type` varchar(255) DEFAULT NULL COMMENT '创建交易时的物流方式（交易完成前，物流方式有可能改变，但系统里的这个字段一直不变）。可选值：ems, express, post, free, virtual。',
  `buyer_cod_fee` varchar(255) DEFAULT NULL COMMENT '买家货到付款服务费。精确到2位小数;单位:元。如:12.07，表示:12元7分',
  `seller_cod_fee` varchar(255) DEFAULT NULL COMMENT '卖家货到付款服务费。精确到2位小数;单位:元。如:12.07，表示:12元7分',
  `express_agency_fee` varchar(255) DEFAULT NULL COMMENT '快递代收款。精确到2位小数;单位:元。如:212.07，表示:212元7分',
  `alipay_warn_msg` varchar(255) DEFAULT NULL,
  `status` varchar(255) DEFAULT NULL COMMENT '交易状态:TRADE_NO_CREATE_PAY没有创建支付宝交易|WAIT_BUYER_PAY等待买家付款|WAIT_SELLER_SEND_GOODS等待卖家发货| WAIT_BUYER_CONFIRM_GOODS等待买家确认收货,即:卖家已发货|TRADE_BUYER_SIGNED买家已签收,货到付款专用|TRADE_FINISHED交易成功|TRADE_CLOSED:付款以后用户退款成功，交易自动关闭|TRADE_CLOSED_BY_TAOBAO:付款以前，卖家或买家主动关闭交易',
  `buyer_memo` varchar(255) DEFAULT NULL COMMENT '买家备注（与淘宝网上订单的买家备注对应，只有买家才能查看该字段）',
  `seller_memo` varchar(255) DEFAULT NULL COMMENT '卖家备注（与淘宝网上订单的卖家备注对应，只有卖家才能查看该字段）',
  `modified` datetime DEFAULT NULL COMMENT '交易修改时间(用户对订单的任何修改都会更新此字段)。格式:yyyy-MM-dd HH:mm:ss',
  `buyer_flag` tinyint(3) DEFAULT NULL COMMENT '买家备注旗帜（与淘宝网上订单的买家备注旗帜对应，只有买家才能查看该字段）',
  `seller_flag` tinyint(3) DEFAULT NULL COMMENT '卖家备注旗帜（与淘宝网上订单的卖家备注旗帜对应，只有卖家才能查看该字段）',
  `trade_from` varchar(255) DEFAULT NULL COMMENT '交易来源。 WAP(手机);HITAO(嗨淘);TOP(TOP平台);TAOBAO(普通淘宝);JHS(聚划算)',
  `seller_nick` varchar(255) DEFAULT NULL COMMENT '卖家昵称',
  `buyer_nick` varchar(255) DEFAULT NULL COMMENT '买家昵称',
  `title` varchar(255) DEFAULT NULL COMMENT '交易标题，以店铺名作为此标题的值。注:taobao.trades.get接口返回的Trade中的title是商品名称',
  `type` varchar(255) DEFAULT NULL COMMENT '交易类型，fixed:一口价|auction:拍卖| guarantee_trade:一口价、拍卖|auto_delivery:自动发货|independent_simple_trade:旺店入门版交易|independent_shop_trade:旺店标准版交易|ec:直冲|cod:货到付款|fenxiao:分销|game_equipment:游戏装备|shopex_trade:ShopEX交易|netcn_trade:万网交易|external_trade:统一外部交易',
  `created` datetime DEFAULT NULL COMMENT '交易创建时间。格式:yyyy-MM-dd HH:mm:ss',
  `iid` varchar(255) DEFAULT NULL COMMENT '商品字符串编号(注意：iid近期即将废弃，请用num_iid参数)',
  `price` varchar(255) DEFAULT NULL COMMENT '	商品价格。精确到2位小数；单位：元。如：200.07，表示：200元7分',
  `pic_path` varchar(255) DEFAULT NULL COMMENT '商品图片绝对途径',
  `num` int(11) DEFAULT '1' COMMENT '商品购买数量。取值范围：大于零的整数',
  `tid` bigint(20) DEFAULT NULL COMMENT '交易编号 (父订单的交易编号)',
  `alipay_no` varchar(255) DEFAULT NULL COMMENT '支付宝交易号，如：2009112081173831',
  `payment` varchar(255) DEFAULT NULL COMMENT '实付金额。精确到2位小数;单位:元。如:200.07，表示:200元7分',
  `discount_fee` varchar(255) DEFAULT NULL COMMENT '系统优惠金额（如打折，VIP，满就送等），精确到2位小数，单位：元。如：200.07，表示：200元7分',
  `adjust_fee` varchar(255) DEFAULT NULL COMMENT '卖家手工调整金额，精确到2位小数，单位：元。如：200.07，表示：200元7分',
  `snapshot_url` varchar(255) DEFAULT NULL COMMENT '交易快照地址',
  `snapshot` varchar(255) DEFAULT NULL COMMENT '交易快照详细信息',
  `seller_rate` char(5) NOT NULL DEFAULT '' COMMENT '卖家是否已评价。可选值:true(已评价),false(未评价)',
  `buyer_rate` char(5) NOT NULL DEFAULT '' COMMENT '买家是否已评价。可选值:true(已评价),false(未评价)',
  `trade_memo` varchar(255) DEFAULT NULL COMMENT '交易备注，通过taobao.trade.add接口创建',
  `pay_time` datetime DEFAULT NULL COMMENT '付款时间。格式:yyyy-MM-dd HH:mm:ss',
  `buyer_obtain_point_fee` int(11) DEFAULT '0' COMMENT '买家获得积分,返点的积分。格式:100;单位:个',
  `point_fee` int(11) DEFAULT '0' COMMENT '买家使用积分。格式:100;单位:个.',
  `real_point_fee` int(11) DEFAULT '0' COMMENT '买家实际使用积分（扣除部分退款使用的积分）。格式:100;单位:个',
  `total_fee` varchar(255) DEFAULT NULL COMMENT '商品金额（商品价格乘以数量的总金额）。精确到2位小数;单位:元。如:200.07，表示:200元7分',
  `post_fee` varchar(255) DEFAULT NULL COMMENT '邮费。精确到2位小数;单位:元。如:200.07，表示:200元7分',
  `buyer_alipay_no` varchar(255) DEFAULT NULL COMMENT '买家支付宝账号',
  `receiver_name` varchar(255) DEFAULT NULL COMMENT '收货人的姓名',
  `receiver_state` varchar(255) DEFAULT NULL COMMENT '收货人的所在省份',
  `receiver_city` varchar(255) DEFAULT NULL COMMENT '收货人的所在城市',
  `receiver_district` varchar(255) DEFAULT NULL COMMENT '收货人的所在地区',
  `receiver_address` varchar(255) DEFAULT NULL COMMENT '收货人的详细地址',
  `receiver_zip` varchar(255) DEFAULT NULL COMMENT '收货人的邮编',
  `receiver_mobile` varchar(255) DEFAULT NULL COMMENT '收货人的手机号码',
  `receiver_phone` varchar(255) DEFAULT NULL COMMENT '收货人的电话号码',
  `consign_time` datetime DEFAULT NULL COMMENT '卖家发货时间。格式:yyyy-MM-dd HH:mm:ss',
  `buyer_email` varchar(255) DEFAULT NULL COMMENT '买家邮件地址',
  `commission_fee` varchar(255) DEFAULT NULL COMMENT '交易佣金。精确到2位小数;单位:元。如:200.07，表示:200元7分',
  `seller_alipay_no` varchar(255) DEFAULT NULL COMMENT '卖家支付宝账号',
  `seller_mobile` varchar(255) DEFAULT NULL COMMENT '卖家手机',
  `seller_phone` varchar(255) DEFAULT NULL COMMENT '卖家电话',
  `seller_name` varchar(255) DEFAULT NULL COMMENT '卖家姓名',
  `seller_email` varchar(255) DEFAULT NULL COMMENT '卖家邮件地址',
  `available_confirm_fee` double DEFAULT '0' COMMENT '交易中剩余的确认收货金额（这个金额会随着子订单确认收货而不断减少，交易成功后会变为零）。精确到2位小数;单位:元。如:200.07，表示:200 元7分',
  `has_post_fee` char(5) NOT NULL DEFAULT '' COMMENT '是否包含邮费。与available_confirm_fee同时使用。可选值:true(包含),false(不包含)',
  `received_payment` varchar(255) DEFAULT NULL,
  `cod_fee` varchar(255) DEFAULT NULL COMMENT '货到付款服务费。精确到2位小数;单位:元。如:12.07，表示:12元7分',
  `cod_status` varchar(255) DEFAULT NULL COMMENT '货到付款物流状态。(EW_CREATED(订单已创建))',
  `timeout_action_time` datetime DEFAULT NULL,
  `is_3D` char(5) NOT NULL DEFAULT '' COMMENT '是否是3D淘宝交易',
  `num_iid` int(11) DEFAULT NULL COMMENT '商品数字编号',
  `promotion` varchar(255) DEFAULT NULL COMMENT '交易促销详细信息',
  `invoice_name` varchar(255) DEFAULT NULL COMMENT '发票抬头',
  `alipay_url` varchar(255) DEFAULT NULL COMMENT '创建交易接口成功后，返回的支付url',
  `is_brand_sale` int(4) NOT NULL DEFAULT '0' COMMENT '表示是否是品牌特卖订单，如果是返回true，如果不是返回false',
  `is_lgtype` int(4) NOT NULL DEFAULT '0' COMMENT '是否需要物流宝发货的标识，如果为true，则需要可以用物流宝来发货，如果未false，则该订单不能用物流宝发货。',
  `is_force_wlb` int(4) NOT NULL DEFAULT '0' COMMENT '代表订单是否是强制使用物流宝发货，如果是返回true,如果不是返回false',
  `step_trade_status` varchar(255) DEFAULT NULL COMMENT '分阶段付款的订单状态（例如万人团订单等），目前有三返回状态 FRONT_NOPAID_FINAL_NOPAID(定金未付尾款未付)，FRONT_PAID_FINAL_NOPAID(定金已付尾款未付)，FRONT_PAID_FINAL_PAID(定金和尾款都付)',
  `step_paid_fee` varchar(255) DEFAULT NULL COMMENT '分阶段付款的已付金额（万人团订单已付金额）',
  `mark_desc` varchar(255) DEFAULT NULL COMMENT '订单出现异常问题的时候，给予用户的描述',
  
  `o2o` varchar(255) DEFAULT NULL COMMENT 'O2O订单来源,例如CRM',
  `o2o_delivery` varchar(255) DEFAULT NULL COMMENT '配送方式:inshop',
  `o2o_guide_id` varchar(255) DEFAULT NULL COMMENT '导购员ID',
  `o2o_guide_name` varchar(255) DEFAULT NULL COMMENT '导购员名称',
  `o2o_shop_id` varchar(255) DEFAULT NULL COMMENT '提货线下店铺ID',
  `o2o_shop_name` varchar(255) DEFAULT NULL COMMENT '提货线下店铺名称',
  
  `vip_code` int(11) NOT NULL DEFAULT '0' COMMENT '预转入会员vip_code',
  `express_code` varchar(20) NOT NULL DEFAULT '' COMMENT '预判断快递公司代码',
  `trade_type` int(4) NOT NULL DEFAULT '0' COMMENT '订单类别{0:正常;1:分销}',
  `sell_record_id` int(11) NOT NULL DEFAULT '0' COMMENT '{sell_record_id of order_sell_record}',
  `sell_record_code` varchar(20) NOT NULL DEFAULT '' COMMENT '订单号',
  `is_refund_trade` int(4) NOT NULL DEFAULT '0' COMMENT '订单是否有退货',
  `is_fetch` int(4) DEFAULT '0' COMMENT '0：正常 1：待处理',
  `is_change` int(4) DEFAULT '0' COMMENT '0：未转单 1：转单成功 2：转单失败',
  `trade_parse` text  COMMENT '处理好的要转入的数据',
  `remark` varchar(255) DEFAULT '' COMMENT '备注',
  `tran_time` datetime DEFAULT NULL COMMENT '转入时间',
  `lastchanged` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后修改时间',
  PRIMARY KEY (`taobao_record_id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COMMENT='淘宝订单';

ALTER TABLE `api_taobao_record` ADD UNIQUE KEY `tid` (`tid`);

ALTER TABLE `api_taobao_record` ADD KEY `tid_change` (`tid`,`is_change`,`sell_record_id`);
ALTER TABLE `api_taobao_record` ADD KEY `record_id_change` (`taobao_record_id`,`is_change`);