-- ----------------------------
-- Table structure for api_weidian_trade 微店订单列表
-- ----------------------------
DROP TABLE IF EXISTS `api_weidian_trade`;
CREATE TABLE `api_weidian_trade` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `order_id` varchar(50) NOT NULL COMMENT '订单ID',
  `name` varchar(50) DEFAULT NULL COMMENT '买家姓名 收货人的姓名',
  `province` varchar(50) DEFAULT NULL COMMENT '收货人的所在省份',
  `city` varchar(50) DEFAULT NULL COMMENT '收货人的所在城市',
  `region` varchar(50) DEFAULT '0' COMMENT '收货人的所在地区',
  `address` varchar(255) DEFAULT NULL COMMENT '收货人的详细地址 带省市区',
  `self_address` varchar(255) DEFAULT NULL COMMENT '街道',
  `post` varchar(20) DEFAULT NULL COMMENT '收货人的邮编',
  `phone` varchar(20) DEFAULT NULL COMMENT '收货人的手机号码',
  `express_no` varchar(50) DEFAULT NULL COMMENT '快递单号',
  `express` varchar(50) DEFAULT NULL COMMENT '快递公司名称',
  `express_type` varchar(50) DEFAULT NULL COMMENT '快递公司编号',
  `express_note` varchar(255) DEFAULT NULL COMMENT '订单备注（卖家）',
  `express_fee` varchar(50) DEFAULT NULL COMMENT '快递费用',
  `total_fee` varchar(50) DEFAULT NULL COMMENT '分成推广佣金',
  `price` varchar(20)  DEFAULT NULL COMMENT '商品总价，不包含运费',
  `trade_no` varchar(50) NOT NULL COMMENT '订单交易编号',
  `total` varchar(20)  DEFAULT NULL COMMENT '商品总价，包含运费',
  `quantity` varchar(20) DEFAULT '0' COMMENT '商品购买数量',
  `status` varchar(50) DEFAULT NULL COMMENT '交易状态 unpay 未付款 pay 待发货 unship_refunding 未发货，申请退款ship 已发货shiped_refunding 已发货，申请退款accept 已确认收货accept_refunding已确认收货，申请退款finish 订单完成close订单关闭',
  `note` varchar(255) DEFAULT NULL COMMENT '订单备注（买家）',
  `seller_id` varchar(10)  DEFAULT NULL COMMENT '卖家ID',
  `sk` varchar(255) DEFAULT NULL COMMENT '推广信息',
  `discount` varchar(20)  DEFAULT NULL COMMENT '优惠折扣',
  `discount_amount` varchar(20)  DEFAULT NULL COMMENT '优惠金额',
  `discount_info` varchar(255)  DEFAULT NULL COMMENT '优惠折扣描述',
  `seller_phone` varchar(20)  DEFAULT NULL COMMENT '卖家手机号',
  `seller_name` varchar(50) DEFAULT NULL COMMENT '卖家微店名称',
  `is_close` varchar(10) NOT NULL COMMENT '订单是否可关闭1表示货到付款订单，可关闭， 0表示不可关闭',
  `user_phone` varchar(50) NOT NULL COMMENT '买家手机号',
  `add_time` datetime DEFAULT NULL COMMENT '下单时间',
  `pay_time` datetime DEFAULT NULL COMMENT '付款时间',
  `send_time` datetime DEFAULT NULL COMMENT '发货时间',
  `order_type` varchar(10) NOT NULL COMMENT '订单类型编号，1为货到付款，2为直接交易，3为担保交易',
  `order_type_des` varchar(255) NOT NULL COMMENT '订单类型描述',
  `return_code` varchar(10) NOT NULL COMMENT '退货单号',
  `argue_flag` varchar(10) NOT NULL COMMENT '是否投诉',
  `status_desc` varchar(10) NOT NULL COMMENT '订单状态详细描述',
  `confirm_expire` varchar(255) NOT NULL COMMENT '担保交易过期时间',
  `merchant_code` varchar(50) NOT NULL COMMENT '商品编码',
  `refund_time` varchar(50) NOT NULL COMMENT '退款时间',
  `buyer_refund_fee` varchar(50) NOT NULL COMMENT '退款金额',
  `status2` varchar(255) NOT NULL COMMENT '订单状态简单描述',
  `f_seller_id` varchar(50) NOT NULL COMMENT '分销商ID',
  `f_shop_name` varchar(255) NOT NULL COMMENT '分销商店铺名称',
  `f_phone` varchar(50) NOT NULL COMMENT '分销商手机号',
  `fx_fee_value` varchar(50) NOT NULL COMMENT '分销商获取的分成金额',
  `img` varchar(255) NOT NULL COMMENT '商品图URL',
  `modify_price_enable` varchar(10) NOT NULL COMMENT '是否可以改价 0表示不可改价，1表示可以改价',
  `express_fee_num` varchar(50) NOT NULL COMMENT '运费，和express_fee相同',
  `original_total_price` varchar(50) NOT NULL COMMENT '订单原价格，包括运费 （此字段用于记录是订单被创建时的价格， 包含运费，减去优惠后的价格）',
  `real_income_price` varchar(50) NOT NULL COMMENT '订单实际支付价格（此字段用于记录订单修改后用户实际支付的价格，包含运费）',
  `shop_code` varchar(50) DEFAULT NULL COMMENT '商店代码',
  PRIMARY KEY (`id`),
  UNIQUE KEY `order_id` (`order_id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COMMENT='微店订单列表';
