-- ----------------------------
-- Table structure for api_paipai_trade 拍拍订单列表
-- ----------------------------
DROP TABLE IF EXISTS `api_paipai_trade`;
CREATE TABLE `api_paipai_trade` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `dealCode` varchar(50) NOT NULL COMMENT '订单编码',
  `buyerName` varchar(50) DEFAULT '' COMMENT '买家名称',
  `buyerUin` varchar(20) DEFAULT '' COMMENT '买家QQ',
  `buyerRemark` varchar(100) DEFAULT '' COMMENT '买家下单时备注',
  `comboInfo` varchar(100) DEFAULT '' COMMENT '促销信息',
  `dealDesc` varchar(100) DEFAULT '' COMMENT '订单序列号，即是订单中的商品编码，多个商品时使用逗号隔开',
  `dealDetailLink` varchar(100) DEFAULT '' COMMENT '订单的详情链接',
  `dealNoteType` varchar(20) DEFAULT '' COMMENT '订单备注类型 RED:红色 YELLOW:黄色 GREEN:绿色 BLUE:蓝色 PINK:粉红色 UN_LABEL:未标注',
  `dealNote` varchar(100) DEFAULT '' COMMENT '订单的备注内容',
  `dealState` varchar(20) DEFAULT '' COMMENT '订单的状态 http://pop.paipai.com/doc/businessinfo/deal_state',
  `dealStateDesc` varchar(100) DEFAULT '' COMMENT '订单的状态说明 http://pop.paipai.com/doc/businessinfo/deal_state',
  `propertymask` varchar(100) DEFAULT '' COMMENT '订单的备注内容订单属性串：各个属性之间用下划线_隔开1=买家是QQ会员 2=诚保订单 4=有子订单退款结束的订单 8=QQ会员店 16=有商品是虚拟商品 128=卖家实收款项金额不为0 256=买家匿名购买 512=配货中状态 2048=来源为手机拍拍网 4096=团购 8192=套餐购买订单 16384=投诉中 32768=使用了店铺代金券',
  `dealType` varchar(20) DEFAULT '' COMMENT '订单类型 SELL_TYPE_ALL:所有类型SELL_TYPE_BIN:一口价 SELL_TYPE_AUCTION_SINGLE:单件拍卖 SELL_TYPE_B2C:b2c订单 SELL_TYPE_TSHOP:店铺街',
  `createTime` datetime DEFAULT NULL COMMENT '订单的创建时间',
  `dealEndTime` datetime DEFAULT NULL COMMENT '订单结束时间',
  `lastUpdateTime` datetime DEFAULT NULL COMMENT '订单的最后更新时间',
  `payTime` datetime DEFAULT NULL COMMENT '买家的付款时间',
  `payReturnTime` datetime DEFAULT NULL COMMENT '打款返回时间',
  `recvfeeReturnTime` datetime DEFAULT NULL COMMENT '退款返回时间',
  `recvfeeTime` datetime DEFAULT NULL COMMENT '退款时间',
  `sellerConsignmentTime` datetime DEFAULT NULL COMMENT '卖家发货时间',
  `hasInvoice` tinyint(1) DEFAULT 0 COMMENT '是否提供发票 1是 0否',
  `invoiceContent` varchar(50) DEFAULT '' COMMENT '发票内容',
  `invoiceTitle` varchar(50) DEFAULT '' COMMENT '发票标题',
  `tenpayCode` varchar(50) DEFAULT '' COMMENT '财付通付款单号',
  `transportType` varchar(50) DEFAULT '' COMMENT '运送类型TRANSPORT_NONE：卖家包邮，无需买家关心运送 TRANSPORT_MAIL：邮政寄送 TRANSPORT_EXPRESS：快递 TRANSPORT_EMS：EMS TRANSPORT_UNKNOWN：未知的运输方式',
  `transportTypeDesc` varchar(50) DEFAULT '' COMMENT '运费类型说明',
  `whoPayShippingfee` tinyint(1) DEFAULT 2 COMMENT '承担运费方式: 1卖家;2买家',
  `wuliuId` varchar(50) DEFAULT NULL COMMENT '物流id',
  `receiverAddress` varchar(255) DEFAULT '' COMMENT '收货人的详细地址',
  `receiverMobile` varchar(50) DEFAULT NULL COMMENT '收货人的手机',
  `receiverName` varchar(50) DEFAULT NULL COMMENT '收货人的姓名',
  `receiverPhone` varchar(50) DEFAULT NULL COMMENT '收货人的电话号码',
  `receiverPostcode` varchar(50) DEFAULT '' COMMENT '收货人的邮政编码',
  `sellerRecvRefund` varchar(20) DEFAULT '' COMMENT '退款:卖家实收金额',
  `buyerRecvRefund` varchar(20) DEFAULT '' COMMENT '退款:买家收到的退款金额',
  `couponFee` varchar(20) DEFAULT '' COMMENT '折扣优惠金额',
  `dealPayFeePoint` varchar(20) DEFAULT 0 COMMENT '实际积分支付金额',
  `dealPayFeeTicket` varchar(50) DEFAULT 0 COMMENT '财付券支付金额',
  `dealPayFeeTotal` varchar(20) DEFAULT 0 COMMENT '费用合计,一共要付的钱（包括可折合钱：积分、财付券之类）',
  `freight` varchar(20) DEFAULT '' COMMENT '支付的运费(单位:分)',
  `shippingfeeCalc` varchar(50) DEFAULT '' COMMENT '运费合计说明,列出运费最终的计算式，以便每次订单详情展示给买家看',
  `totalCash` varchar(20) DEFAULT '' COMMENT '买家支付现金总额，包括所有可折算为现金的部分',
  `sellerCrm` varchar(20) DEFAULT '' COMMENT '客服CRM',
  `sellerName` varchar(50) DEFAULT '' COMMENT '卖家名称',
  `sellerNick` varchar(20) DEFAULT '' COMMENT '卖家昵称',
  `sellerUin` varchar(20) DEFAULT '' COMMENT '卖家QQ',
  `expectArrivalTime` datetime DEFAULT NULL COMMENT '预计到货时间',
  `wuliuCompany` varchar(50) DEFAULT '' COMMENT '物流公司',
  `wuliuCode` varchar(50) DEFAULT '' COMMENT '物流单号',
  `wuliuDesc` varchar(50) DEFAULT '' COMMENT '物流备注',
  `dealPayFeeCommission` varchar(20) DEFAULT '' COMMENT '手续费字段，大于0的时候，表示卖家承担的手续费',
  `recvTime` varchar(20) DEFAULT '' COMMENT '买家收到商品的签收时间，或者拒签时间',
  `codPayList` text COMMENT '货到付款信息列表(json)',
  `shop_code` varchar(50) DEFAULT '' COMMENT '商店代码',
  PRIMARY KEY (`id`),
  UNIQUE KEY `dealCode` (`dealCode`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COMMENT='拍拍订单列表';
