DROP TABLE IF EXISTS `api_taobao_refund`;
CREATE TABLE `api_taobao_refund` (
  `shop_code` varchar(30) COMMENT '商店代码',
  `refund_id` char(20) COMMENT '退款单号',
  `tid` char(20) COMMENT '淘宝交易单号',
  `oid` char(20) COMMENT '子订单号。如果是单笔交易oid会等于tid',
  `alipay_no` varchar(30) COMMENT '支付宝交易号',
  `total_fee` float(7,2) COMMENT '交易总金额。精确到2位小数;单位:元。如:200.07，表示:200元7分',
  `buyer_nick` varchar(30) COMMENT '买家昵称',
  `seller_nick` varchar(30) COMMENT '卖家昵称',
  `created` datetime COMMENT '退款申请时间',
  `modified` datetime COMMENT '更新时间',
  `order_status` varchar(30) COMMENT '退款对应的订单交易状态。可选值 TRADE_NO_CREATE_PAY(没有创建支付宝交易) WAIT_BUYER_PAY(等待买家付款) WAIT_SELLER_SEND_GOODS(等待卖家发货,即:买家已付款) ',
  `status` varchar(30) COMMENT '退款状态。可选值 WAIT_SELLER_AGREE(买家已经申请退款，等待卖家同意) WAIT_BUYER_RETURN_GOODS(卖家已经同意退款，等待买家退货) WAIT_SELLER_CONFIRM_GOODS(买家已经退货，等待卖家确认收货) SELLER_REFUSE_BUYER(卖家拒绝退款) CLOSED(退款关闭) SUCCESS(退款成功)',
  `good_status` varchar(30) COMMENT '货物状态。可选值 BUYER_NOT_RECEIVED (买家未收到货) BUYER_RECEIVED (买家已收到货) BUYER_RETURNED_GOODS (买家已退货)',
  `has_good_return` tinyint(1) COMMENT '买家是否需要退货。可选值:true(是),false(否)',
  `refund_fee` float(7,2) COMMENT '退还金额(退还给买家的金额)。精确到2位小数;单位:元。如:200.07，表示:200元7分',
  `payment` float(7,2) COMMENT '支付给卖家的金额(交易总金额-退还给买家的金额)。精确到2位小数;单位:元。如:200.07，表示:200元7分',
  `reason` varchar(200) COMMENT '退款原因',
  `refund_desc` varchar(200) COMMENT '退款说明（注：此字段对应taobao提供api中的desc字段）',
  `title` varchar(200) COMMENT '商品标题',
  `price` float(7,2) COMMENT '商品价格。精确到2位小数;单位:元。如:200.07，表示:200元7分',
  `num` tinyint unsigned COMMENT '商品购买数量',
  `good_return_time` datetime COMMENT '退货时间',
  `company_name` varchar(20) COMMENT '物流公司名称',
  `sid` varchar(20) COMMENT '退货运单号',
  `address` varchar(100) COMMENT '卖家收货地址',
  `shipping_type` varchar(10) COMMENT '物流方式.可选值:free(卖家包邮),post(平邮),express(快递),ems(EMS)',
  `num_iid` varchar(20) COMMENT '申请退款的商品数字编号',
  `remind_type` tinyint COMMENT '提醒的类型（退款详情中提示信息的类型)（注：refund_remind_timeout中的结构）',
  `sku_properties_name` varchar(50) COMMENT '获取SKU字段中分隔符‘|’之后的内容,如"sku": "30004447689|颜色分类:军绿色;尺码:XS"',
  `outer_iid` varchar(20) COMMENT '商家外部编码(可与商家外部系统对接)。外部商家自己定义的商品Item的id，可以通过taobao.items.custom.get获取商品的Item的信息',
  `exist_timeout` tinyint(1) COMMENT '提醒的类型（退款详情中提示信息的类型)（注：refund_remind_timeout中的结构）',
  `timeout` datetime COMMENT '超时时间。格式:yyyy-MM-dd HH:mm:ss',
  `error_code` tinyint unsigned COMMENT '错误代码',
  `error_msg` varchar(200) COMMENT '错误消息',
  `updated` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, 
  PRIMARY KEY (`refund_id`),
  KEY(`shop_code`),
  KEY(`tid`),
  KEY(`oid`),
  KEY(`buyer_nick`),
  KEY(`seller_nick`),
  KEY(`created`),
  KEY(`modified`),
  KEY(`order_status`),
  KEY(`status`),
  KEY(`good_status`),
  KEY(`good_return_time`),
  KEY(`company_name`),
  KEY(`sid`),
  KEY(`num_iid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT '淘宝退单';