DROP TABLE IF EXISTS `api_taobao_goods`;
CREATE TABLE `api_taobao_goods` (
  `taobao_goods_id` int(11) NOT NULL AUTO_INCREMENT,
  `shop_code` VARCHAR(128) DEFAULT '' COMMENT '业务系统店铺代码',
  `after_sale_id` varchar(255) DEFAULT NULL COMMENT '售后服务ID,该字段仅在taobao.item.get接口中返回',
  `approve_status` varchar(255) DEFAULT NULL COMMENT '商品上传后的状态',
  `auction_point` varchar(255) DEFAULT NULL COMMENT '商品的积分返点比例。如:5,表示:返点比例0.5%',
  `auto_fill` varchar(255) DEFAULT NULL COMMENT '代充商品类型。在代充商品的类目下，不传表示不标记商品类型（交易搜索中就不能通过标记搜到相关的交易了）。可选类型： no_mark(不做类型标记) time_card(点卡软件代充) fee_card(话费软件代充)',
  `cid` varchar(255) DEFAULT NULL COMMENT '商品所属的叶子类目 id',
  `cod_postage_id` varchar(255) DEFAULT NULL COMMENT '货到付款运费模板ID',
  `created` varchar(255) DEFAULT NULL COMMENT 'Item的发布时间，目前仅供taobao.item.add和taobao.item.get可用',
  `delist_time` varchar(255) DEFAULT NULL COMMENT '下架时间（格式：yyyy-MM-dd HH:mm:ss）',
  `desc` text DEFAULT '' COMMENT '商品描述',
  `detail_url` varchar(255) DEFAULT NULL COMMENT '商品url',
  `ems_fee` varchar(255) DEFAULT NULL COMMENT 'ems费用,格式：5.00；单位：元；精确到：分',
  `express_fee` varchar(255) DEFAULT NULL COMMENT '快递费用,格式：5.00；单位：元；精确到：分',
  `freight_payer` varchar(255) DEFAULT NULL COMMENT '运费承担方式,seller（卖家承担），buyer(买家承担）',
  `barcode` varchar(255) DEFAULT NULL COMMENT '商品级别的条形码',
  `has_discount` varchar(255) DEFAULT NULL COMMENT '支持会员打折,true/false',
  `has_invoice` varchar(255) DEFAULT NULL COMMENT '是否有发票,true/false',
  `has_showcase` varchar(255) DEFAULT NULL COMMENT '橱窗推荐,true/false',
  `has_warranty` varchar(255) DEFAULT NULL COMMENT '是否有保修,true/false',
  `increment` varchar(255) DEFAULT NULL COMMENT '加价幅度。如果为0，代表系统代理幅度。 在竞拍中，为了超越上一个出价，会员需要在当前出价上增加金额，这个金额就是加价幅度。卖家在发布宝贝的时候可以自定义加价幅度，也可以让系统自动代理加价。系统自动代理加价的加价幅度随着当前出价金额的增加而增加，我们建议会员使用系统自动代理加价，并请买家在出价前看清楚加价幅度的具体金额。另外需要注意是，此功能只适用于拍卖的商品。 以下是系统自动代理加价幅度表： 当前价（加价幅度 ） 1-40（ 1 ）、41-100（ 2 ）、101-200（5 ）、201-500 （10）、501-1001（15）、001-2000（25）、2001-5000（50）、5001-10000（100） 10001以上 200',
  `input_pids` varchar(255) DEFAULT NULL COMMENT '用户自行输入的类目属性ID串。结构："pid1,pid2,pid3"，如："20000"（表示品牌） 注：通常一个类目下用户可输入的关键属性不超过1个。',
  `input_str` text DEFAULT '' COMMENT '用户自行输入的子属性名和属性值，结构:"父属性值;一级子属性名;一级子属性值;二级子属性名;自定义输入值,....",如：“耐克;耐克系列;科比系列;科比系列;2K5”，input_str需要与input_pids一一对应，注：通常一个类目下用户可输入的关键属性不超过1个。所有属性别名加起来不能超过 3999字节。',
  `is_3D` varchar(255) DEFAULT NULL COMMENT '是否是3D淘宝的商品',
  `is_ex` varchar(255) DEFAULT NULL COMMENT '是否在外部网店显示',
  `is_fenxiao` varchar(255) DEFAULT NULL COMMENT '非分销商品：0，  代销：1，  经销：2',
  `is_lightning_consignment` varchar(255) DEFAULT NULL COMMENT '是否24小时闪电发货',
  `is_prepay` varchar(255) DEFAULT NULL COMMENT '商品是否为先行赔付 taobao.items.search和taobao.items.vip.search专用',
  `is_taobao` varchar(255) DEFAULT NULL COMMENT '是否在淘宝显示',
  `is_timing` varchar(255) DEFAULT NULL COMMENT '是否定时上架商品',
  `is_virtual` varchar(255) DEFAULT NULL COMMENT '虚拟商品的状态字段',
  `is_xinpin` varchar(255) DEFAULT NULL COMMENT '标示商品是否为新品。 值含义：true-是，false-否。',
  `item_imgs` text DEFAULT '' COMMENT '商品图片列表(包括主图)。fields中只设置item_img可以返回ItemImg结构体中所有字段，如果设置为item_img.id、item_img.url、item_img.position等形式就只会返回相应的字段',
  `list_time` varchar(255) DEFAULT NULL COMMENT '上架时间（格式：yyyy-MM-dd HH:mm:ss）',
  `location` varchar(255) DEFAULT NULL COMMENT '商品所在地',
  `modified` varchar(255) DEFAULT NULL COMMENT '商品修改时间（格式：yyyy-MM-dd HH:mm:ss）',
  `nick` varchar(255) DEFAULT NULL COMMENT '卖家昵称',
  `num` varchar(255) DEFAULT NULL COMMENT '商品数量',
  `num_iid` varchar(255) DEFAULT NULL COMMENT '商品数字id',
  `one_station` varchar(255) DEFAULT NULL COMMENT '是否淘1站商品',
  `outer_id` varchar(255) DEFAULT NULL COMMENT '商家外部编码(可与商家外部系统对接)。需要授权才能获取。',
  `pic_url` varchar(255) DEFAULT NULL COMMENT '商品主图片地址',
  `post_fee` varchar(255) DEFAULT NULL COMMENT '平邮费用,格式：5.00；单位：元；精确到：分',
  `postage_id` varchar(255) DEFAULT NULL COMMENT '宝贝所属的运费模板ID，如果没有返回则说明没有使用运费模板',
  `price` varchar(255) DEFAULT NULL COMMENT '商品价格，格式：5.00；单位：元；精确到：分',
  `product_id` varchar(255) DEFAULT NULL COMMENT '宝贝所属产品的id(可能为空). 该字段可以通过taobao.products.search 得到',
  `promoted_service` varchar(255) DEFAULT NULL COMMENT '消保类型，多个类型以,分割。可取以下值： 2：假一赔三；4：7天无理由退换货；taobao.items.search和taobao.items.vip.search专用',
  `prop_imgs` varchar(255) DEFAULT NULL COMMENT '商品属性图片列表。fields中只设置prop_img可以返回PropImg结构体中所有字段，如果设置为prop_img.id、prop_img.url、prop_img.properties、prop_img.position等形式就只会返回相应的字段',
  `property_alias` varchar(255) DEFAULT NULL COMMENT '属性值别名,比如颜色的自定义名称',
  `props` varchar(255) DEFAULT NULL COMMENT '商品属性 格式：pid:vid;pid:vid',
  `props_name` varchar(255) DEFAULT NULL COMMENT '商品属性名称',
  `score` varchar(255) DEFAULT NULL COMMENT '商品所属卖家的信用等级数，1表示1心，2表示2心……，只有调用商品搜索:taobao.items.get和taobao.items.search的时候才能返回',
  `second_kill` varchar(255) DEFAULT NULL COMMENT '秒杀商品类型。打上秒杀标记的商品，用户只能下架并不能再上架，其他任何编辑或删除操作都不能进行。如果用户想取消秒杀标记，需要联系小二进行操作。如果秒杀结束需要自由编辑请联系活动负责人（小二）去掉秒杀标记。可选类型 web_only(只能通过web网络秒杀) wap_only(只能通过wap网络秒杀) web_and_wap(既能通过web秒杀也能通过wap秒杀)',
  `sell_promise` varchar(255) DEFAULT NULL COMMENT '是否承诺退换货服务!',
  `seller_cids` varchar(255) DEFAULT NULL COMMENT '商品所属的店铺内卖家自定义类目列表',
  `skus` text DEFAULT '' COMMENT 'Sku列表。fields中只设置sku可以返回Sku结构体中所有字段，如果设置为sku.sku_id、sku.properties、sku.quantity等形式就只会返回相应的字段',
  `stuff_status` varchar(255) DEFAULT NULL COMMENT '商品新旧程度(全新:new，闲置:unused，二手：second)',
  `sub_stock` varchar(255) DEFAULT NULL COMMENT '商品是否支持拍下减库存:1支持;2取消支持(付款减库存);0(默认)不更改 集市卖家默认拍下减库存; 商城卖家默认付款减库存',
  `template_id` varchar(255) DEFAULT NULL COMMENT '页面模板id',
  `title` varchar(255) DEFAULT NULL COMMENT '商品标题,不能超过60字节',
  `type` varchar(255) DEFAULT NULL COMMENT '商品类型(fixed:一口价;auction:拍卖)',
  `valid_thru` varchar(255) DEFAULT NULL COMMENT '有效期,7或者14（默认是7天）',
  `videos` varchar(255) DEFAULT NULL COMMENT '商品视频列表(目前只支持单个视频关联)。fields中只设置video可以返回Video结构体中所有字段，如果设置为video.id、video.video_id、 video.url等形式就只会返回相应的字段',
  `violation` varchar(255) DEFAULT NULL COMMENT '商品是否违规，违规：true , 不违规：false',
  `wap_desc` varchar(255) DEFAULT NULL COMMENT '不带html标签的desc文本信息，该字段只在taobao.item.get接口中返回',
  `wap_detail_url` varchar(255) DEFAULT NULL COMMENT '适合wap应用的商品详情url ，该字段只在taobao.item.get接口中返回',
  `ww_status` varchar(255) DEFAULT NULL COMMENT '商品所属的商家的旺旺在线状况， taobao.items.search和taobao.items.vip.search专用',
  `item_weight` varchar(255) DEFAULT NULL COMMENT '商品的重量，用于按重量计费的运费模板。注意：单位为kg',
  `first_insert_time` datetime DEFAULT NULL COMMENT '平台第一次数据下载时间',
  `last_update_time` datetime DEFAULT NULL COMMENT '平台最后一次更新时间',
  `lastchanged` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '数据变更时间戳',
  `is_relation` tinyint(2) NOT NULL DEFAULT '0' COMMENT '商品是否绑定',
  `relation_msg` VARCHAR(255) NOT NULL COMMENT '关联备注',
  `cat` varchar(255) DEFAULT NULL COMMENT '分类',
  `brand` varchar(255) DEFAULT NULL COMMENT '品牌',
  PRIMARY KEY (`taobao_goods_id`),
  UNIQUE KEY `shop_num_iid` (`shop_code`,`num_iid`),
  KEY `num_iid` (`num_iid`),
  KEY `is_relation` (`is_relation`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='淘宝商品原始数据表';