DROP TABLE IF EXISTS `api_zouxiu_trade`;
CREATE TABLE `api_zouxiu_trade` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `shop_code` varchar(200) NOT NULL COMMENT '店铺code',
  `orderId` varchar(32) NOT NULL DEFAULT '0' COMMENT '走秀官网订单号',
  `packageId` varchar(32) NOT NULL DEFAULT '0' COMMENT '走秀包裹ID(EBS生成的包裹号)',
  `packageNumber` varchar(32) DEFAULT '' COMMENT '走秀包裹号',
  `deliveryNo` varchar(32) DEFAULT '' COMMENT '运单号',
  `deliveryName` varchar(32) DEFAULT '' COMMENT '快递公司名称',
  `shippingTime` varchar(64) DEFAULT '' COMMENT '配送时间',
  `shippingRemark` varchar(250) DEFAULT '' COMMENT '配送备注',
  `status` int(1) DEFAULT '1' COMMENT '订单状态(0:待备货,1:待发货,2:已发货,3:拒收订单,4:退货订单,5:超期未发货订单)',
  `createTime` varchar(32) DEFAULT '' COMMENT '创建时间 yyyy-MM-dd HH:mm:ss',
  `totalFee` decimal(15,2) DEFAULT '0.00' COMMENT '包裹金额(商品单价*数量)，单位元',
  `payMethod` int(1) DEFAULT '0' COMMENT '是否货到付款0:非COD 1:COD',
  `codFee` decimal(15,2) DEFAULT '0.00' COMMENT '包裹金额(COD金额，单位元)',
  `postFee` decimal(15,2) DEFAULT '0.00' COMMENT '运费',
  `logisticsStatus` varchar(64) DEFAULT '' COMMENT '发货状态',
  `shipOrderUrl` varchar(300) DEFAULT '' COMMENT '发货单图片url',
  `eWaybillUrl` varchar(300) DEFAULT '' COMMENT '运单图片url',
  `receiverName` varchar(30) DEFAULT '' COMMENT '收货人姓名',
  `receiverState` varchar(64) DEFAULT '' COMMENT '收货人所在省份',
  `receiverCity` varchar(64) DEFAULT '' COMMENT '收货人所在城市',
  `receiverDistrict` varchar(255) DEFAULT '' COMMENT '收货人所在区县',
  `receiverAddress` varchar(255) DEFAULT '' COMMENT '收货人详细地址',
  `receiverZip` varchar(20) DEFAULT '' COMMENT '收货人邮编',
  `receiverMobile` varchar(20) DEFAULT '' COMMENT '收货人手机号码',
  `receiverPhone` varchar(20) DEFAULT '' COMMENT '收货人固定电话',
  `buyerRemark` varchar(255) DEFAULT '' COMMENT '买家备注',
  `isInvoice` varchar(2) DEFAULT '0' COMMENT '是否需要发票0:否 1:是',
  `invoiceName` varchar(255) DEFAULT '' COMMENT '发票抬头',
  `invoiceContent` varchar(255) DEFAULT '' COMMENT '发票内容',
  PRIMARY KEY (`id`),
  UNIQUE KEY `INDEX_TRADEID` (`packageId`),
  KEY `shop_code` (`shop_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;