DROP TABLE IF EXISTS `api_taobao_trade`;
CREATE TABLE `api_taobao_trade` (
  `ttid` int(11) unsigned AUTO_INCREMENT,
  `shop_code` varchar(50) DEFAULT '' COMMENT '店铺nick',
  `end_time` datetime COMMENT '交易结束时间。交易成功时间(更新交易状态为成功的同时更新)/确认收货时间或者交易关闭时间',
  `buyer_message` varchar(200) COMMENT '买家留言',
  `shipping_type` varchar(10) COMMENT '创建交易时的物流方式（交易完成前，物流方式有可能改变，但系统里的这个字段一直不变）。可选值：free(卖家包邮),post(平邮),express(快递),ems(EMS),virtual(虚拟发货)，25(次日必达)，26(预约配送)',
  `buyer_cod_fee` float(7,2) COMMENT '买家货到付款服务费',
  `seller_cod_fee` float(7,2) COMMENT '卖家货到付款服务费',
  `express_agency_fee` float(7,2) COMMENT '快递代收款',
  `alipay_warn_msg` float(7,2) COMMENT '淘宝下单成功了,但由于某种错误支付宝订单没有创建时返回的信息。taobao.trade.add接口专用',
  `status` varchar(30) COMMENT '交易状态。可选值: TRADE_NO_CREATE_PAY(没有创建支付宝交易)  WAIT_BUYER_PAY(等待买家付款) SELLER_CONSIGNED_PART(卖家部分发货) WAIT_SELLER_SEND_GOODS(等待卖家发货,即:买家已付款) WAIT_BUYER_CONFIRM_GOODS(等待买家确认收货,即:卖家已发货) TRADE_BUYER_SIGNED(买家已签收,货到付款专用) TRADE_FINISHED(交易成功) TRADE_CLOSED(付款以后用户退款成功，交易自动关闭) TRADE_CLOSED_BY_TAOBAO(付款以前，卖家或买家主动关闭交易) PAY_PENDING(国际信用卡支付付款确认中) WAIT_PRE_AUTH_CONFIRM(0元购合约中)',
  `buyer_memo` varchar(200) COMMENT '买家备注（与淘宝网上订单的买家备注对应，只有买家才能查看该字段）',
  `seller_memo` varchar(200) COMMENT '卖家备注（与淘宝网上订单的卖家备注对应，只有卖家才能查看该字段）',
  `modified` datetime COMMENT '交易修改时间(用户对订单的任何修改都会更新此字段)',
  `buyer_flag` tinyint(1) COMMENT '买家备注旗帜（与淘宝网上订单的买家备注旗帜对应，只有买家才能查看该字段） 红、黄、绿、蓝、紫 分别对应 1、2、3、4、5',
  `seller_flag` tinyint(1) COMMENT '卖家备注旗帜（与淘宝网上订单的卖家备注旗帜对应，只有卖家才能查看该字段） 红、黄、绿、蓝、紫 分别对应 1、2、3、4、5',
  `trade_from` varchar(20) COMMENT '交易内部来源WAP(手机);HITAO(嗨淘);TOP(TOP平台);TAOBAO(普通淘宝);JHS(聚划算) 一笔订单可能同时有以上多个标记，则以逗号分隔',
  `seller_nick` varchar(30) DEFAULT '' COMMENT '卖家昵称',
  `buyer_nick` varchar(30) DEFAULT '' COMMENT '买家昵称',
  `title` varchar(200) COMMENT '交易标题，以店铺名作为此标题的值。注:taobao.trades.get接口返回的Trade中的title是商品名称',
  `type` varchar(30) COMMENT '交易类型列表，同时查询多种交易类型可用逗号分隔',
  `created` datetime COMMENT '交易创建时间',
  `iid` datetime COMMENT '商品字符串编号(注意：iid近期即将废弃，请用num_iid参数)',
  `price` float(7,2) COMMENT '商品价格',
  `pic_path` varchar(50) COMMENT '商品图片的绝对路径,http开头',
  `num` tinyint COMMENT '商品购买数量。取值范围：大于零的整数,对于一个trade对应多个order的时候（一笔主订单，对应多笔子订单），num=0，num是一个跟商品关联的属性，一笔订单对应多比子订单的时候，主订单上的num无意义',
  `tid` varchar(30) DEFAULT '' COMMENT '父订单的交易编号',
  `alipay_no` varchar(30) DEFAULT '' COMMENT '支付宝交易号',
  `payment` float(7,2) COMMENT '实付金额',
  `discount_fee` float(7,2) COMMENT '建议使用trade.promotion_details查询系统优惠 系统优惠金额（如打折，VIP，满就送等）',
  `adjust_fee` float(7,2) COMMENT '卖家手工调整金额，精确到2位小数，单位：元。如：200.07，表示：200元7分。来源于订单价格修改，如果有多笔子订单的时候，这个为0，单笔的话则跟[order].adjust_fee一样',
  `snapshot_url` varchar(40) COMMENT '交易快照地址',
  `snapshot` varchar(40) COMMENT '交易快照详细信息',
  `seller_rate` tinyint(1) COMMENT '卖家是否已评价。可选值:true(已评价),false(未评价)',
  `buyer_rate` tinyint(1) COMMENT '买家是否已评价。可选值:true(已评价),false(未评价)。如买家只评价未打分，此字段仍返回false',
  `trade_memo` varchar(100) COMMENT '交易备注',
  `pay_time` datetime COMMENT '订单的付款时间即为物流订单的创建时间',
  `buyer_obtain_point_fee` smallint unsigned COMMENT '买家获得积分,返点的积分。格式:100;单位:个。返点的积分要交易成功之后才能获得',
  `point_fee` smallint unsigned COMMENT '买家使用积分,下单时生成，且一直不变。格式:100;单位:个',
  `real_point_fee` smallint unsigned COMMENT '买家实际使用积分（扣除部分退款使用的积分），交易完成后生成（交易成功或关闭），交易未完成时该字段值为0。格式:100;单位:个',
  `total_fee` float(7,2) COMMENT '商品金额（商品价格乘以数量的总金额）',
  `post_fee` float(7,2) COMMENT '邮费,精确到2位小数;单位:元。如:200.07，表示:200元7分',
  `buyer_alipay_no` varchar(30) COMMENT '买家支付宝账号',
  `receiver_name` varchar(30) COMMENT '收货人的姓名',
  `receiver_state` varchar(20) COMMENT '收货人的所在省份',
  `receiver_city` varchar(20) COMMENT '收货人的所在城市',
  `receiver_district` varchar(20) COMMENT '收货人的所在地区',
  `receiver_address` varchar(200) COMMENT '收货人的详细地址',
  `receiver_zip` varchar(6) COMMENT '收货人的邮编',
  `receiver_mobile` char(11) COMMENT '收货人的手机号码',
  `receiver_phone` varchar(12) COMMENT '收货人的电话号码',
  `consign_time` datetime COMMENT '卖家发货时间',
  `buyer_email` varchar(20) COMMENT '买家邮件地址',
  `commission_fee` float(7,2) COMMENT '交易佣金',
  `seller_alipay_no` varchar(30) COMMENT '卖家支付宝账号',
  `seller_mobile` char(11) COMMENT '卖家手机',
  `seller_phone` varchar(12) COMMENT '卖家电话',
  `seller_name` varchar(30) COMMENT '卖家姓名',
  `seller_email` varchar(20) COMMENT '卖家邮件地址',
  `available_confirm_fee` float(7,2) COMMENT '交易中剩余的确认收货金额（这个金额会随着子订单确认收货而不断减少，交易成功后会变为零）',
  `has_post_fee` tinyint(1) COMMENT '是否包含邮费。与available_confirm_fee同时使用。可选值:true(包含),false(不包含)',
  `received_payment` float(7,2) COMMENT '卖家实际收到的支付宝打款金额（由于子订单可以部分确认收货，这个金额会随着子订单的确认收货而不断增加，交易成功后等于买家实付款减去退款金额）',
  `cod_fee` float(5,2) COMMENT '货到付款服务费',
  `cod_status` varchar(10) COMMENT '货到付款物流状态',
  `timeout_action_time` datetime COMMENT '超时到期时间',
  `is_3D` tinyint(1) COMMENT '是否是3D淘宝交易',
  `num_iid` varchar(20) COMMENT '商品数字编号',
  `promotion_details` varchar(200) COMMENT '优惠详情',
  `invoice_name` varchar(60) COMMENT '发票抬头',
  `alipay_url` varchar(60) COMMENT '创建交易接口成功后，返回的支付url',
  `error_code` varchar(10) COMMENT '错误代码',
  `error_msg` varchar(100) COMMENT '错误消息',
  `is_lgtype` tinyint(1) COMMENT '是否保障速递，如果为true，则为保障速递订单，使用线下联系发货接口发货，如果未false，则该订单非保障速递，根据卖家设置的订单流转规则可使用物流宝或者常规物流发货',
  `is_force_wlb` tinyint(1) COMMENT '订单是否强制使用物流宝发货。当此字段与is_brand_sale均为true时，订单强制物流宝发货。此字段为false时，该订单根据流转规则设置可以使用物流宝或者常规方式发货',
  `is_brand_sale` tinyint(1) COMMENT '表示是否是品牌特卖（常规特卖，不包括特卖惠和特实惠）订单，如果是返回true，如果不是返回false。当此字段与is_force_wlb均为true时，订单强制物流宝发货',
  `mark_desc` varchar(200) DEFAULT '' COMMENT '订单出现异常问题的时候，给予用户的描述,没有异常的时候，此值为空',
  PRIMARY KEY (`ttid`),
  unique KEY(`tid`),
  KEY(`shop_code`),
  KEY(`alipay_no`),
  KEY(`seller_nick`),
  KEY(`buyer_nick`),
  KEY `shop_code_modified` (`shop_code`,`modified`),
  KEY `modified` (`modified`),
  KEY `shop_code_created` (`shop_code`,`created`),
  KEY `created` (`created`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT '淘宝订单';