-- ----------------------------
-- Table structure for api_yihaodian_trade 一号店订单主表
-- ----------------------------
DROP TABLE IF EXISTS `api_yihaodian_trade`;
CREATE TABLE `api_yihaodian_trade` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `orderId` varchar(30) DEFAULT '' COMMENT '订单ID',
  `orderCode` varchar(30) DEFAULT '' COMMENT '订单编码',
  `orderStatus` varchar(40) DEFAULT '' COMMENT '订单状态（英文）ORDER_WAIT_PAY：已下单（货款未全收）, ORDER_PAYED：已下单（货款已收）, ORDER_TRUNED_TO_DO：可以发货（已送仓库）, ORDER_OUT_OF_WH：已出库（货在途）, ORDER_RECEIVED：货物用户已收到, ORDER_FINISH：订单完成, ORDER_CANCEL：订单取消',
  `orderAmount` varchar(30) DEFAULT '' COMMENT '订购金额=商品金额+运费-满立减金额，即为顾客应付款',
  `productAmount` varchar(30) DEFAULT '' COMMENT '产品总额',
  `orderCreateTime` varchar(30) DEFAULT '' COMMENT '订单创建日期',
  `orderDeliveryFee` varchar(30) DEFAULT '' COMMENT '运费',
  `orderNeedInvoice` varchar(30) DEFAULT '' COMMENT '发票需要情况:0不需要，1旧版普通，2新版普通，3增值税发票',
  `goodReceiverName` varchar(30) DEFAULT '' COMMENT '收货人姓名',
  `goodReceiverAddress` varchar(30) DEFAULT '' COMMENT '收货人地址',
  `goodReceiverProvince` varchar(30) DEFAULT '' COMMENT '收货人省份',
  `goodReceiverCity` varchar(255) DEFAULT '' COMMENT '收货人城市',
  `goodReceiverCounty` varchar(30) DEFAULT '' COMMENT '收货人地区',
  `goodReceiverPostCode` varchar(30) DEFAULT '' COMMENT '收货人邮编',
  `goodReceiverPhone` varchar(30) DEFAULT '' COMMENT '收货人电话',
  `goodReceiverMoblie` varchar(30) DEFAULT '' COMMENT '收货人手机号',
  `deliveryDate` varchar(30) DEFAULT '' COMMENT '发货时间',
  `receiveDate` varchar(30) DEFAULT '' COMMENT '确认收货时间',
  `deliveryRemark` varchar(255) DEFAULT '' COMMENT '买家留言',
  `deliverySupplierId` varchar(30) DEFAULT '' COMMENT '配送商ID',
  `merchantRemark` varchar(255) DEFAULT '' COMMENT '卖家备注',
  `orderPaymentConfirmDate` varchar(30) DEFAULT '' COMMENT '付款确认时间(实际付款时间)',
  `payServiceType` varchar(255) DEFAULT '' COMMENT '订单支付方式0:账户支付1:网上支付2:货到付款3:邮局汇款4:银行转账5:pos机6:万里通7:分期付款8:合同账期9:货到转账10:货到付支票 12:货到刷支付宝',
  `orderPromotionDiscount` varchar(30) DEFAULT '' COMMENT '参加促销活动立减金额',
  `merchantExpressNbr` varchar(30) DEFAULT '' COMMENT '配送商送货编号(运单号)',
  `updateTime` varchar(30) DEFAULT '' COMMENT '更新时间',
  `orderCouponDiscount` varchar(255) DEFAULT '' COMMENT '商家抵用券支付金额',
  `orderPlatformDiscount` varchar(30) DEFAULT '' COMMENT '1mall平台抵用券支付金额',
  `invoiceTitle` varchar(30) DEFAULT '' COMMENT '发票抬头',
  `invoiceContent` varchar(255) DEFAULT '' COMMENT '发票内容',
  `endUserId` varchar(30) DEFAULT '' COMMENT '用户ID',
  `realAmount` varchar(30) DEFAULT '' COMMENT '实收款==产品金额-促销活动立减金额 -商家抵用券金额+运费',
  `warehouseId` varchar(30) DEFAULT '' COMMENT '仓库ID',
  `isMobileOrder` varchar(255) DEFAULT '' COMMENT '是否无线端订单(0:PC端订单;1:无线端订单)',
  `businessType` varchar(30) DEFAULT '' COMMENT '订单类型：0:前台普通订单1:团购订单 2:EPP订单 3:处方药订单 4:B2B订单 5:店中店代售 6:平安3g标志 10:定期购订单 11:预售订单 12:闪购 13:合约机 14:手机充值 15:选号入网 16:二手品 17:1闪团订单 18:生活团订单 19:定金预售 20:社区团订单 21:微店订单 22:OMO订单 23:跨境通海购订单 24:快拍订单 25:手机流量充值订单 26:支付宝渠道订单 27:门店订单',
  `orderDeposit` varchar(255) DEFAULT '' COMMENT '订单订金',
  `isDepositOrder` varchar(30) DEFAULT '' COMMENT '是否为预售订单',
  `depositPaidTime` varchar(255) DEFAULT '' COMMENT '订金支付时间',
  `applyCancel` varchar(30) DEFAULT '' COMMENT '是否为申请取消订单:1是, 0否',
  `storeId` varchar(30) DEFAULT '' COMMENT '门店ID',
  `storeName` varchar(30) DEFAULT '' COMMENT '门店名称',
  `externalStoreId` varchar(30) DEFAULT '' COMMENT '沃尔玛外部门店ID',
  `collectOnDeliveryAmount` varchar(30) DEFAULT '' COMMENT '货到应收金额(订单支付方式为2、5、12时候有值)',
  `shop_code` varchar(255) DEFAULT '' COMMENT 'efast商店代码',
  PRIMARY KEY (`id`),
  UNIQUE KEY `orderCode` (`orderCode`) USING BTREE,
  KEY `shop_code` (`shop_code`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 ROW_FORMAT=COMPACT;