-- ----------------------------
-- Table structure for api_dangdang_goods
-- ----------------------------
DROP TABLE IF EXISTS `api_dangdang_goods`;
CREATE TABLE `api_dangdang_goods` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `itemID` varchar(50) DEFAULT NULL COMMENT '商品标识符',
  `outerItemID` varchar(50) DEFAULT NULL COMMENT '商家自定义的商品标识符(如果商品没有“企业商品标志符”，则不返回此项)',
  `itemBarcode` varchar(50) DEFAULT NULL COMMENT '条形码',
  `itemName` varchar(255) DEFAULT NULL COMMENT '商品名称',
  `itemSubhead` varchar(100) DEFAULT NULL COMMENT '商品副标题',
  `classificationCode1` varchar(10) DEFAULT NULL COMMENT '分类代码1',
  `classificationCode2` varchar(10) DEFAULT NULL COMMENT '分类代码2',
  `brand` varchar(20) DEFAULT NULL COMMENT '品牌',
  `model` varchar(20) DEFAULT NULL COMMENT '商品所属型号',
  `attribute` varchar(30) DEFAULT NULL COMMENT '属性',
  `itemDetail` text DEFAULT NULL COMMENT '商品描述',
  `stockPrice` varchar(20) DEFAULT NULL COMMENT '进货价',
  `marketPrice` varchar(20) DEFAULT NULL COMMENT '市场价',
  `unitPrice` varchar(50) DEFAULT NULL COMMENT '单价',
  `stockCount` varchar(50) DEFAULT NULL COMMENT 'stockCount',
  `isShopVip` varchar(50) DEFAULT NULL COMMENT '是否设置店铺VIP价',
  `shopCategoryID1` varchar(50) DEFAULT NULL COMMENT '店内分类编号1',
  `shopCategoryID2` varchar(50) DEFAULT NULL COMMENT '店内分类编号2',
  `shopCategoryID3` varchar(50) DEFAULT NULL COMMENT '店内分类编号3',
  `shopCategoryID4` varchar(50) DEFAULT NULL COMMENT '店内分类编号4',
  `shopCategoryID5` varchar(50) DEFAULT NULL COMMENT '店内分类编号5',
  `shopCategoryID6` varchar(50) DEFAULT NULL COMMENT '店内分类编号6',
  `shopCategoryID7` varchar(50) DEFAULT NULL COMMENT '店内分类编号7',
  `shopCategoryID8` varchar(50) DEFAULT NULL COMMENT '店内分类编号8',
  `shopCategoryID9` varchar(50) DEFAULT NULL COMMENT '店内分类编号9',
  `shopCategoryID10` varchar(50) DEFAULT NULL COMMENT '店内分类编号10',
  `itemState` varchar(50) DEFAULT NULL COMMENT '商品状态(“上架”或“下架”)',
  `is_cod` varchar(50) DEFAULT NULL COMMENT '是否支持COD',
  `itemType` varchar(20) DEFAULT NULL COMMENT '商品类型(“商品”，“赠品”)',
  `volume` varchar(20) DEFAULT NULL COMMENT '商品体积',
  `weight` varchar(20) DEFAULT NULL COMMENT '商品重量',
  `templateName` varchar(255) DEFAULT NULL COMMENT '运费模板',
  `bestPartnerList` varchar(255) DEFAULT NULL COMMENT '最佳拍档',
  `pic1` varchar(255) DEFAULT NULL COMMENT '商品的主图第1张图片的链接地址(若无图，不返回此节点)',
  `pic2` varchar(255) DEFAULT NULL COMMENT '商品的主图第2张图片的链接地址(若无图，不返回此节点)',
  `pic3` varchar(255) DEFAULT NULL COMMENT '商品的主图第3张图片的链接地址(若无图，不返回此节点)',
  `pic4` varchar(255) DEFAULT NULL COMMENT '商品的主图第4张图片的链接地址(若无图，不返回此节点)',
  `pic5` varchar(255) DEFAULT NULL COMMENT '商品的主图第5张图片的链接地址(若无图，不返回此节点)',
  `pic6` varchar(255) DEFAULT NULL COMMENT '商品的主图第6张图片的链接地址(若无图，不返回此节点)',
  `pic7` varchar(255) DEFAULT NULL COMMENT '商品的主图第7张图片的链接地址(若无图，不返回此节点)',
  `pic8` varchar(255) DEFAULT NULL COMMENT '商品的主图第8张图片的链接地址(若无图，不返回此节点)',
  `shop_code` varchar(30) NOT NULL COMMENT 'efast商店代码',
  `first_insert_time` datetime DEFAULT NULL COMMENT '平台第一次数据下载时间',
  `last_update_time` datetime DEFAULT NULL COMMENT '平台最后一次更新时间',
  `lastchanged` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '数据变更时间戳',
  PRIMARY KEY (`id`),
  UNIQUE KEY `itemID_sd` (`itemID`,`shop_code`),
  KEY `itemID` (`itemID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

