DROP TABLE IF EXISTS `api_zhe800_trade`;
CREATE TABLE `api_zhe800_trade` (
  `trade_id` int(11) NOT NULL AUTO_INCREMENT,
  `id` varchar(30) NOT NULL DEFAULT '0' COMMENT '订单编号(兼容折800的字段）',
  `from_source` tinyint(1) NOT NULL DEFAULT '1' COMMENT '订单来源 1-PC(默认)2-无线',
  `url` varchar(100) NOT NULL DEFAULT '' COMMENT '订单-链接',
  `seller_id` int(11) NOT NULL DEFAULT '0' COMMENT '卖家ID',
  `seller_nickname` varchar(30) NOT NULL DEFAULT '' COMMENT '卖家昵称（商家眤称）',
  `order_price` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '总金额',
  `goods_price` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '商品总金额',
  `discount_price` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '商家优惠金额',
  `postage` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '邮费(订单运费)',
  `oos` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否超卖 0-正常 1-超卖',
  `status` tinyint(1) NOT NULL DEFAULT '0' COMMENT '订单-状态 1-待付款 2-等待发货 3-已发货(待确认收货) 5-交易成功 7-交易关闭, 99-等待第三方支付平台返回支付结果',
  `deliver_time_limit` tinyint(1) NOT NULL DEFAULT '1' COMMENT '订单-发货时长(1天, 2天, 3天)',
  `seller_comment` varchar(255) NOT NULL DEFAULT '' COMMENT '卖家备注(商家备注)',
  `buyer_comment` varchar(255) NOT NULL DEFAULT '' COMMENT '买家留言(买家备注)',
  `created_at` datetime NOT NULL COMMENT '拍下时间(下单时间)',
  `close_time` datetime DEFAULT NULL COMMENT '订单关闭时间（原因：买家取消订单/超过未⽀支付/因为售后完成）',
  `updated_at` datetime NOT NULL COMMENT '订单更新时间',
  `express_time` datetime NOT NULL COMMENT '发货时间 PENDING',
  `close_reason` varchar(255) NOT NULL COMMENT '关闭原因',
  `pay_time` datetime NOT NULL COMMENT '付款时间',
  `express_no` varchar(30) DEFAULT '' COMMENT '运单号',
  `express_company` varchar(100) NOT NULL DEFAULT '' COMMENT '快递公司',
  `nickname` varchar(100) NOT NULL DEFAULT '',
  `seller_comment_type` tinyint(1) NOT NULL DEFAULT '0' COMMENT '卖家备注类型 0 无备注； 1-红色，2-黄色，3-绿色，4-蓝色，5-紫色',
  `invoice_type` varchar(30) NOT NULL DEFAULT '' COMMENT '发票信息-发票类型',
  `invoice_content` varchar(100) NOT NULL DEFAULT '' COMMENT '发票信息-发票内容',
  `invoice_title` varchar(100) NOT NULL DEFAULT '' COMMENT '发票信息-发票抬头',
  `receiver_name` varchar(30) NOT NULL DEFAULT '' COMMENT '收货人-姓名',
  `receiver_province` varchar(30) NOT NULL DEFAULT '' COMMENT '收货人-地区-省',
  `receiver_city` varchar(30) NOT NULL DEFAULT '' COMMENT '收货人-地区-市',
  `receiver_county` varchar(30) NOT NULL DEFAULT '' COMMENT '收货人-地区-区县',
  `receiver_address` varchar(50) NOT NULL DEFAULT '' COMMENT '收货人-地址(无省市区)',
  `receiver_phone` varchar(30) NOT NULL DEFAULT '' COMMENT '收货人-手机',
  `receiver_tel` varchar(30) NOT NULL DEFAULT '' COMMENT '收货人-电话',
  `receiver_postCode` varchar(20) NOT NULL DEFAULT '' COMMENT '收货人-邮编',
  PRIMARY KEY (`trade_id`),
  UNIQUE KEY `id` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
