DROP TABLE IF EXISTS `api_refund`;
CREATE TABLE `api_refund` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `refund_id` varchar(30) DEFAULT NULL COMMENT '退款单号',
  `refund_type` varchar(10) DEFAULT NULL COMMENT '退款类型',
  `tid` varchar(30) DEFAULT NULL COMMENT '交易号',
  `oid` varchar(30) DEFAULT NULL COMMENT '子订单号。如果是单笔交易oid会等于tid',
  `refund_record_code` varchar(30) NOT NULL DEFAULT '' COMMENT '业务系统单据编号(售后服务单号)',
  `source` varchar(10) DEFAULT NULL COMMENT '平台来源标识符',
  `shop_code` varchar(30) DEFAULT NULL COMMENT '业务系统店铺代码',
  `status` tinyint(1) DEFAULT NULL COMMENT '0：不可转单 1：可转单',
  `is_change` tinyint(1) NOT NULL DEFAULT '0' COMMENT '0：未转单 1：已转单',
  `seller_nick` varchar(30) DEFAULT NULL COMMENT '平台卖家昵称',
  `buyer_nick` varchar(30) DEFAULT NULL COMMENT '平台买家昵称',
  `has_good_return` tinyint(1) DEFAULT NULL COMMENT '买家是否需要退货。可选值:true(是),false(否)',
  `refund_fee` float(7,2) DEFAULT NULL COMMENT '退还金额(退还给买家的金额)',
  `payment` float(7,2) DEFAULT NULL COMMENT '支付给卖家的金额(交易总金额-退还给买家的金额)。精确到2位小数',
  `refund_reason` varchar(100) DEFAULT NULL COMMENT '退款原因',
  `refund_desc` varchar(200) DEFAULT NULL COMMENT '退款说明（注：此字段对应taobao提供api中的desc字段）',
  `refund_express_code` varchar(20) DEFAULT NULL COMMENT '物流公司代码',
  `refund_express_no` varchar(20) DEFAULT NULL COMMENT '退货运单号',
  `attribute` varchar(20) DEFAULT NULL COMMENT '退款扩展属性',
  `change_remark` text COMMENT '转单日志',
  `order_last_update_time` datetime DEFAULT NULL COMMENT '平台订单最后一次更新订单时间,淘宝平台：modified',
  `order_first_insert_time` datetime DEFAULT NULL COMMENT '平台订单第一次插入订单时间,淘宝平台：created',
  `last_update_time` datetime DEFAULT NULL COMMENT '最后一次更新订单时间,数据在本平台的更新时间',
  `first_insert_time` datetime DEFAULT NULL COMMENT '第一次插入订单时间,数据在本平台的插入时间',
  `lastchanged` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `refund_id` (`refund_id`) USING BTREE,
  KEY `refund_type` (`refund_type`) USING BTREE,
  KEY `tid` (`tid`) USING BTREE,
  KEY `oid` (`oid`) USING BTREE,
  KEY `refund_record_code` (`refund_record_code`) USING BTREE,
  KEY `source` (`source`) USING BTREE,
  KEY `shop_code` (`shop_code`) USING BTREE,
  KEY `buyer_nick` (`buyer_nick`) USING BTREE,
  KEY `seller_nick` (`seller_nick`) USING BTREE,
  KEY `refund_express_code` (`refund_express_code`) USING BTREE,
  KEY `refund_express_no` (`refund_express_no`) USING BTREE,
  KEY `index1` (`status`,`is_change`) USING BTREE,
  KEY `order_first_insert_time` (`order_first_insert_time`) USING BTREE,
  KEY `is_change` (`is_change`) USING BTREE,
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='退单';