-- ----------------------------
-- Table structure for api_yz_order 有赞订单列表
-- ----------------------------
DROP TABLE IF EXISTS `api_yz_trade`;
CREATE TABLE `api_yz_trade` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '有赞订单列表',
  `tid` varchar(50) NOT NULL COMMENT '交易编号',
  `num` int(10) DEFAULT '0' COMMENT '商品购买数量。当一个trade对应多个order的时候，值为所有商品购买数量之和',
  `num_iid` int(10) DEFAULT '0' COMMENT '商品数字编号。当一个trade对应多个order的时候，值为第一个子订单商品的编号',
  `price` varchar(20) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '商品价格。精确到2位小数；单位：元。当一个trade对应多个order的时候，值为第一个子订单商品的价格',
  `pic_path` varchar(255) DEFAULT NULL COMMENT '商品主图片缩略图地址',
  `pic_thumb_path` varchar(255) NOT NULL COMMENT '商品主图片缩略图地址',
  `title` varchar(50) NOT NULL COMMENT '交易标题，以首个商品标题作为此标题的值',
  `weixin_user_id` int(10) DEFAULT NULL COMMENT '微信粉丝ID',
  `buyer_nick` varchar(50) DEFAULT NULL COMMENT '买家昵称',
  `buyer_message` varchar(255) DEFAULT NULL COMMENT '买家购买附言',
  `seller_flag` int(10) unsigned zerofill DEFAULT NULL COMMENT '卖家备注星标，取值范围 1、2、3、4、5',
  `trade_memo` varchar(255) DEFAULT NULL COMMENT '卖家对该交易的备注',
  `receiver_city` varchar(50) DEFAULT NULL COMMENT '收货人的所在城市',
  `receiver_district` varchar(50) DEFAULT '0' COMMENT '收货人的所在地区',
  `receiver_name` varchar(50) DEFAULT NULL COMMENT '收货人的姓名',
  `receiver_state` varchar(50) DEFAULT NULL COMMENT '收货人的所在省份',
  `receiver_address` varchar(255) DEFAULT NULL COMMENT '收货人的详细地址',
  `receiver_zip` varchar(20) DEFAULT NULL COMMENT '收货人的邮编',
  `receiver_mobile` varchar(20) DEFAULT NULL COMMENT '收货人的手机号码',
  `feedback` tinyint(1) DEFAULT NULL COMMENT '订单维权状态。0 无维权，1 顾客发起维权，9 商家正在处理，2 顾客拒绝商家的处理结果，3 顾客接受商家的处理结果',
  `outer_tid` varchar(50) DEFAULT NULL COMMENT '外部交易编号',
  `status` varchar(50) DEFAULT NULL COMMENT '交易状态',
  `shipping_type` varchar(50) DEFAULT NULL COMMENT '创建交易时的物流方式。可选值：express(快递)',
  `is_tran_success` tinyint(1) DEFAULT '0' COMMENT '是否转单成功0:未转单;1:已转单',
  `error_code` int(11) DEFAULT '0' COMMENT '错误信息code',
  `error_msg` varchar(255) DEFAULT NULL,
  `efast_order_sn` varchar(20) DEFAULT NULL COMMENT 'efast交易号',
  `post_fee` varchar(50) DEFAULT NULL COMMENT '运费。单位：元，精确到分',
  `total_fee` varchar(50) DEFAULT NULL COMMENT '商品总价（商品价格乘以数量的总金额）。单位：元，精确到分',
  `discount_fee` varchar(50) DEFAULT NULL COMMENT '系统优惠金额（目前都是 0）。单位：元，精确到分',
  `payment` varchar(20) DEFAULT NULL COMMENT '实付金额',
  `created` datetime DEFAULT NULL COMMENT '交易创建时间',
  `pay_time` datetime DEFAULT NULL COMMENT '买家付款时间',
  `pay_type` varchar(50) DEFAULT NULL COMMENT '支付类型。可选值：WEIXIN（微信支付），ALIPAY（支付宝支付）',
  `consign_time` datetime DEFAULT NULL COMMENT '卖家发货时间',
  `buyer_area` varchar(50) DEFAULT NULL COMMENT '买家下单的地区',
  `shop_id` int(5) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `tid` (`tid`) USING BTREE,
  KEY `goods_money` (`receiver_mobile`) USING BTREE,
  KEY `shop_id` (`status`) USING BTREE,
  KEY `num_iid` (`num_iid`) USING BTREE,
  KEY `price` (`price`) USING BTREE,
  KEY `title` (`title`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;
