DROP TABLE IF EXISTS `api_taobao_fx_order`;
CREATE TABLE `api_taobao_fx_order` (
  `oid` int(11) unsigned AUTO_INCREMENT COMMENT '本表自增ID，注意不是淘宝平台的，淘平台请用ID',
  `ttid` int(11) unsigned COMMENT '父ID',
  `shop_code` varchar(50) DEFAULT '' COMMENT '店铺nick',
  `item_id` varchar(50) DEFAULT '' COMMENT '分销平台上的产品id，同FenxiaoProduct 的pid',
  `item_outer_id` varchar(50) DEFAULT '' COMMENT '分销平台上商品商家编码',
  `sku_outer_id` varchar(50) DEFAULT '' COMMENT 'SKU商家编码',
  `sku_properties` varchar(255) DEFAULT '' COMMENT 'SKU属性值',
  `auction_price` varchar(50) DEFAULT '' COMMENT '分销商店铺中宝贝一口价',
  `sku_id` varchar(50) DEFAULT '' COMMENT '分销产品的SKU id。当存在时才会有值，建议使用sku_outer_id，sku_properties这两个值',
  `bill_fee` varchar(50) DEFAULT '' COMMENT '发票应开金额。根据买家实际付款去除邮费后，按各个子单(商品)金额比例进行分摊后的金额，仅供开发票时做票面金额参考。',
  `num` varchar(50) DEFAULT '' COMMENT '产品的采购数量。取值范围:大于零的整数',
  `buyer_payment` varchar(50) DEFAULT '' COMMENT '买家订单上对应的子单零售金额，除以num（数量）后等于最终宝贝的零售价格（精确到2位小数;单位:元。如:200.07，表示:200元7分）',
  `discount_fee` varchar(50) DEFAULT '' COMMENT '优惠活动的折扣金额',
  `distributor_payment` varchar(50) DEFAULT '' COMMENT '分销商实付金额=total_fee（分销商应付金额）+改价-优惠。（精确到2位小数;单位:元。如:200.07，表示:200元7分）',
  `total_fee` varchar(50) DEFAULT '' COMMENT '分销商应付金额=num(采购数量)*price(采购价)。（精确到2位小数;单位:元。如:200.07，表示:200元7分）',
  `fenxiao_id` varchar(50) DEFAULT '' COMMENT '分销平台的子采购单主键',
  `created` varchar(50) DEFAULT '' COMMENT '创建时间',
  `order_200_status` varchar(50) DEFAULT '' COMMENT '代销采购单对应下游200订单状态。 可选值： WAIT_SELLER_SEND_GOODS(已付款，待发货) WAIT_BUYER_CONFIRM_GOODS(已付款，已发货) TRADE_CLOSED(已退款成功) TRADE_REFUNDING(退款中) TRADE_FINISHED(交易成功) TRADE_CLOSED_BY_TAOBAO(交易关闭)',
  `price` varchar(50) DEFAULT '' COMMENT '产品的采购价格。（精确到2位小数;单位:元。如:200.07，表示:200元7分）',
  `promotion_type` varchar(50) DEFAULT '' COMMENT '优惠活动类型 0=无优惠 1=限时折',
  `auction_sku_id` varchar(50) DEFAULT '' COMMENT '前台商品SKU ID，不存在时为0。2015年3月15日之前创建的采购单该字段都是0。',
  `refund_fee` varchar(50) DEFAULT '' COMMENT '退款金额',
  `sc_item_id` varchar(50) DEFAULT '' COMMENT '后端商品id',
  `snapshot_url` varchar(255) DEFAULT '' COMMENT '快照地址',
  `status` varchar(50) DEFAULT '' COMMENT '交易状态。可选值：WAIT_BUYER_PAY(等待付款),WAIT_CONFIRM(付款信息待确认),WAIT_CONFIRM_WAIT_SEND_GOODS(付款信息待确认，待发货),WAIT_CONFIRM_SEND_GOODS(付款信息待确认，已发货),WAIT_CONFIRM_GOODS_CONFIRM(付款信息待确认，已收货),WAIT_SELLER_SEND_GOODS(已付款，待发货),WAIT_BUYER_CONFIRM_GOODS(已付款，已发货),WAIT_BUYER_CONFIRM_GOODS_ACOUNTED(已付款（已分账），已发货。只对代销分账支持),CONFIRM_WAIT_SEND_GOODS(付款信息已确认，待发货),CONFIRM_SEND_GOODS(付款信息已确认，已发货),TRADE_REFUNDED(已退款),TRADE_REFUNDING(退款中),TRADE_FINISHED(交易成功),TRADE_CLOSED(交易关闭),PAY_ACOUNTED_GOODS_CONFIRM （已分账发货成功）,PAY_WAIT_ACOUNT_GOODS_CONFIRM（已付款，确认收货）',
  `id` varchar(50) DEFAULT '' COMMENT '子采购单id，淘宝交易主键，采购单未付款时为0.（只有支付宝 付款才有这个id，其余付款形式该字段为0）',
  `tc_order_id` varchar(50) DEFAULT '' COMMENT 'TC子订单ID（经销不显示）',
  `tc_adjust_fee` varchar(50) DEFAULT '' COMMENT '商品的卖出金额调整，金额增加时为正数，金额减少时为负数，单位是分，不带小数',
  `tc_discount_fee` varchar(50) DEFAULT '' COMMENT '优惠金额，始终为正数，单位是分，不带小数',
  `tc_preferential_type` varchar(50) DEFAULT '' COMMENT '商品优惠类型：聚划算、秒杀或其他',
  `title` varchar(255) DEFAULT '' COMMENT '采购的产品标题',
  `fenxiao_oid` varchar(50) DEFAULT NULL COMMENT '子采购订单id',
  PRIMARY KEY (`oid`),
  UNIQUE KEY `fenxiao_oid` (`fenxiao_oid`),
  KEY(`ttid`),
  KEY(`shop_code`),
  KEY `fenxiao_id` (`fenxiao_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT '淘宝分销订单明细';