
DROP TABLE IF EXISTS `base_store`;
CREATE TABLE `base_store` (
  `store_id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `store_code` varchar(128) DEFAULT '' COMMENT '仓库代码',
  `store_name` varchar(128) DEFAULT '' COMMENT '仓库名称',
  `area_code` varchar(128) DEFAULT '' COMMENT '区域代码',
  `user_code` varchar(64) DEFAULT '' COMMENT '员工代码',
  `store_type_code` varchar(128) DEFAULT '' COMMENT '仓库类别代码',
  `store_property` int(4) DEFAULT '0' COMMENT '仓库性质 0普通仓 1门店仓',
  `relation_code` varchar(128) DEFAULT '' COMMENT '外部编码',
  `status` int(4) DEFAULT '1' COMMENT '0：停用 1：启用',
  `sys` int(4) DEFAULT '0' COMMENT '是否是系统值 1：是 0：不是',
  `contact_person` varchar(128) DEFAULT '' COMMENT '联系人',
  `contact_phone` varchar(128) DEFAULT '' COMMENT '联系人电话',
  `contact_tel` varchar(128) DEFAULT '' COMMENT '联系人手机',
  `address` varchar(255) DEFAULT '' COMMENT '地址',
  `zipcode` varchar(128) DEFAULT '' COMMENT '邮编',
  `responsible_person` varchar(128) DEFAULT '' COMMENT '责任人',
  `responsible_phone` varchar(128) DEFAULT '' COMMENT '责任人电话',
  `responsible_tel` varchar(128) DEFAULT '' COMMENT '责任人手机',
  `shop_code` varchar(128) DEFAULT '' COMMENT '商店代码',
  `org_code` varchar(128) DEFAULT '000' COMMENT '渠道代码',
  `country` varchar(20) DEFAULT NULL COMMENT '国家',
  `province` varchar(20) DEFAULT NULL COMMENT '省份',
  `city` varchar(20) DEFAULT NULL COMMENT '城市',
  `district` varchar(20) DEFAULT NULL COMMENT '地区',
  `street` varchar(20) DEFAULT NULL COMMENT '街道',
  `message` varchar(255) DEFAULT '' COMMENT '留言',
  `remark` varchar(255) DEFAULT '' COMMENT '备注',
  `lastchanged` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后修改时间',
  `trd_id` varchar(64) DEFAULT '' COMMENT '第三方来源GUID',
  `trd_type` varchar(32) DEFAULT '' COMMENT '第三方来源类型:erp/3000/efast',
  `trd_time` varchar(64) DEFAULT '' COMMENT '第三方导入或者更新的时间',
  `shop_name` varchar(50) DEFAULT '' COMMENT '店铺名称',
  `shop_contact_person` varchar(20) DEFAULT '' COMMENT '寄件人',
  `message2` varchar(255) DEFAULT '' COMMENT '店铺留言2',
  `ship_area_code` varchar(50) DEFAULT '' COMMENT '发货区行政区划代码',
  `allow_negative_inv` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0' COMMENT '是否允许负库存: 0否, 1是',
  `custom_code` varchar(128) DEFAULT '' COMMENT '分销商',
  PRIMARY KEY (`store_id`)
) ENGINE=InnoDB AUTO_INCREMENT=27 DEFAULT CHARSET=utf8 COMMENT='仓库';


