DROP TABLE IF EXISTS `base_custom`;
CREATE TABLE `base_custom` (
  `custom_id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `custom_code` varchar(128) DEFAULT '' COMMENT '客户代码',
  `custom_name` varchar(128) DEFAULT '' COMMENT '客户名称',
  `email` varchar(128) DEFAULT '' COMMENT '邮箱',
  `phone` varchar(128) DEFAULT '' COMMENT '电话',
  `weixin` varchar(128) DEFAULT '' COMMENT '微信',
  `qq` varchar(128) DEFAULT '' COMMENT 'QQ',
  `mobile` varchar(128) DEFAULT '' COMMENT '手机',
  `tel` varchar(128) DEFAULT '' COMMENT '电话',
  `address` varchar(255) DEFAULT '' COMMENT '地址',
  `fax` varchar(128) DEFAULT '' COMMENT '传真',
  `zipcode` varchar(128) DEFAULT '' COMMENT '邮编',
  `website` varchar(255) DEFAULT '' COMMENT '公司网站',
  `rebate` decimal(4,3) DEFAULT '1.000' COMMENT '折扣',
  `price_type` varchar(64) DEFAULT '' COMMENT '价格类型',
  `sys` int(4) DEFAULT '0' COMMENT '是否是系统值 1：是 0：不是',
  `remark` varchar(255) DEFAULT '' COMMENT '备注',
  `lastchanged` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后修改时间',
  `contact_person` varchar(128) DEFAULT '' COMMENT '联系人',
  `pay_account` varchar(128) DEFAULT NULL COMMENT '支付宝帐号',
  `credit_lines` decimal(10,3) NOT NULL DEFAULT '0.000' COMMENT '信用额度',
  `account_money` decimal(10,3) NOT NULL DEFAULT '0.000' COMMENT '账户金额',
  `frozen_money` decimal(10,3) NOT NULL DEFAULT '0.000' COMMENT '冻结金额',
  `settlement_amount` decimal(10,3) NOT NULL DEFAULT '0.000' COMMENT '可结算金额',
  `fixed_money` decimal(10,3) NOT NULL DEFAULT '0.000' COMMENT '固定费用',
  `settlement_method` varchar(128) DEFAULT NULL COMMENT '费用结算方式',
  `custom_nick` varchar(128) DEFAULT NULL COMMENT '分销商昵称',
  `custom_type` varchar(128) DEFAULT NULL COMMENT 'tb_fx:淘宝分销；pt_fx:普通分销',
  `shop_code` varchar(128) DEFAULT NULL COMMENT '店铺',
  `custom_user` varchar(128) DEFAULT NULL COMMENT '分销专员',
  `custom_grade` tinyint(3) DEFAULT NULL COMMENT '分销商等级',
  `custom_price_type` varchar(128) DEFAULT NULL COMMENT '结算价格',
  `custom_rebate` varchar(128) DEFAULT NULL COMMENT '结算折扣',
  `is_effective` tinyint(3) DEFAULT '1' COMMENT '是否有效',
  `user_code` varchar(128) DEFAULT null COMMENT '登录帐号',
  PRIMARY KEY (`custom_id`)
) ENGINE=InnoDB AUTO_INCREMENT=21 DEFAULT CHARSET=utf8 COMMENT='客户';
