
DROP TABLE IF EXISTS `base_express`;
CREATE TABLE `base_express` (
  `express_id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `company_code` varchar(20) DEFAULT NULL,
  `express_code` varchar(128) DEFAULT '' COMMENT '代码',
  `express_name` varchar(128) DEFAULT '' COMMENT '名称',
  `type` int(4) DEFAULT '0' COMMENT '0：B2C 1：B2B',
  `area_type` int(4) DEFAULT '0' COMMENT '0：不维护 1：维护可达 2:维护不可达',
  `tel` varchar(128) DEFAULT '' COMMENT '手机',
  `status` int(4) DEFAULT '0' COMMENT '0：停用 1：启用',
  `is_cash_on_delivery` int(4) DEFAULT '0' COMMENT '货到付款 0：不是 1：是',
  `sys` int(4) DEFAULT '0' COMMENT '是否是系统值 1：是 0：不是',
  `goods_img` varchar(128) DEFAULT '' COMMENT '主图地址',
  `is_add_person` varchar(64) DEFAULT '' COMMENT '添加人',
  `is_add_time` datetime DEFAULT NULL COMMENT '添加时间',
  `is_edit_person` varchar(64) DEFAULT '' COMMENT '修改人',
  `is_edit_time` datetime DEFAULT NULL COMMENT '修改时间',
  `print` longtext COMMENT '打印模版',
  `printer_name` varchar(100) DEFAULT NULL COMMENT '打印机名称',
  `remark` varchar(255) DEFAULT '' COMMENT '备注',
  `reg_mail_no` varchar(255) DEFAULT '' COMMENT '物流公司对应的运单规则',
  `calc_type` tinyint(3) DEFAULT '0' COMMENT '计费方式0按重量1按体积',
  `base_fee` decimal(10,3) DEFAULT '0.000'  COMMENT '首重单价',
  `base_weight` decimal(10,2) DEFAULT '0.00' COMMENT '首重重量',
  `per_fee` decimal(10,3) DEFAULT '0.000'  COMMENT '续重单价',
  `per_weight` decimal(10,2) DEFAULT '0.00' COMMENT '续重重量',
  `free_fee` decimal(10,3) DEFAULT '0.000'  COMMENT '免费额度',
  `per_rule` decimal(10,3) DEFAULT '0.000'  COMMENT '续重规则',
  `zk` decimal(10,3) DEFAULT NULL COMMENT '折扣',
  `free_per_weight` decimal(10,2) DEFAULT NULL COMMENT '免费续重',
  `print_type` int(4) DEFAULT '0' COMMENT '0：普通打印 1：直连热敏 2:云栈热敏',
  `rm_id` int(11) unsigned DEFAULT NULL COMMENT '热敏模板id',
  `rm_shop_code` varchar(128) DEFAULT '' COMMENT '热敏挂靠商店代码',
  `df_id` int(11) unsigned DEFAULT NULL COMMENT '到付模板id',
  `pt_id` int(11) unsigned DEFAULT NULL COMMENT '普通模板id',
  `lastchanged` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后修改时间',
  PRIMARY KEY (`express_id`)
) ENGINE=InnoDB AUTO_INCREMENT=56 DEFAULT CHARSET=utf8 COMMENT='配送方式，快递方式';
