
DROP TABLE IF EXISTS `base_shop`;
CREATE TABLE `base_shop` (
  `shop_id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `shop_code` varchar(128) DEFAULT '' COMMENT '商店代码',
  `shop_name` varchar(128) DEFAULT '' COMMENT '商店名称',
  `shop_type` tinyint(1) DEFAULT '0' COMMENT '商店性质,0网络店铺、1实体店铺',
  `entity_type` tinyint(1) DEFAULT '0' COMMENT '门店性质,0直营店、1加盟店',
  `open_time` varchar(20) DEFAULT NULL COMMENT '营业时间:9:00-18:00',
  `sale_channel_code` varchar(30) DEFAULT '' COMMENT '销售平台代码',
  `contact_person` varchar(128) DEFAULT '' COMMENT '联系人',
  `email` varchar(128) DEFAULT '' COMMENT '邮箱',
  `phone` varchar(128) DEFAULT '' COMMENT '电话',
  `tel` varchar(128) DEFAULT '' COMMENT '手机',
  `rank` tinyint(3) DEFAULT '0' COMMENT '等级',
  `address` varchar(255) DEFAULT '' COMMENT '地址',
  `province` varchar(20) DEFAULT NULL COMMENT '省',
  `city` varchar(20) DEFAULT NULL COMMENT '市',
  `district` VARCHAR(20) DEFAULT NULL COMMENT '区',
  `street` VARCHAR(20) DEFAULT NULL COMMENT '街道',
  `fax` varchar(128) DEFAULT '' COMMENT '传真',
  `zipcode` varchar(128) DEFAULT '' COMMENT '邮编',
  `ww` varchar(50) DEFAULT NULL COMMENT '旺旺号',
  `alipay_no` varchar(50) DEFAULT NULL COMMENT '支付宝帐号',
  `remark` varchar(255) DEFAULT '' COMMENT '备注',
  `lastchanged` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后修改时间',
  `send_store_code` varchar(20) DEFAULT '' COMMENT '发货仓库',
  `refund_store_code` varchar(20) DEFAULT '' COMMENT '退货仓库',
  `stock_source_store_code` varchar(500) NOT NULL DEFAULT '库存来源仓库,多个仓以逗号分开',
  `fenxiao_status` tinyint(1) NOT NULL DEFAULT '0' COMMENT '不启用分销=0，启用分销=1',
  `express_code` varchar(20) DEFAULT '' COMMENT '默认快递方式',
  `sale_channel_id` int(10) DEFAULT NULL COMMENT '销售渠道',
  `presale` tinyint(4) NOT NULL DEFAULT '0' COMMENT '预售,默认为0，大于0为店铺开启预售，等于0为店铺不开启预售（大于0表示的是商品的默认承诺发货天数，此值代表现货承诺发货天数）',
  `days` int(10) unsigned DEFAULT '0' COMMENT '承诺发货天数',
  `authorize_state` int(1) DEFAULT '0' COMMENT '0未授权 1授权',
  `authorize_date` datetime DEFAULT NULL COMMENT '授权截止时间',
  `shop_user_nick` varchar(30) DEFAULT '' COMMENT '店铺昵称',
  `is_active` int(1) DEFAULT '0' COMMENT '0关闭，1开启',
  `alipay_order_status` tinyint(1) NULL DEFAULT 0 COMMENT '支付宝订购状态 0-未订购，1-订购',
  `express_data` varchar(255) DEFAULT '' COMMENT '快递公司',
  `shop_desc` varchar(255) DEFAULT '' COMMENT '店铺介绍',
  `create_time` datetime NOT NULL COMMENT '创建时间',
  `create_person` varchar(128) DEFAULT '' COMMENT '创建人',
  PRIMARY KEY (`shop_id`),
  UNIQUE KEY `shop_code` (`shop_code`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=20 DEFAULT CHARSET=utf8 COMMENT='商店'

