DROP TABLE IF EXISTS `crm_client`;

CREATE TABLE `crm_client` (
	`client_id` INT (11) UNSIGNED NOT NULL AUTO_INCREMENT,
	`client_code` VARCHAR (30) DEFAULT '' COMMENT '顾客代码',
	`client_name` VARCHAR (30) DEFAULT '' COMMENT '顾客名称',
	`status` TINYINT (1) DEFAULT NULL COMMENT '1：未提交 2：已提交 3：已审核 4：已发卡 5：已领用 6：完成 7：退回',
	`birthday` datetime DEFAULT NULL COMMENT '生日',
	`client_sex` TINYINT (1) DEFAULT '3' COMMENT '性别 1:男 2:女 3:保密',
	`client_tel` VARCHAR (20) DEFAULT '' COMMENT '手机号码',
	`email` VARCHAR (128) DEFAULT '' COMMENT '电子邮箱',
	`add_time` datetime DEFAULT NULL COMMENT '加入时间',
	`address` VARCHAR (255) DEFAULT '' COMMENT '详细地址',
	`level` INT (4) DEFAULT '0' COMMENT '会员卡等级',
	`level_time` datetime DEFAULT NULL COMMENT '升级时间',
	`last_consume_time` datetime DEFAULT NULL COMMENT '最后一次消费时间',
	`is_vip` TINYINT (1) DEFAULT '0' COMMENT '0:不是会员 1:是会员',
	`is_followed_weixin` TINYINT (1) DEFAULT '0' COMMENT '0:未关注 1:已关注',
	`marriage` TINYINT (1) DEFAULT '0' COMMENT '婚姻状况 1：已婚 2：未婚 0：保密',
	`education` TINYINT (1) DEFAULT '0' COMMENT '学历 1：小学及以下，2：初中，3：高中，4：中专，5：大专，6：本科，7：研究生，8：博士及以上，0：保密',
	`consume_money` DECIMAL (20, 3) DEFAULT '0.000' COMMENT '累计消费金额',
	`consume_num` VARCHAR (64) DEFAULT '0' COMMENT '累计消费数量',
	`client_balance` INT (11) DEFAULT '0' COMMENT '剩余余额',
	`client_integral` INT (11) DEFAULT '0' COMMENT '剩余积分',
	`is_black` TINYINT (1) DEFAULT '0' COMMENT '0:不在黑名单 1:在黑名单',
	`country` VARCHAR (20) DEFAULT '1' COMMENT '国家',
	`province` VARCHAR (20) DEFAULT '0' COMMENT '省',
	`city` VARCHAR (20) DEFAULT '0' COMMENT '城市',
	`district` VARCHAR (20) DEFAULT '0' COMMENT '地区',
	`street` VARCHAR (20) DEFAULT '0' COMMENT '街道',
	`remark` VARCHAR (255) DEFAULT '' COMMENT '备注',
	`is_add_person` VARCHAR (64) DEFAULT '' COMMENT '添加人',
	`is_add_time` datetime DEFAULT NULL COMMENT '添加时间',
	`lastchanged` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后修改时间',
	`trd_id` VARCHAR (64) DEFAULT '' COMMENT '第三方来源GUID',
	`trd_type` VARCHAR (32) DEFAULT '' COMMENT '第三方来源类型:erp/3000/efast',
	`trd_time` VARCHAR (64) DEFAULT '' COMMENT '第三方导入或者更新的时间',
	PRIMARY KEY (`client_id`),
	UNIQUE KEY `idxu` (`client_code`) USING BTREE,
	UNIQUE KEY `idxu2` (`client_tel`) USING BTREE,
	KEY `client_name` (`client_name`) USING BTREE,
	KEY `status` (`status`) USING BTREE
) ENGINE = INNODB DEFAULT CHARSET = utf8 COMMENT = '顾客列表';