
DROP TABLE IF EXISTS `crm_customer`;
CREATE TABLE `crm_customer` (
  `customer_id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `customer_code` varchar(30) DEFAULT '' COMMENT '顾客代码',
  `customer_name` varchar(30) DEFAULT '' COMMENT '顾客名称',
  `customer_level` varchar(30) DEFAULT '1' COMMENT '会员等级',
  `shop_code` varchar(30) DEFAULT '' COMMENT '商店代码',
  `customer_tel` varchar(64) DEFAULT '' COMMENT '手机号码',
  `customer_sex` varchar(64) DEFAULT '' COMMENT '性别 1：男 2：女',
  `email` varchar(64) DEFAULT '' COMMENT 'email',
  `address` varchar(255) DEFAULT '' COMMENT '地址',
  `work_address` varchar(255) DEFAULT '' COMMENT '工作地址',
  `birthday` date DEFAULT NULL COMMENT '生日',
  `customer_integral` int(11) DEFAULT '0' COMMENT '顾客积分',
  `consume_money` decimal(20,3) DEFAULT '0.000' COMMENT '消费金额',
  `consume_num` varchar(64) DEFAULT '0' COMMENT '消费数量',
  `password` varchar(64) DEFAULT '' COMMENT '密码',
  `id_card` varchar(128) DEFAULT '' COMMENT '身份证',
  `status` int(4) DEFAULT NULL COMMENT '1：未提交 2：已提交 3：已审核 4：已发卡 5：已领用 6：完成 7：退回',
  `nickname` varchar(30) DEFAULT '' COMMENT '昵称',
  `type` int(4) DEFAULT '1' COMMENT '1：正常 2：黑名单 3:禁言',
  `level_time` datetime DEFAULT NULL COMMENT '升级时间',
  `is_online` int(4) DEFAULT '1' COMMENT '是否线上用户，1：不是，2：是',
  `is_offline` int(4) DEFAULT '1' COMMENT '是否线下用户，1：不是，2：是',
  `country` varchar(20) DEFAULT '1' COMMENT '国家',
  `province` varchar(20) DEFAULT '0' COMMENT '省',
  `city` varchar(20) DEFAULT '0' COMMENT '城市',
  `district` varchar(20) DEFAULT '0' COMMENT '地区',
  `marriage` int(4) DEFAULT '0' COMMENT '婚姻状况 1：已婚 2：未婚 0：保密',
  `education` int(4) DEFAULT '0' COMMENT '学历 1：小学及以下，2：初中，3：高中，4：中专，5：大专，6：本科，7：研究生，8：博士及以上，0：保密',
  `weixin_id` varchar(128) DEFAULT '' COMMENT '微信id',
  `is_edit` int(4) DEFAULT '0' COMMENT '前台编辑 0:未编辑 1：已编辑',
  `remark` varchar(255) DEFAULT '' COMMENT '备注',
  `lastchanged` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后修改时间',
  `is_add_person` varchar(64) DEFAULT '' COMMENT '添加人',
  `is_add_time` datetime DEFAULT NULL COMMENT '添加时间',
  `is_edit_person` varchar(64) DEFAULT '' COMMENT '修改人',
  `is_edit_time` datetime DEFAULT NULL COMMENT '修改时间',
  `trd_id` varchar(64) DEFAULT '' COMMENT '第三方来源GUID',
  `trd_type` varchar(32) DEFAULT '' COMMENT '第三方来源类型:erp/3000/efast',
  `trd_time` varchar(64) DEFAULT '' COMMENT '第三方导入或者更新的时间',
  `tel` varchar(20) DEFAULT NULL,
  `home_tel` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`customer_id`),
  UNIQUE KEY `idxu` (`customer_code`) USING BTREE,
  UNIQUE KEY `idxu2` (`customer_name`,`shop_code`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='顾客';