DROP TABLE IF EXISTS `oms_sell_record_detail`;
CREATE TABLE `oms_sell_record_detail` (
  `sell_record_detail_id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `sell_record_code` varchar(64) NOT NULL DEFAULT '' COMMENT '单据编号',
  `deal_code` varchar(64) NOT NULL DEFAULT '' COMMENT '平台交易号',
  `sub_deal_code` varchar(64) NOT NULL DEFAULT '' COMMENT '平台子交易号',
  `goods_code` varchar(20) NOT NULL DEFAULT '' COMMENT '商品代码',
  `spec1_code` varchar(20) NOT NULL DEFAULT '' COMMENT '颜色代码',
  `spec2_code` varchar(20) NOT NULL DEFAULT '' COMMENT '尺码代码',
  `sku_id` varchar(20) NOT NULL DEFAULT '' COMMENT 'sku_id',
  `sku` varchar(128) NOT NULL DEFAULT '' COMMENT 'sku',
  `combo_sku` varchar(128) DEFAULT '',
  `barcode` varchar(30) NOT NULL DEFAULT '' COMMENT '条码',
  `goods_price` decimal(10,3) NOT NULL DEFAULT '0.000' COMMENT '商品单价(实际售价)',
  `cost_price` decimal(10,3) NOT NULL DEFAULT '0.000' COMMENT '商品成本单价',
  `num` int(11) NOT NULL DEFAULT '0' COMMENT '数量',
  `lock_num` int(10) NOT NULL DEFAULT '0' COMMENT '锁定数量',
  `return_num` int(11) NOT NULL DEFAULT '0' COMMENT '退货数量',
  `goods_weigh` decimal(10,3) NOT NULL DEFAULT '0.000' COMMENT '商品重量',
  `avg_money` decimal(10,3) NOT NULL DEFAULT '0.000' COMMENT '均摊金额',
  `trade_price` decimal(10,3) NOT NULL DEFAULT '0.000' COMMENT '批发价,即分销单价',
  `fx_amount` decimal(10,3) NOT NULL DEFAULT '0.000' COMMENT '结算金额（分销单价*num）,用于分销',
  `platform_spec` varchar(255) NOT NULL DEFAULT '' COMMENT '平台规格',
  `lock_inv_status` int(4) NOT NULL DEFAULT '0' COMMENT '库存状态：0-未锁定 1-已锁定 2-部分锁定',
  `is_gift` tinyint(4) NOT NULL DEFAULT '0' COMMENT '礼品标识：0-普通商品1-礼品',
  `sale_mode` varchar(10) NOT NULL DEFAULT 'stock' COMMENT '销售模式：现货stock，预售presale',
  `delivery_mode` varchar(10) NOT NULL DEFAULT 'days' COMMENT 'days承诺发货天数 ; time预售发货时间',
  `delivery_days_or_time` varchar(20) NOT NULL COMMENT '存放承诺发货期或预售发货时间',
  `plan_send_time` datetime NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT 'SKU计划发货时间',
  `is_delete` int(11) NOT NULL DEFAULT '0' COMMENT '0有效 大于0无效明细,无效时填写无效timestamp',
  `api_refund_num` int(11) DEFAULT '0' COMMENT 'api退货数量',
  `api_refund_desc` varchar(255) DEFAULT '' COMMENT 'api退货描述',
  `lastchanged` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后修改时间',
  `pic_path` varchar(200) DEFAULT '' COMMENT '商品图片地址',
  `return_money` decimal(10,3) NOT NULL DEFAULT '0.000' COMMENT '退货金额',
  PRIMARY KEY (`sell_record_detail_id`),
  UNIQUE KEY `idxu_key` (`sell_record_code`,`deal_code`,`sku`,`is_delete`,`is_gift`) USING BTREE,
  KEY `lastchanged` (`lastchanged`) USING BTREE,
  KEY `sub_deal_code` (`sub_deal_code`) USING BTREE
    KEY `goods_code_index` (`goods_code`) USING BTREE,
  KEY `sku_index` (`sku`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='销售订单明细表';