
DROP TABLE IF EXISTS `oms_deliver_record`;
CREATE TABLE `oms_deliver_record` (
  `deliver_record_id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `sell_record_code` varchar(128) NOT NULL COMMENT '订单编号',
  `deal_code` varchar(200) NOT NULL COMMENT '交易号',
  `deal_code_list` varchar(500) NOT NULL DEFAULT '' COMMENT '平台交易号列表',
  `sale_channel_code` varchar(20) NOT NULL COMMENT '销售平台',
  `store_code` varchar(128) DEFAULT '' COMMENT '仓库代码',
  `shop_code` varchar(128) DEFAULT '' COMMENT '商店代码',
  `pay_type` varchar(20) NOT NULL DEFAULT 'secured' COMMENT 'secured 担保交易 cod货到付款 nosecured 非担保交易',
  `pay_code` varchar(32) DEFAULT '' COMMENT '支付方式代码',
  `pay_time` datetime DEFAULT NULL COMMENT '支付时间',
  `goods_num` int(11) DEFAULT '0' COMMENT '商品数量',
  `sku_num` int(11) DEFAULT '0' COMMENT 'sku种类数量',
  `record_time` datetime DEFAULT NULL COMMENT '下单时间',
  `goods_weigh` decimal(20,3) DEFAULT '0.000' COMMENT '商品总重量',
  `real_weigh` decimal(10,3) DEFAULT '0.000' COMMENT '实际总重量',
  `weigh_express_money` decimal(10,2) DEFAULT '0.00' COMMENT '称重后计算的快递费用',
  `weigh_time` datetime DEFAULT NULL COMMENT '称重时间',
  `express_code` varchar(64) DEFAULT '0' COMMENT '配送方式CODE',
  `express_no` varchar(128) DEFAULT '' COMMENT '快递单号',
  `express_data` text COMMENT '云栈获取数据',
  `package_no` tinyint(3) DEFAULT '0' COMMENT '包裹号',
  `send_order` tinyint(4) DEFAULT '0' COMMENT '订单发货优先级',
  `pack_no` int(11) DEFAULT '0',
  `waves_record_id` int(11) DEFAULT '0' COMMENT '波次单编号',
  `order_money` decimal(10,3) NOT NULL DEFAULT '0.000' COMMENT '订单总额,商品总额+运费+配送手续费',
  `goods_money` decimal(10,3) NOT NULL DEFAULT '0.000' COMMENT '商品总额',
  `express_money` decimal(10,3) NOT NULL DEFAULT '0.000' COMMENT '运费',
  `delivery_money` decimal(10,3) NOT NULL DEFAULT '0.000' COMMENT '配送手续费',
  `paid_money` decimal(20,3) DEFAULT '0.000' COMMENT '订单已付款,已支付状态下与应付款相等',
  `payable_money` decimal(20,3) DEFAULT '0.000' COMMENT '订单应付款,顾客应支付金额，=订单总额-商品折让-其他折让',
  `buyer_remark` varchar(255) DEFAULT '' COMMENT '买家留言',
  `seller_remark` varchar(255) DEFAULT '' COMMENT '商家备注',
  `seller_flag` int(4) DEFAULT '0' COMMENT '淘宝订单的旗帜',
  `store_remark` varchar(255) NOT NULL DEFAULT '' COMMENT '仓库留言',
  `sort_no` int(11) DEFAULT '0' COMMENT '序号',
  `order_remark` varchar(255) DEFAULT '' COMMENT '订单备注',
  `buyer_name` varchar(20) NOT NULL DEFAULT '' COMMENT '购买人名称',
  `receiver_name` varchar(128) DEFAULT '' COMMENT '收货人名称',
  `receiver_country` bigint(20) DEFAULT '0' COMMENT '国家',
  `receiver_province` bigint(20) DEFAULT '0' COMMENT '省',
  `receiver_city` bigint(20) DEFAULT '0' COMMENT '市',
  `receiver_district` bigint(20) DEFAULT '0' COMMENT '区',
  `receiver_street` bigint(20) DEFAULT '0' COMMENT '区',
  `receiver_address` varchar(255) DEFAULT '' COMMENT '地址(包含省市区)',
  `receiver_addr` varchar(255) DEFAULT '' COMMENT '地址(不包含省市区)',
  `receiver_zip_code` varchar(64) DEFAULT '' COMMENT '邮政编码',
  `receiver_mobile` varchar(32) DEFAULT '' COMMENT '电话',
  `receiver_phone` varchar(32) DEFAULT '' COMMENT '固定电话',
  `receiver_email` varchar(128) DEFAULT '' COMMENT 'email',
  `invoice_type` varchar(255) DEFAULT '' COMMENT '发票类型',
  `invoice_title` varchar(255) DEFAULT '' COMMENT '发票抬头',
  `invoice_content` varchar(255) DEFAULT '' COMMENT '发票内容',
  `invoice_money` varchar(255) DEFAULT '' COMMENT '发票金额',
  `invoice_status` int(4) DEFAULT '0' COMMENT '发票状态：0初始状态，1已审核状态，2已开票状态,3已作废状态',
  `lastchanged` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后修改时间',
  `delivery_time` datetime DEFAULT NULL COMMENT '实际发货时间',
  `delivery_date` date DEFAULT NULL COMMENT '实际发货日期',
  `is_weigh` int(4) DEFAULT '0' COMMENT '称重 0未称重 1称重',
  `is_edit_shipping_time` datetime DEFAULT NULL COMMENT '配送方式修改时间',
  `is_plan_send_time` datetime DEFAULT NULL COMMENT '计划发货时间',
  `is_hope_send_time` datetime DEFAULT NULL COMMENT '期望配送时间',
  `is_last_send_time` datetime DEFAULT NULL COMMENT '承诺买家最晚发货时间',
  `is_print_sellrecord` tinyint(3) DEFAULT '0' COMMENT '是否打印订单',
  `is_print_express` tinyint(3) DEFAULT '0' COMMENT '是否打印快递',
  `is_cancel` int(11) DEFAULT '0',
  `is_deliver` tinyint(3) DEFAULT '0' COMMENT '是否发货',
  `is_notice_time` datetime DEFAULT NULL COMMENT '通知时间',
  `is_stock_out` int(4) DEFAULT '0' COMMENT '是否缺货 0未缺货 1缺货 2部分缺货',
  `is_print_invoice` tinyint(3) NOT NULL DEFAULT '0' COMMENT '是否打印发票',
  `weigh_person` varchar(20) NOT NULL DEFAULT '' COMMENT '称重人',
  `buyer_alipay_no` varchar(50) DEFAULT '' COMMENT '买家支付宝账号',
  PRIMARY KEY (`deliver_record_id`),
  UNIQUE KEY `idxu` (`sell_record_code`,`is_cancel`) USING BTREE,
  KEY `_waves_record_id` (`waves_record_id`) USING BTREE,
  KEY `is_print_invoice` (`is_print_invoice`),
  KEY `index1` (`is_deliver`) USING BTREE,
  KEY `index2` (`is_cancel`) USING BTREE,
  KEY `express_no` (`express_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='发货订单';

