DROP TABLE IF EXISTS `oms_sell_settlement`;
CREATE TABLE `oms_sell_settlement` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `order_attr` tinyint(4) NOT NULL DEFAULT '1' COMMENT '单据性质：1销售 2退货',
  `sale_channel_code` varchar(20) NOT NULL COMMENT '平台代码',
  `deal_code` varchar(64) NOT NULL DEFAULT '' COMMENT '平台交易号',
  `shop_code` varchar(20) NOT NULL DEFAULT '' COMMENT '商店代码',
  `alipay_no` varchar(30) NOT NULL DEFAULT '' COMMENT '支付宝交易号',
  `total_fee` decimal(10,3) NOT NULL DEFAULT '0.000' COMMENT '总应收款',
  `express_money` decimal(10,3) NOT NULL DEFAULT '0.000' COMMENT '运费',
  `point_fee` decimal(10,3) NOT NULL COMMENT '积分抵用金额',
  `ali_in_amount` decimal(10,3) NOT NULL DEFAULT '0.000' COMMENT '收入金额',
  `ali_out_amount` decimal(10,3) NOT NULL DEFAULT '0.000' COMMENT '支出金额',
  `commission_fee` decimal(10,3) NOT NULL DEFAULT '0.000' COMMENT '交易佣金',
  `num` int(11) NOT NULL DEFAULT '0' COMMENT '商品发货数量',
  `return_num` int(11) NOT NULL DEFAULT '0' COMMENT '商品退货数量',
  `sell_record_avg_money` decimal(10,3) NOT NULL DEFAULT '0.000' COMMENT '商品均摊总金额',
  `sell_return_avg_money` decimal(10,3) NOT NULL DEFAULT '0.000' COMMENT '商品退货均摊总金额',
  `compensate_money` decimal(20,3) NOT NULL DEFAULT '0.000' COMMENT '补差金额',
  `create_time` datetime NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '添加时间',
  `lastchanged` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后修改时间',
  `account_month` date NOT NULL DEFAULT '0000-00-00' COMMENT '财务账期',
  `check_accounts_status` tinyint(4) NOT NULL DEFAULT '0' COMMENT '核销状态 0未对账 10已核销 20部分核销 30虚拟核消  40人工核销 50核销失败',
  `check_accounts_time` datetime NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '核销时间',
  `check_accounts_user_code` varchar(20) NOT NULL DEFAULT '' COMMENT '核销人',
  `sell_month` date NOT NULL DEFAULT '0000-00-00' COMMENT '业务账期',
  `account_month_ym` varchar(7) NOT NULL DEFAULT '0000-00' COMMENT '财务账期--仅年月',
  `sell_month_ym` varchar(7) NOT NULL DEFAULT '0000-00' COMMENT '业务账期--仅年月',
  `sale_right_fee` decimal(10,3) NOT NULL DEFAULT '0.000' COMMENT '售后维权退款',
  `commission_fee2` decimal(10,3) NOT NULL DEFAULT '0.000' COMMENT '淘宝客佣金代扣款',
  `credit_code_fee` decimal(10,3) NOT NULL DEFAULT '0.000' COMMENT '信用卡支付服务费',
  `ali_trade_je` decimal(10,3) NOT NULL DEFAULT '0.000' COMMENT '支付宝交易收款',
  `adjust_money` decimal(20,3) NOT NULL DEFAULT '0.000' COMMENT '调整金额',
  `real_point_fee` decimal(10,3) NOT NULL DEFAULT '0.000' COMMENT '天猫积分抵扣金额',
  `record_time` datetime NOT NULL COMMENT '下单时间',
  `pay_time` datetime NOT NULL COMMENT '支付时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `idxu_code` (`deal_code`) USING BTREE,
  KEY `idx_lastchanged` (`lastchanged`) USING BTREE,
  KEY `idx_sale_channel_code` (`sale_channel_code`) USING BTREE,
  KEY `idx_deal_code` (`deal_code`) USING BTREE,
  KEY `idx_shop_code` (`shop_code`) USING BTREE,
  KEY `idx_alipay_no` (`alipay_no`) USING BTREE,
  KEY `idx_create_time` (`create_time`) USING BTREE,
  KEY `pay_time` (`pay_time`),
  KEY `record_time` (`record_time`),
  KEY `sell_month` (`sell_month`),
  KEY `sell_month_ym` (`sell_month_ym`),
  KEY `account_month` (`account_month`),
  KEY `account_month_ym` (`account_month_ym`),
  KEY `check_accounts_time` (`check_accounts_time`),
  KEY `idx_account_momth` (`shop_code`,`check_accounts_status`,`account_month_ym`,`sell_month_ym`)
) ENGINE=InnoDB AUTO_INCREMENT=178 DEFAULT CHARSET=utf8 COMMENT='零售结算单';





