-- ----------------------------
-- Table structure for oms_sell_return
-- ----------------------------
DROP TABLE IF EXISTS `oms_sell_return`;
CREATE TABLE `oms_sell_return` (
  `sell_return_id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `return_type` tinyint(1) NOT NULL DEFAULT '0' COMMENT '退单类型 1仅退款 2仅退货 3退款退货',
  `is_compensate` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否赔付',
  `is_packet_out_stock` tinyint(1) NOT NULL DEFAULT '0' COMMENT '订单包裹是否已出库',
  `create_time` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '创建时间',
  `sell_return_code` varchar(20) NOT NULL DEFAULT '' COMMENT '退单号',
  `sell_record_code` varchar(20) NOT NULL DEFAULT '' COMMENT '关联订单号',
  `refund_id` varchar(30) DEFAULT NULL COMMENT '平台退单号',
  `change_record` varchar(20) NOT NULL DEFAULT '' COMMENT '换货单号',
  `deal_code` varchar(200) NOT NULL DEFAULT '' COMMENT '平台交易号(交易号)',
  `deal_code_list` varchar(200) NOT NULL DEFAULT '' COMMENT '平台交易号列表',
  `stock_date` date NOT NULL DEFAULT '0000-00-00' COMMENT '业务日期',
  `store_code` varchar(20) NOT NULL DEFAULT '' COMMENT '退货仓库代码',
  `shop_code` varchar(20) NOT NULL DEFAULT '' COMMENT '商店代码',
  `sale_channel_code` varchar(20) NOT NULL DEFAULT '0' COMMENT '销售渠道代码',
  `return_pay_code` varchar(32) NOT NULL DEFAULT '' COMMENT '退款方式代码',
  `relation_shipping_status` tinyint(11) NOT NULL DEFAULT '0' COMMENT '原单：配送状态.0-未发货 1-已通知配货 2-拣货中(已分配拣货任务) 3-已完成拣货 4-已发货',
  `return_order_status` tinyint(11) NOT NULL DEFAULT '0' COMMENT '退单状态.0-未确认；1-已确认； 3-已作废；',
  `finance_check_status` tinyint(11) NOT NULL COMMENT '财务审核 0未审 1财务审核通过 2通知财务审核 3退回',
  `return_shipping_status` tinyint(11) NOT NULL DEFAULT '0' COMMENT '配送状态.0-初始; 1-已验收入库 2-已通知仓库收货',
  `is_package_out_stock` tinyint(11) NOT NULL DEFAULT '0' COMMENT '订单包裹是否已出库',
  `sell_record_checkpay_status` tinyint(1) NOT NULL DEFAULT '0' COMMENT '买家确认支付状态 0 未确认 1 已确认',
  `customer_code` varchar(20) NOT NULL DEFAULT '' COMMENT '会员代码',
  `buyer_name` varchar(20) NOT NULL DEFAULT '' COMMENT '购买人名称',
  `return_name` varchar(20) NOT NULL DEFAULT '' COMMENT '退货人名称',
  `return_country` bigint(11) NOT NULL DEFAULT '0' COMMENT '退货人国家',
  `return_province` bigint(11) NOT NULL DEFAULT '0' COMMENT '退货人省',
  `return_city` bigint(11) NOT NULL DEFAULT '0' COMMENT '退货人市',
  `return_district` bigint(11) NOT NULL DEFAULT '0' COMMENT '退货人区',
  `return_street` bigint(11) NOT NULL DEFAULT '0' COMMENT '退货人街道',
  `return_address` varchar(100) NOT NULL DEFAULT '' COMMENT '地址(包含省市区)',
  `return_addr` varchar(100) NOT NULL DEFAULT '' COMMENT '地址(不包含省市区)',
  `return_zip_code` varchar(20) NOT NULL DEFAULT '' COMMENT '邮政编码',
  `return_mobile` varchar(32) NOT NULL DEFAULT '' COMMENT '电话',
  `return_phone` varchar(32) NOT NULL DEFAULT '' COMMENT '固定电话',
  `return_email` varchar(40) NOT NULL DEFAULT '' COMMENT 'email',
  `return_express_code` varchar(20) NOT NULL DEFAULT '0' COMMENT '退货快递公司CODE',
  `return_express_no` varchar(40) NOT NULL DEFAULT '' COMMENT '快递单号',
  `return_reason_code` varchar(40) NOT NULL DEFAULT '' COMMENT '退货原因代码',
  `return_buyer_memo` varchar(255) NOT NULL DEFAULT '' COMMENT '退单说明（买家）',
  `return_remark` varchar(255) NOT NULL DEFAULT '' COMMENT '退单备注',
  `refund_total_fee` decimal(20,3) NOT NULL DEFAULT '0.000' COMMENT '实际退款总金额',
  `compensate_money` decimal(20,3) NOT NULL DEFAULT '0.000' COMMENT '赔付金额',
  `buyer_express_money` decimal(20,3) NOT NULL DEFAULT '0.000' COMMENT '买家承担运费金额',
  `seller_express_money` decimal(20,3) NOT NULL DEFAULT '0.000' COMMENT '卖家承担运费金额',
  `adjust_money` decimal(20,3) NOT NULL DEFAULT '0.000' COMMENT '手工调整金额',
  `change_express_money` decimal(20,3) NOT NULL DEFAULT '0.000' COMMENT '换货承担运费金额',
  `return_avg_money` decimal(20,3) NOT NULL DEFAULT '0.000' COMMENT '退单商品均摊总金额',
  `change_avg_money` decimal(20,3) NOT NULL DEFAULT '0.000' COMMENT '换货商品均摊总金额',
  `change_name` varchar(20) NOT NULL DEFAULT '' COMMENT '换货人',
  `change_country` bigint(11) NOT NULL DEFAULT '0' COMMENT '国家-换货',
  `change_province` bigint(11) NOT NULL DEFAULT '0' COMMENT '省-换货',
  `change_city` bigint(11) NOT NULL DEFAULT '0' COMMENT '市-换货',
  `change_district` bigint(11) NOT NULL DEFAULT '0' COMMENT '区-换货',
  `change_street` bigint(11) NOT NULL DEFAULT '0' COMMENT '街道-换货',
  `change_address` varchar(100) NOT NULL DEFAULT '' COMMENT '地址(包含省市区)-换货',
  `change_addr` varchar(100) NOT NULL DEFAULT '' COMMENT '地址(不包含省市区)-换货',
  `change_mobile` varchar(32) NOT NULL DEFAULT '' COMMENT '电话-换货',
  `change_phone` varchar(32) NOT NULL DEFAULT '' COMMENT '固定电话-换货',
  `change_express_code` varchar(20) NOT NULL DEFAULT '' COMMENT '换货配送方式CODE',
  `service_code` varchar(20) NOT NULL DEFAULT '' COMMENT '退单客服',
  `check_time` datetime NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '审核时间',
  `agreed_refund_time` datetime NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '同意退款时间',
  `receive_person` varchar(20) NOT NULL COMMENT '确认收货人',
  `receive_time` datetime NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '验收入库时间',
  `is_lock` tinyint(4) NOT NULL COMMENT '是否锁定',
  `is_lock_person` varchar(20) NOT NULL DEFAULT '' COMMENT '锁定人',
  `create_person` varchar(20) NOT NULL COMMENT '创建人',
  `confirm_person` varchar(20) NOT NULL DEFAULT '' COMMENT '客服确认人',
  `confirm_time` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `finance_confirm_person` varchar(20) NOT NULL DEFAULT '' COMMENT '财务审核人',
  `finance_confirm_time` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `finance_reject_person` varchar(20) NOT NULL DEFAULT '' COMMENT '财务退回人',
  `finance_reject_time` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `finance_reject_reason` varchar(255) NOT NULL DEFAULT '' COMMENT '财务退回原因',
  `agree_refund_person` varchar(20) NOT NULL DEFAULT '' COMMENT '同意退款人',
  `agree_refund_time` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `cancel_person` varchar(20) NOT NULL DEFAULT '' COMMENT '作废人',
  `cancel_time` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `is_settlement` tinyint(4) NOT NULL DEFAULT '0' COMMENT '是否生成结算单 0未生成 1已生成',
  `lastchanged` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后修改时间',
  `buyer_alipay_no` varchar(50) DEFAULT '' COMMENT '买家支付宝账号',
  `finsih_status` tinyint(1) DEFAULT '0' COMMENT '完成状态',
  PRIMARY KEY (`sell_return_id`),
  UNIQUE KEY `idxu_key` (`sell_return_code`) USING BTREE,
  KEY `create_time` (`create_time`),
  KEY `lastchanged` (`lastchanged`),
  KEY `return_name` (`return_name`),
  KEY `stock_date` (`stock_date`),
  KEY `return_mobile` (`return_mobile`),
  KEY `return_order_status` (`return_order_status`),
  KEY `return_shipping_status` (`return_shipping_status`),
  KEY `finance_check_status` (`finance_check_status`),
  KEY `receive_time` (`receive_time`) USING BTREE,
  KEY `agreed_refund_time` (`agreed_refund_time`) USING BTREE,
  KEY `customer_code` (`customer_code`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=211 DEFAULT CHARSET=utf8 COMMENT='销售退单';
