
DROP TABLE IF EXISTS `oms_sell_settlement_record`;
CREATE TABLE `oms_sell_settlement_record` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `sell_settlement_code` varchar(24) NOT NULL,
  `order_attr` tinyint(4) NOT NULL DEFAULT '1' COMMENT '单据性质：1销售 2退货',
  `deal_code` varchar(64) NOT NULL DEFAULT '' COMMENT '平台交易号',
  `sale_channel_code` varchar(20) NOT NULL COMMENT '平台代码',
  `sell_record_code` varchar(20) NOT NULL DEFAULT '' COMMENT '单据编号(订单号)',
  `shop_code` varchar(20) NOT NULL DEFAULT '' COMMENT '商店代码',
  `pay_code` varchar(20) NOT NULL DEFAULT '' COMMENT '支付方式代码',
  `alipay_no` varchar(30) NOT NULL DEFAULT '' COMMENT '支付宝交易号',
  `order_type` tinyint(4) NOT NULL DEFAULT '1' COMMENT '单据类型：1系统单 2 手工单 3复制单 4 合并单 5拆分单 6换货单 100 仅退款 101 退款退货 102 仅退货',
  `settle_type` tinyint(4) NOT NULL DEFAULT '1' COMMENT '结算类别：1商品 2邮费 3补差',
  `point_fee` decimal(10,3) NOT NULL DEFAULT '0.000' COMMENT '积分抵用金额',
  `express_money` decimal(10,3) NOT NULL DEFAULT '0.000' COMMENT '运费',
  `commission_fee` decimal(10,3) NOT NULL DEFAULT '0.000' COMMENT '交易佣金',
  `compensate_money` decimal(20,3) NOT NULL DEFAULT '0.000' COMMENT '赔付金额',
  `num` int(11) NOT NULL DEFAULT '0' COMMENT '商品数量',
  `je` decimal(10,3) NOT NULL DEFAULT '0.000' COMMENT '金额',
  `receiver_name` varchar(20) NOT NULL DEFAULT '' COMMENT '收货人名称',
  `receiver_address` varchar(100) NOT NULL DEFAULT '' COMMENT '收货人地址(包含省市区)',
  `receiver_mobile` varchar(20) NOT NULL DEFAULT '' COMMENT '收货人手机',
  `express_company_code` varchar(20) NOT NULL DEFAULT '' COMMENT '快递公司CODE',
  `express_code` varchar(20) NOT NULL DEFAULT '' COMMENT '配送方式CODE',
  `express_no` varchar(40) NOT NULL DEFAULT '' COMMENT '快递单号',
  `check_accounts_status` tinyint(4) NOT NULL DEFAULT '0' COMMENT '核销状态',
  `check_accounts_time` datetime NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '核销时间',
  `check_accounts_user_code` varchar(20) NOT NULL DEFAULT '' COMMENT '核销人',
  `create_time` datetime NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '添加时间',
  `lastchanged` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后修改时间',
  `remark` varchar(255) NOT NULL DEFAULT '' COMMENT '调整备注',
  `sell_month` date NOT NULL DEFAULT '0000-00-00' COMMENT '业务账期',
  `sell_month_ym` varchar(7) NOT NULL DEFAULT '0000-00' COMMENT '业务账期--仅年月',
  `account_month` date NOT NULL DEFAULT '0000-00-00' COMMENT '财务账期',
  `account_month_ym` varchar(7) NOT NULL DEFAULT '0000-00' COMMENT '财务账期--仅年月',
  PRIMARY KEY (`id`),
  UNIQUE KEY `idxu_code` (`sell_record_code`,`deal_code`,`order_attr`,`settle_type`) USING BTREE,
  KEY `lastchanged` (`lastchanged`) USING BTREE,
  KEY `deal_code` (`deal_code`) USING BTREE,
  KEY `sale_channel_code` (`sale_channel_code`) USING BTREE,
  KEY `sell_record_code` (`sell_record_code`) USING BTREE,
  KEY `alipay_no` (`alipay_no`) USING BTREE,
  KEY `shop_code` (`shop_code`) USING BTREE,
  KEY `order_type` (`order_type`) USING BTREE,
  KEY `express_no` (`express_no`) USING BTREE,
  KEY `create_time` (`create_time`) USING BTREE,
  KEY `pay_code` (`pay_code`),
  KEY `sell_month` (`sell_month`),
  KEY `sell_month_ym` (`sell_month_ym`),
  KEY `account_month` (`account_month`),
  KEY `account_month_ym` (`account_month_ym`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='零售结算订单表';

