DROP TABLE IF EXISTS `oms_sell_record_notice`;
CREATE TABLE `oms_sell_record_notice` (
  `sell_record_id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `sell_record_code` varchar(20) NOT NULL DEFAULT '' COMMENT '单据编号(订单号)',
  `deal_code` varchar(80) NOT NULL DEFAULT '' COMMENT '平台交易号(交易号)',
  `deal_code_list` varchar(200) NOT NULL DEFAULT '' COMMENT '平台交易号列表',
  `sale_channel_code` varchar(20) NOT NULL,
  `alipay_no` varchar(30) NOT NULL DEFAULT '' COMMENT '支付宝交易号',
  `is_handwork` tinyint(4) NOT NULL DEFAULT '0' COMMENT '手工单 0不是 1是',
  `store_code` varchar(20) NOT NULL DEFAULT '' COMMENT '仓库代码',
  `shop_code` varchar(20) NOT NULL DEFAULT '' COMMENT '商店代码',
  `user_code` varchar(20) NOT NULL DEFAULT '' COMMENT '业务员代码',
  `pay_type` varchar(20) NOT NULL DEFAULT 'secured' COMMENT 'secured 担保交易 cod货到付款 nosecured 非担保交易',
  `pay_code` varchar(20) NOT NULL DEFAULT '' COMMENT '支付方式代码',
  `pay_status` tinyint(4) NOT NULL DEFAULT '0' COMMENT '付款状态 0:未付款;1:付款中(部分付款);2:已付款',
  `pay_time` datetime NOT NULL COMMENT '支付时间',
  `customer_code` varchar(20) NOT NULL DEFAULT '' COMMENT '会员代码',
  `buyer_name` varchar(20) NOT NULL DEFAULT '' COMMENT '购买人名称',
  `receiver_name` varchar(20) NOT NULL DEFAULT '' COMMENT '收货人名称',
  `receiver_country` bigint(11) NOT NULL DEFAULT '0' COMMENT '收货人国家',
  `receiver_province` bigint(11) NOT NULL DEFAULT '0' COMMENT '收货人省',
  `receiver_city` bigint(11) NOT NULL DEFAULT '0' COMMENT '收货人市',
  `receiver_district` bigint(11) NOT NULL DEFAULT '0' COMMENT '收货人区',
  `receiver_street` bigint(11) NOT NULL DEFAULT '0' COMMENT '收货人街道',
  `receiver_address` varchar(100) NOT NULL DEFAULT '' COMMENT '收货人地址(包含省市区)',
  `receiver_addr` varchar(100) NOT NULL DEFAULT '' COMMENT '收货人地址(不包含省市区)',
  `receiver_zip_code` varchar(20) NOT NULL DEFAULT '' COMMENT '收货人邮政编码',
  `receiver_mobile` varchar(20) NOT NULL DEFAULT '' COMMENT '收货人手机',
  `receiver_phone` varchar(20) NOT NULL DEFAULT '' COMMENT '收货人固定电话',
  `receiver_email` varchar(40) NOT NULL DEFAULT '' COMMENT '收货人email',
  `express_code` varchar(20) NOT NULL DEFAULT '' COMMENT '配送方式CODE',
  `express_no` varchar(40) NOT NULL DEFAULT '' COMMENT '快递单号',
  `express_data` varchar(2000) NOT NULL DEFAULT '' COMMENT '云栈获取数据',
  `plan_send_time` datetime NOT NULL COMMENT '计划发货时间',
  `goods_num` smallint(11) NOT NULL DEFAULT '0' COMMENT '商品数量',
  `sku_num` tinyint(11) NOT NULL DEFAULT '0' COMMENT 'sku种类数量',
  `goods_weigh` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '商品总重量-克',
  `real_weigh` decimal(20,2) DEFAULT '0.00' COMMENT '实际总重量',
  `weigh_express_money` decimal(20,2) DEFAULT '0.00' COMMENT '称重后计算的快递费用',
  `weigh_time` datetime DEFAULT NULL COMMENT '称重时间',
  `buyer_remark` varchar(255) NOT NULL DEFAULT '' COMMENT '买家留言',
  `seller_remark` varchar(255) NOT NULL DEFAULT '' COMMENT '商家备注',
  `seller_flag` tinyint(4) NOT NULL DEFAULT '0' COMMENT '淘宝订单的旗帜',
  `order_remark` varchar(255) NOT NULL DEFAULT '' COMMENT '订单备注',
  `store_remark` varchar(255) NOT NULL DEFAULT '' COMMENT '仓库留言',
  `order_money` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '订单总额,商品总额+运费+配送手续费',
  `goods_money` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '商品总额',
  `express_money` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '运费',
  `delivery_money` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '配送手续费',
  `payable_money` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '订单应付款,商品均摊总金额+运费',
  `paid_money` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '订单已付款,已支付状态下与应付款相等',
  `invoice_type` varchar(20) NOT NULL DEFAULT '' COMMENT '发票类型',
  `invoice_title` varchar(100) NOT NULL DEFAULT '' COMMENT '发票抬头',
  `invoice_content` varchar(255) NOT NULL DEFAULT '' COMMENT '发票内容',
  `invoice_money` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '发票金额',
  `invoice_status` tinyint(4) NOT NULL DEFAULT '0' COMMENT '发票状态：0没有发票，1未审核状态，2已审核状态，3已开票状态,4已作废状态',
  `create_time` datetime NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '转入系统时间',
  `record_time` datetime NOT NULL COMMENT '下单时间',
  `record_date` date NOT NULL DEFAULT '0000-00-00' COMMENT '业务日期',
  `is_lock` tinyint(4) NOT NULL DEFAULT '0' COMMENT '是否锁定 0不是 1是',
  `is_change_record` tinyint(4) NOT NULL DEFAULT '0' COMMENT '是否换货单 0不是 1是',
  `change_record_from` varchar(20) NOT NULL DEFAULT '' COMMENT '换货单的原单号',
  `is_split` tinyint(4) NOT NULL DEFAULT '0' COMMENT '是否为被拆分订单 0:不是 1：是',
  `is_split_new` tinyint(4) NOT NULL DEFAULT '0' COMMENT '是否为拆分产生的新订单 0:不是 1是',
  `split_order` varchar(20) NOT NULL DEFAULT '0' COMMENT '被拆分的订单号（is_split_new=1的时候有效）',
  `split_new_orders` varchar(255) NOT NULL DEFAULT '' COMMENT '拆分之后的新订单号字符串，逗号分隔（is_split=1的时候有效）',
  `is_combine` tinyint(4) NOT NULL DEFAULT '0' COMMENT '是否被合并 0:不是 1：是',
  `is_combine_new` tinyint(4) NOT NULL DEFAULT '0' COMMENT '是否为合并产生的新订单 0:不是 1：是',
  `combine_orders` varchar(255) NOT NULL DEFAULT '' COMMENT '被合并的订单号字符串，逗号分隔（is_combine_new=1的时候有效）',
  `combine_new_order` varchar(20) NOT NULL DEFAULT '0' COMMENT '合并之后的新订单号（is_combine=1的时候有效）',
  `is_copy` tinyint(4) NOT NULL DEFAULT '0' COMMENT '是否复制单 0:不是 1：是',
  `is_copy_from` varchar(20) NOT NULL DEFAULT '0' COMMENT '复制来源订单号',
  `is_wap` tinyint(1) NOT NULL COMMENT '是否移动端订单',
  `is_jhs` tinyint(1) NOT NULL COMMENT '是否聚划算',
  `point_fee` decimal(10,2) NOT NULL COMMENT '付款-积分',
  `alipay_point_fee` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '付款-集分宝',
  `coupon_fee` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '付款-抵用金额',
  `yfx_fee` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '运费险',
  `change_sell_record` varchar(20) NOT NULL DEFAULT '' COMMENT '换货单原单号',
  `is_print_sellrecord` tinyint(3) NOT NULL DEFAULT '0' COMMENT '是否打印订单',
  `is_print_express` tinyint(3) NOT NULL DEFAULT '0' COMMENT '是否打印快递',
  `is_fenxiao` tinyint(3) NOT NULL DEFAULT '0',
  `is_notice_time` datetime NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '通知配货时间',
  `check_time` datetime NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '确认时间',
  `lastchanged` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后修改时间',
  `is_buyer_remark` tinyint(4) DEFAULT '0' COMMENT '是否有买家留言',
  `is_seller_remark` tinyint(4) DEFAULT '0' COMMENT '是否有卖家留言',
  `is_rush` tinyint(4) DEFAULT '0' COMMENT '是否是急单',
  `confirm_person` varchar(20) NOT NULL DEFAULT '' COMMENT '确认人',
  `notice_person` varchar(20) NOT NULL DEFAULT '' COMMENT '通知配货人',
  `fenxiao_id` int(11) DEFAULT NULL COMMENT '分销商id',
  `fenxiao_name` varchar(200) DEFAULT '' COMMENT '分销商名称',
  `sku_all` varchar(256) DEFAULT '',
  `sku_all_num` varchar(256) DEFAULT '',
  PRIMARY KEY (`sell_record_id`),
  UNIQUE KEY `idxu_record_code` (`sell_record_code`) USING BTREE,
  UNIQUE KEY `idxu_deal_code` (`deal_code`) USING BTREE,
  KEY `lastchanged` (`lastchanged`) USING BTREE,
  KEY `pay_code` (`pay_code`) USING BTREE,
  KEY `customer_code` (`customer_code`) USING BTREE,
  KEY `record_time` (`record_time`) USING BTREE,
  KEY `pay_time` (`pay_time`) USING BTREE,
  KEY `shop_code` (`shop_code`) USING BTREE,
  KEY `sku_num` (`sku_num`) USING BTREE,
  KEY `is_notice_time` (`is_notice_time`) USING BTREE,
  KEY `plan_send_time` (`plan_send_time`) USING BTREE,
  KEY `sku_all` (`sku_all`(255)) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='通知配货订单';
