DROP TABLE IF EXISTS `oms_sell_record_cz`;
CREATE TABLE `oms_sell_record_cz` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `sell_record_code` varchar(20) NOT NULL DEFAULT '' COMMENT '单据编号(订单号)',
  `deal_code` varchar(80) NOT NULL DEFAULT '' COMMENT '平台交易号(交易号)',
  `deal_code_list` varchar(500) NOT NULL DEFAULT '' COMMENT '平台交易号列表',
  `sale_channel_code` varchar(20) NOT NULL,
  `alipay_no` varchar(30) NOT NULL DEFAULT '' COMMENT '支付宝交易号',
  `store_code` varchar(20) NOT NULL DEFAULT '' COMMENT '仓库代码',
  `shop_code` varchar(20) NOT NULL DEFAULT '' COMMENT '商店代码',
  `pay_type` varchar(20) NOT NULL DEFAULT 'secured' COMMENT 'secured 担保交易 cod货到付款 nosecured 非担保交易',
  `pay_code` varchar(20) NOT NULL DEFAULT '' COMMENT '支付方式代码',
  `pay_status` tinyint(4) NOT NULL DEFAULT '0' COMMENT '付款状态 0:未付款;1:付款中(部分付款);2:已付款',
  `pay_time` datetime NOT NULL COMMENT '支付时间',
  `customer_code` varchar(20) NOT NULL DEFAULT '' COMMENT '会员代码',
  `buyer_name` varchar(20) NOT NULL DEFAULT '' COMMENT '购买人名称',
  `receiver_name` varchar(20) NOT NULL DEFAULT '' COMMENT '收货人名称',
  `receiver_country` bigint(11) NOT NULL DEFAULT '0' COMMENT '收货人国家',
  `receiver_province` bigint(11) NOT NULL DEFAULT '0' COMMENT '收货人省',
  `receiver_city` bigint(11) NOT NULL DEFAULT '0' COMMENT '收货人市',
  `receiver_district` bigint(11) NOT NULL DEFAULT '0' COMMENT '收货人区',
  `receiver_street` bigint(11) NOT NULL DEFAULT '0' COMMENT '收货人街道',
  `receiver_address` varchar(100) NOT NULL DEFAULT '' COMMENT '收货人地址(包含省市区)',
  `receiver_addr` varchar(100) NOT NULL DEFAULT '' COMMENT '收货人地址(不包含省市区)',
  `receiver_zip_code` varchar(20) NOT NULL DEFAULT '' COMMENT '收货人邮政编码',
  `receiver_mobile` varchar(20) NOT NULL DEFAULT '' COMMENT '收货人手机',
  `receiver_phone` varchar(20) NOT NULL DEFAULT '' COMMENT '收货人固定电话',
  `receiver_email` varchar(40) NOT NULL DEFAULT '' COMMENT '收货人email',
  `express_code` varchar(20) NOT NULL DEFAULT '' COMMENT '配送方式CODE',
  `express_no` varchar(40) NOT NULL DEFAULT '' COMMENT '快递单号',
  `goods_weigh` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '商品总重量-克',
  `real_weigh` decimal(10,3) DEFAULT '0.000' COMMENT '实际总重量-千克',
  `weigh_express_money` decimal(10,2) DEFAULT '0.00' COMMENT '称重后计算的快递费用',
  `weigh_time` datetime DEFAULT NULL COMMENT '称重时间',
  `weigh_person` varchar(20) NOT NULL DEFAULT '' COMMENT '称重人',
  `order_money` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '订单总额,商品总额+运费+配送手续费',
  `goods_money` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '商品总额',
  `express_money` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '运费',
  `delivery_money` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '配送手续费',
  `payable_money` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '订单应付款,商品均摊总金额+运费',
  `paid_money` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '订单已付款,已支付状态下与应付款相等',
  `create_time` datetime NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '转入系统时间',
  `record_time` datetime NOT NULL COMMENT '下单时间',
  `delivery_time` datetime NOT NULL COMMENT '发货时间',
  `delivery_date` date NOT NULL DEFAULT '0000-00-00' COMMENT '发货日期',
  `record_date` date NOT NULL DEFAULT '0000-00-00' COMMENT '业务日期',
  `is_notice_time` datetime NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '通知配货时间',
  `check_time` datetime NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '确认时间',
  `lastchanged` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后修改时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `express_no` (`express_no`),
  KEY `idxu_record_code` (`sell_record_code`) USING BTREE,
  KEY `idxu_deal_code` (`deal_code`),
  KEY `record_time` (`record_time`),
  KEY `delivery_time` (`delivery_time`),
  KEY `pay_time` (`pay_time`),
  KEY `weigh_time` (`weigh_time`),
  KEY `express_code` (`express_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='称重订单';
