DROP TABLE IF EXISTS `pur_purchaser_record`;
CREATE TABLE `pur_purchaser_record` (
  `purchaser_record_id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `record_code` varchar(64) DEFAULT '' COMMENT '单据编号',
  `init_code` varchar(128) DEFAULT '' COMMENT '原单号',
  `supplier_code` varchar(128) DEFAULT '' COMMENT '供应商代码',
  `record_type_code` varchar(128) DEFAULT '' COMMENT '入库类型',
  `user_code` varchar(64) DEFAULT '' COMMENT '业务员代码',
  `enter_time` datetime DEFAULT NULL COMMENT '入库日期',
  `record_time` date DEFAULT '0000-00-00' COMMENT '业务时间',
  `order_time` DATETIME DEFAULT NULL COMMENT '下单日期',
  `is_pre_sale` tinyint(3) DEFAULT '0' COMMENT '1预售，0非预售',
  `is_check_and_accept` int(4) DEFAULT '0' COMMENT '0未入库 1入库',
  `is_check` int(4) DEFAULT '0' COMMENT '0未确认  1确认',
  `store_code` varchar(128) DEFAULT '' COMMENT '仓库代码',
  `rebate` decimal(4,3) DEFAULT '1.000' COMMENT '折扣',
  `status` int(4) DEFAULT '0' COMMENT '订单状态',
  `remark` varchar(255) DEFAULT '' COMMENT '备注',
  `is_lock` tinyint(3) DEFAULT '0' COMMENT '0未锁定，1锁定',
  `is_lock_time` int(11) DEFAULT NULL,
  `is_add_person` varchar(64) DEFAULT '' COMMENT '添加人',
  `is_add_time` datetime DEFAULT NULL COMMENT '添加时间',
  `lastchanged` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后修改时间',
  `relation_code` VARCHAR(128) DEFAULT '' COMMENT '关联单号',
  PRIMARY KEY (`purchaser_record_id`),
  UNIQUE KEY `_key` (`record_code`) USING BTREE,
  KEY `ix_record_time` (`record_time`) USING BTREE,
  KEY `ix_is_check_and_accept` (`is_check_and_accept`) USING BTREE,
  KEY `ix_store_code` (`store_code`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8 COMMENT='商品采购入库单';