DROP TABLE IF EXISTS `pur_order_record`;
CREATE TABLE `pur_order_record` (
  `order_record_id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `record_code` VARCHAR(64) DEFAULT '' COMMENT '单据编号',
  `supplier_code` VARCHAR(128) DEFAULT '' COMMENT '供应商代码',
  `user_code` VARCHAR(64) DEFAULT '' COMMENT '业务员代码',
 `record_time` date DEFAULT '0000-00-00' COMMENT '业务时间',
  `store_code` VARCHAR(128) DEFAULT '' COMMENT '仓库代码',
  `rebate` DECIMAL(4,3) DEFAULT '1.000' COMMENT '折扣',
  `init_code` VARCHAR(128) DEFAULT '' COMMENT '原单号',
  `order_time` DATETIME DEFAULT NULL COMMENT '下单日期',
  `in_time` DATETIME DEFAULT NULL COMMENT '入库期限',
  `relation_code` VARCHAR(128) DEFAULT '' COMMENT '关联单号',	
  `brand_code` VARCHAR(128) DEFAULT '' COMMENT '品牌代码',
  `num` INT(11) DEFAULT '0' COMMENT '数量',
  `finish_num` INT(11) DEFAULT '0' COMMENT '完成数量',
  `money` decimal(20,3) DEFAULT '0.000' COMMENT '金额',
  `is_check` INT(4) DEFAULT '0' COMMENT '0未审核 1审核',
  `is_execute` INT(4) DEFAULT '0' COMMENT '0未执行 1执行',
  `is_finish` INT(4) DEFAULT '0' COMMENT '0未完成 1完成',
  `is_add_person` VARCHAR(64) DEFAULT '' COMMENT '添加人',
  `is_add_time` DATETIME DEFAULT NULL COMMENT '添加时间',
  `is_finish_person` VARCHAR(64) DEFAULT '' COMMENT '完成人',
  `is_finish_time` DATETIME DEFAULT NULL COMMENT '完成时间',
  `remark` VARCHAR(255) DEFAULT '' COMMENT '备注',
  `lastchanged` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后修改时间',
  `pre_sale` INT(4) DEFAULT '0' COMMENT '0未预售 1预售',
  `pur_type_code` VARCHAR(100) DEFAULT '' COMMENT '采购类型代码',
  PRIMARY KEY (`order_record_id`)
) ENGINE=INNODB DEFAULT CHARSET=utf8 COMMENT='商品采购订单';