DROP TABLE IF EXISTS `pur_return_record`;
CREATE TABLE `pur_return_record` (
  `return_record_id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `record_code` varchar(64) DEFAULT '' COMMENT '单据编号',
  `record_type_code` varchar(128) DEFAULT '' COMMENT '单据类型代码',
  `supplier_code` varchar(128) DEFAULT '' COMMENT '供应商代码',
  `org_code` varchar(128) DEFAULT '000' COMMENT '渠道代码',
  `user_code` varchar(64) DEFAULT '' COMMENT '业务员代码',
  `record_time` date DEFAULT '0000-00-00' COMMENT '业务时间',
  `order_time` datetime DEFAULT NULL COMMENT '下单日期',
  `price_type` varchar(64) DEFAULT 'buy_price' COMMENT '价格类型',
  `store_code` varchar(128) DEFAULT '' COMMENT '仓库代码',
  `rebate` decimal(4,3) DEFAULT '1.000' COMMENT '折扣',
  `relation_code` varchar(128) DEFAULT '' COMMENT '关联单号',
  `init_code` varchar(128) DEFAULT '' COMMENT '原单号',
  `refer_time` datetime DEFAULT NULL COMMENT '交货时间',
  `pay_time` datetime DEFAULT NULL COMMENT '付款期限',
  `num` int(11) DEFAULT '0' COMMENT '数量',
  `money` decimal(20,3) DEFAULT '0.000' COMMENT '金额',
  `adjust_money` decimal(20,3) DEFAULT '0.000' COMMENT '折让金额',
  `pay_money` decimal(20,3) DEFAULT '0.000' COMMENT '付款金额',
  `is_check` int(4) DEFAULT '0' COMMENT '0未确认 1确认',
  `is_cancel` int(4) DEFAULT '0' COMMENT '0未作废 1作废',
  `is_store_out` int(4) DEFAULT '0' COMMENT '0未出库 1出库',
  `is_keep_accounts` int(4) DEFAULT '0' COMMENT '0未记账 1记账',
  `is_settlement` int(4) DEFAULT '0' COMMENT '0未结算 1结算',
  `remark` varchar(255) DEFAULT '' COMMENT '备注',
  `lastchanged` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后修改时间',
  `enotice_num` int(11) DEFAULT '0' COMMENT '通知数量',
  PRIMARY KEY (`return_record_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='商品采购退货单';