  DROP TABLE IF EXISTS `shop_data_analysis`;
  CREATE TABLE `shop_data_analysis` (
    `shop_report_id` int(11) unsigned NOT NULL AUTO_INCREMENT,
    `summary_date` date NOT NULL  DEFAULT '0000-00-00' COMMENT '汇总日期',
    `sale_channel_code` varchar(20) NOT NULL DEFAULT '' COMMENT '平台代码',
    `shop_code` varchar(20) NOT NULL DEFAULT '' COMMENT '商店代码',
    `order_total_num` smallint(5) NOT NULL DEFAULT '0' COMMENT '订单总量',
    `goods_total_num` int(10) NOT NULL DEFAULT '0' COMMENT '商品总量',
    `sale_total_money` decimal(20,2) DEFAULT '0.00'  COMMENT '总销售金额',
    `shipping_fee` decimal(10,2) DEFAULT '0.00' COMMENT '运费',
    `send_order_num` smallint(10) NOT NULL DEFAULT '0' COMMENT '已发货订单量',
    `send_goods_num` int(10) NOT NULL DEFAULT '0' COMMENT '已发货商品量',
    `send_sell_total_price` decimal(20,2) DEFAULT '0.00' COMMENT '已发货总吊牌价',
    `send_avg_total_money` decimal(20,2) DEFAULT '0.00' COMMENT '已发货总销售金额',
    `send_goods_percentage` float(4,2) DEFAULT '0.00' COMMENT '发货比例',
    `no_send_order_num` smallint(5) NOT NULL DEFAULT '0' COMMENT '未发货订单量',
    `no_send_goods_distinct_num` smallint(5) NOT NULL DEFAULT '0' COMMENT '未发货商品种类量',
    `no_send_goods_num` int(10) NOT NULL DEFAULT '0' COMMENT '未发货商品量',
    `no_send_sell_total_price` decimal(20,2) DEFAULT '0.00' COMMENT '未发货总吊牌价',
    `no_send_avg_total_money` decimal(20,2) DEFAULT '0.00' COMMENT '未发货总销售金额',
    `no_send_goods_percentage` float(4,2) DEFAULT '0.00' COMMENT '未发货比例',
    `remaining_un_send_order_num` smallint(5) NOT NULL DEFAULT '0' COMMENT '剩余未发货订单量',
    `short_order_num` smallint(5) NOT NULL DEFAULT '0' COMMENT '缺货订单量',
    `short_goods_num` int(10) NOT NULL DEFAULT '0' COMMENT '缺货商品量',
    `short_sell_total_price` decimal(20,2) DEFAULT '0.00' COMMENT '缺货总吊牌价',
    `short_avg_total_money` decimal(20,2) DEFAULT '0.00' COMMENT '缺货总销售金额',
    `remaning_short_order_num` smallint(5) NOT NULL DEFAULT '0' COMMENT '剩余缺货订单量',
    `cancel_order_num` smallint(5) NOT NULL DEFAULT '0' COMMENT '已取消订单量',
    `cancel_sell_total_price` decimal(20,2) DEFAULT '0.00' COMMENT '已取消总吊牌价',
    `cancel_avg_total_money` decimal(20,2) DEFAULT '0.00' COMMENT '已取消总销售金额',
    `cancel_goods_percentage` float(4,2) DEFAULT '0.00' COMMENT '取消比例',
    `return_order_num` smallint(5) NOT NULL DEFAULT '0' COMMENT '退货订单量',
    `return_goods_num` int(10) NOT NULL DEFAULT '0' COMMENT '退货商品量',
    `return_sell_total_price` decimal(20,2) DEFAULT '0.00' COMMENT '退货总吊牌价',
    `return_avg_total_money` decimal(20,2) DEFAULT '0.00' COMMENT '退货总销售金额',
    PRIMARY KEY (`shop_report_id`),
    UNIQUE KEY `summary_date_shop_code` (`summary_date`,`shop_code`),
    KEY `sale_channel_code` (`sale_channel_code`)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='店铺运营数据分析';