DROP TABLE IF EXISTS `stm_store_shift_record_detail`;
CREATE TABLE `stm_store_shift_record_detail` (
  `shift_record_detail_id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `pid` INT(11) DEFAULT '0',
  `mid` INT(11) DEFAULT '0',
  `goods_id` INT(11) DEFAULT '0' COMMENT 'goods_id',
  `goods_code` VARCHAR(64) DEFAULT '' COMMENT '商品代码',
  `spec1_id` INT(11) DEFAULT '0' COMMENT 'color_id',
  `spec1_code` VARCHAR(64) DEFAULT '' COMMENT '颜色代码',
  `spec2_id` INT(11) DEFAULT '0' COMMENT 'size_id',
  `spec2_code` VARCHAR(64) DEFAULT '' COMMENT '尺码代码',
  `sku` VARCHAR(128) DEFAULT '' COMMENT 'sku',
  `refer_price` DECIMAL(20,3) DEFAULT '0.00' COMMENT '参考价',
  `price` DECIMAL(20,3) DEFAULT '0.00' COMMENT '单价',
  `rebate` DECIMAL(4,3) DEFAULT '1.00' COMMENT '折扣',
  `out_money` DECIMAL(20,3) DEFAULT '0.00' COMMENT '移出金额',
  `in_money` DECIMAL(20,3) DEFAULT '0.00' COMMENT '移入金额',
  `out_num` INT(11) DEFAULT '0' COMMENT '移出数量',
  `in_num` INT(11) DEFAULT '0' COMMENT '移入数量',
  `scan_num` INT(11) DEFAULT '0' COMMENT '扫描数量',
  `cost_price` DECIMAL(20,3) DEFAULT '0.00' COMMENT '成本单',
  `cost_price_forecast` DECIMAL(20,3) DEFAULT '0.00' COMMENT '预估成本单',
  `remark` VARCHAR(255) DEFAULT '' COMMENT '备注',
  `lastchanged` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后修改时间',
  `is_fetch` INT(4) DEFAULT '0' COMMENT '0：正常 1：待处理',
  `record_code` VARCHAR(128) DEFAULT NULL COMMENT '单据编号',
  `trd_id` VARCHAR(64) DEFAULT '' COMMENT '第三方来源GUID',
  `trd_type` VARCHAR(32) DEFAULT '' COMMENT '第三方来源类型:erp/3000/efast',
  `trd_time` VARCHAR(64) DEFAULT '' COMMENT '第三方导入或者更新的时间',
   UNIQUE KEY `record_sku` (`record_code`,`sku`),
  PRIMARY KEY (`shift_record_detail_id`)
) ENGINE=INNODB DEFAULT CHARSET=utf8 COMMENT='移仓单明细表';
