DROP TABLE IF EXISTS `wbm_notice_record`;
CREATE TABLE `wbm_notice_record` (
  `notice_record_id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `record_code` VARCHAR(64) DEFAULT '' COMMENT '单据编号',
  `record_type_code` VARCHAR(128) DEFAULT '' COMMENT '单据类型代码',
  `distributor_code` VARCHAR(128) DEFAULT '' COMMENT '客户，分销商代码',
  `org_code` VARCHAR(128) DEFAULT '000' COMMENT '渠道代码',
  `user_code` VARCHAR(64) DEFAULT '' COMMENT '业务员代码',
  `order_time` DATETIME DEFAULT NULL COMMENT '下单时间',
  `record_time` DATETIME DEFAULT NULL COMMENT '业务时间',
  `store_code` VARCHAR(128) DEFAULT '' COMMENT '仓库代码',
  `rebate` DECIMAL(4,3) DEFAULT '1.000' COMMENT '折扣',
  `init_code` VARCHAR(128) DEFAULT '' COMMENT '原单号',
  `out_time` DATETIME DEFAULT NULL COMMENT '出库期限',
  `relation_code` VARCHAR(128) DEFAULT '' COMMENT '关联单号',	
  `brand_code` VARCHAR(128) DEFAULT '' COMMENT '品牌代码',
  `num` INT(11) DEFAULT '0' COMMENT '数量',
  `finish_num` INT(11) DEFAULT '0' COMMENT '完成数量',
  `money` decimal(20,3) DEFAULT '0.000' COMMENT '金额',
  `is_sure` INT(4) DEFAULT '0' COMMENT '0未确认 1确认',
  `is_execute` INT(4) DEFAULT '0' COMMENT '0未执行 1执行',
  `is_stop` INT(4) DEFAULT '0' COMMENT '0未终止 1终止',
  `is_finish` INT(4) DEFAULT '0' COMMENT '0未完成 1完成',
  `is_add_person` VARCHAR(64) DEFAULT '' COMMENT '添加人',
  `is_add_time` DATETIME DEFAULT NULL COMMENT '添加时间',
  `is_finish_person` VARCHAR(64) DEFAULT '' COMMENT '完成人',
  `is_finish_time` DATETIME DEFAULT NULL COMMENT '完成时间',
  `remark` VARCHAR(255) DEFAULT '' COMMENT '备注',
  `lastchanged` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后修改时间',
  `is_relation` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否绑定档期',
 
  PRIMARY KEY (`notice_record_id`),
  KEY (`is_relation`)
) ENGINE=INNODB DEFAULT CHARSET=utf8 COMMENT='商品批发通知单';