DROP TABLE IF EXISTS `wbm_store_out_record`;
CREATE TABLE `wbm_store_out_record` (
  `store_out_record_id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `record_code` varchar(64) DEFAULT '' COMMENT '单据编号',
  `record_type_code` varchar(128) DEFAULT '' COMMENT '单据类型代码',
  `distributor_code` varchar(128) DEFAULT '' COMMENT '客户，分销商代码',
  `org_code` varchar(128) DEFAULT '000' COMMENT '渠道代码',
  `user_code` varchar(64) DEFAULT '' COMMENT '业务员代码',
  `order_time` datetime DEFAULT NULL COMMENT '下单时间',
  `record_time` date DEFAULT NULL COMMENT '业务时间',
  `pifa_type` varchar(64) DEFAULT '' COMMENT '批发类型',
  `store_code` varchar(128) DEFAULT '' COMMENT '仓库代码',
  `rebate` decimal(4,3) DEFAULT '1.000' COMMENT '折扣',
  `relation_code` varchar(128) DEFAULT '' COMMENT '关联单号',
  `init_code` varchar(128) DEFAULT '' COMMENT '原单号',
  `refer_time` datetime DEFAULT NULL COMMENT '交货时间',
  `pay_time` datetime DEFAULT NULL COMMENT '付款期限',
  `brand_code` varchar(128) DEFAULT '' COMMENT '品牌代码',
  `bank_code` varchar(128) DEFAULT '' COMMENT '银行账号代码',
  `num` int(11) DEFAULT '0' COMMENT '数量',
  `money` decimal(20,3) DEFAULT '0.000' COMMENT '金额',
  `adjust_money` decimal(20,3) DEFAULT '0.000' COMMENT '折让金额',
  `pay_money` decimal(20,3) DEFAULT '0.000' COMMENT '付款金额',
  `is_sure` int(4) DEFAULT '0' COMMENT '0未确认 1确认',
  `is_cancel` int(4) DEFAULT '0' COMMENT '0未作废 1作废',
  `is_store_out` int(4) DEFAULT '0' COMMENT '0未出库 1出库',
  `is_keep_accounts` int(4) DEFAULT '0' COMMENT '0未记账 1记账',
  `is_settlement` int(4) DEFAULT '0' COMMENT '0未结算 1结算',
  `is_add_person` varchar(64) DEFAULT '' COMMENT '添加人',
  `is_add_time` datetime DEFAULT NULL COMMENT '添加时间',
  `is_edit_person` varchar(64) DEFAULT '' COMMENT '修改人',
  `is_edit_time` datetime DEFAULT NULL COMMENT '修改时间',
  `is_sure_person` varchar(64) DEFAULT '' COMMENT '确认人',
  `is_sure_time` datetime DEFAULT NULL COMMENT '确认时间',
  `is_cancel_person` varchar(64) DEFAULT '' COMMENT '作废人',
  `is_cancel_time` datetime DEFAULT NULL COMMENT '作废时间',
  `is_store_out_person` varchar(64) DEFAULT '' COMMENT '出库人',
  `is_store_out_time` datetime DEFAULT NULL COMMENT '出库时间',
  `is_keep_accounts_person` varchar(64) DEFAULT '' COMMENT '记账人',
  `is_keep_accounts_time` datetime DEFAULT NULL COMMENT '记账时间',
  `is_settlement_person` varchar(64) DEFAULT '' COMMENT '结算人',
  `is_settlement_time` datetime DEFAULT NULL COMMENT '结算时间',
  `is_month_settlement` int(4) DEFAULT '0' COMMENT '0未月结 1月结',
  `remark` varchar(255) DEFAULT '' COMMENT '备注',
  `address` varchar(100) NOT NULL DEFAULT '' COMMENT '地址(包含省市区)',
  `lastchanged` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后修改时间',
  `is_fetch` int(4) DEFAULT '0' COMMENT '0：正常 1：待处理',
  `trd_id` varchar(64) DEFAULT '' COMMENT '第三方来源GUID',
  `trd_type` varchar(32) DEFAULT '' COMMENT '第三方来源类型:erp/3000/efast',
  `trd_time` varchar(64) DEFAULT '' COMMENT '第三方导入或者更新的时间',
  `trd_upload` tinyint(4) DEFAULT '0' COMMENT '第三方上传标识位: 0未上传, 1已上传等待处理, 2 上传处理成功 3上传处理失败',
  `enotice_num` int(11) DEFAULT '0' COMMENT '通知数量',
  `name` varchar(20) NOT NULL DEFAULT '' COMMENT '联系人',
  `tel` varchar(20) NOT NULL DEFAULT '' COMMENT '电话',
  `express` varchar(20) NOT NULL DEFAULT '' COMMENT '快递单号',
  `express_money` decimal(20,2) DEFAULT '0.00' COMMENT '运费',
  `express_code` varchar(20) NOT NULL DEFAULT '' COMMENT '配送方式CODE',
  PRIMARY KEY (`store_out_record_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='批发销货单';