DROP TABLE IF EXISTS `wms_oms_trade`;
CREATE TABLE `wms_oms_trade` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '表的主键,自增',
  `in_out_flag` tinyint(4) NOT NULL DEFAULT '0' COMMENT 'wms单据出入库类型 1出库 2入库 移仓单根据这个标识区分出入库',
  `record_code` varchar(20) NOT NULL DEFAULT '' COMMENT '订单号',
  `record_type` varchar(20) NOT NULL DEFAULT '' COMMENT '订单类型',
  `order_status` varchar(20) NOT NULL DEFAULT '' COMMENT 'wms订单状态',
  `upload_request_time` datetime NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '上传请求时间',
  `upload_request_flag` tinyint(4) NOT NULL DEFAULT '0' COMMENT '上传请示是否发送成功的标识，10 表示上传成功',
  `upload_response_time` datetime NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT 'wms回传订单是否接单的时间',
  `upload_response_flag` tinyint(4) NOT NULL DEFAULT '0' COMMENT 'wms回传订单是否接单，0 没回传 10 表示接单成功 20 表示接单失败 30表示主动查询接单成功',
  `upload_response_err_msg` varchar(100) NOT NULL DEFAULT '' COMMENT 'wms回传接单失败的信息',
  `cancel_request_time` datetime NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '取消请求发出时间',
  `cancel_request_flag` tinyint(1) NOT NULL DEFAULT '0' COMMENT '取消请求是否发送成功的标识，0表示没有取消请求 10表示是取消请求发出成功',
  `cancel_response_time` datetime NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT 'wms回传取消订单是否成功的时间',
  `cancel_response_flag` tinyint(4) NOT NULL DEFAULT '0' COMMENT 'wms回传取消订单是否成功，0 没回传 10 表示取消成功 20 表示取消失败 30表示主动查询取消成功',
  `cancel_response_err_msg` varchar(100) NOT NULL DEFAULT '' COMMENT 'wms回传取消订单失败的信息',
  `process_time` datetime NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '处理WMS回传信息的时间',
  `process_flag` tinyint(4) NOT NULL DEFAULT '0' COMMENT '处理WMS回传信息成功的标识, 0 表示待处理 10 解析成功 20 处理出错 30 处理结束',
  `process_err_msg` varchar(100) NOT NULL DEFAULT '' COMMENT '处理WMS回传信息失败的原因',
  `wms_order_from_flag` tinyint(4) NOT NULL DEFAULT '0' COMMENT 'WMS回传信息来源, 10 来源于回传 20 来源于查询接口',
  `process_fail_num` tinyint(4) DEFAULT '0' COMMENT '处理失败次数',
  `express_code` varchar(20) NOT NULL DEFAULT '' COMMENT 'wms发货的物流公司CODE',
  `express_no` varchar(30) NOT NULL DEFAULT '' COMMENT 'wms发货的物流单号',
  `order_weight` decimal(20,3) NOT NULL DEFAULT '0.000' COMMENT '订单重量',
  `wms_order_time` int(11) NOT NULL COMMENT 'wms 发/收货的时间',
  `wms_order_flow_end_flag` tinyint(4) NOT NULL DEFAULT '0' COMMENT 'wms订单流转结束 0 未收发货 1已收发货',
  `efast_store_code` varchar(20) NOT NULL DEFAULT '' COMMENT 'efast仓库代码',
  `wms_store_code` varchar(20) NOT NULL DEFAULT '' COMMENT 'wms仓库代码',
  `api_product` varchar(20) NOT NULL DEFAULT '' COMMENT '对接产品名称 iwms bswl',
  `wms_record_code` varchar(50) NOT NULL DEFAULT '' COMMENT 'wms单据编号',
  `sale_channel_code` varchar(20) NOT NULL DEFAULT '' COMMENT '销售平台代码',
  `shop_code` varchar(20) NOT NULL DEFAULT '' COMMENT '店铺代码',
  `deal_code` varchar(100) NOT NULL DEFAULT '' COMMENT '订单交易号',
  `buyer_name` varchar(10) NOT NULL DEFAULT '' COMMENT '买家昵称',
  `json_data` text NOT NULL COMMENT '订单/退单 主信息数据',
  `wms_result_md5` varchar(32) NOT NULL DEFAULT '' COMMENT 'wms收发货结果的MD5值',
  `create_time` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '创建时间',
  `lastchanged` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后修改时间',
  `cancel_flag` tinyint(1) NOT NULL DEFAULT '0' COMMENT '1取消，0未取消',
  `new_record_code` varchar(20) NOT NULL DEFAULT '' COMMENT '新单号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_order_sn_type` (`record_code`,`record_type`) USING BTREE,
  KEY `record_type` (`record_type`) USING BTREE,
  KEY `order_status` (`order_status`) USING BTREE,
  KEY `upload_request_time` (`upload_request_time`) USING BTREE,
  KEY `upload_request_flag` (`upload_request_flag`) USING BTREE,
  KEY `upload_response_time` (`upload_response_time`) USING BTREE,
  KEY `upload_response_flag` (`upload_response_flag`) USING BTREE,
  KEY `cancel_request_time` (`cancel_request_time`) USING BTREE,
  KEY `cancel_request_flag` (`cancel_request_flag`) USING BTREE,
  KEY `cancel_response_time` (`cancel_response_time`) USING BTREE,
  KEY `cancel_response_flag` (`cancel_response_flag`) USING BTREE,
  KEY `process_time` (`process_time`) USING BTREE,
  KEY `process_flag` (`process_flag`) USING BTREE,
  KEY `wms_order_from_flag` (`wms_order_from_flag`) USING BTREE,
  KEY `express_no` (`express_no`) USING BTREE,
  KEY `wms_order_time` (`wms_order_time`) USING BTREE,
  KEY `wms_order_flow_end_flag` (`wms_order_flow_end_flag`) USING BTREE,
  KEY `in_out_flag` (`in_out_flag`) USING BTREE,
  KEY `record_code` (`record_code`) USING BTREE,
  KEY `efast_store_code` (`efast_store_code`) USING BTREE,
  KEY `wms_store_code` (`wms_store_code`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;