<?php
return array(
    'taobao' =>array('TB','淘宝'),
    'tmall' =>  array('TM','天猫'),
    'jingdong' =>   array('JD','京东'),
    'dangdang' => array('DD','当当'),
    'papai' => array('PP','拍拍'),
    'ebuy' =>  array('EBAY','ebay'),
    'qqbuy' => array('QQ','QQ网购'),
    'yamaxun' => array('AMAZON','亚马逊'),
    'suning' => array('SN','苏宁'),
    'weipinhui' => array('WPH','唯品会'),
    'jumei' => array('JM','聚美'),
    'mogujie' => array('MGJ','蘑菇街'),
    'jushang' =>  array('JS','聚尚'),
    'paixie' => array('paixie','拍鞋'),
    'yintai' => array('YT','银泰'),
    'yihaodian' => array('YHD','1号店'),
    'vjia' =>  array('VANCL','凡客'),
    'youle' =>  array('YL','邮乐'),
    'yougou' =>array('YG','优购'),
    'alibaba' => array('1688','阿里巴巴'),
    'ht' =>  array('OTHERS','其他'),
);