<?php

return array(
    'template' => 'report',
    'data_source'=>array(
       'model'=> 'b2b/BoxRecordModel',
       'method'=> 'print_data_default',
        ),
    'record' => array(
        '箱号' => 'record_code',
        '装箱任务号' => 'task_code',
        '扫描人' => 'scan_user',
        '关联单号' => 'relation_code',
        '装箱时间' => 'create_time',
        '关联单类型' => 'record_type_name',
        '仓库' => 'store_code_name',
        '总数量' => 'num',
        '总金额' => 'money',
        '打印时间' => 'print_time',
        '打印人' => 'print_user_name',
        '页码' => 'page_no',
        '分销商名称' => 'custom_name',
        '拣货单编号'=>'pick_no',
        '入库编号'=>'storage_no',
        'PO编号'=>'po_no',
        '箱序号'=>'box_order',
        '销货单备注' => 'remark',
        '唯品会送货仓' => 'warehouse_name',
        '页码' => 'page_no',
    ),
    'detail' =>
    array(
        '序号' => 'sort_num',
        '商品名称' => 'goods_name',
        '商品编码' => 'goods_code',
        '商品简称' => 'goods_short_name',
        '出厂名称' => 'goods_produce_name',
        '规格1' => 'spec1_name',
        '规格1代码' => 'spec1_code',
        '规格2' => 'spec2_name',
        '规格2代码' => 'spec2_code',
        '数量' => 'num',
        '商品条形码' => 'barcode',
        '库位' => 'shelf_code',
        '商品分类' => 'category_name',
        '商品品牌' => 'brand_name',
        '商品季节' => 'season_name',
        '商品年份' => 'year_name',
        '商品重量' => 'weight',
        '单价' => 'price',
        '吊牌价' => 'sell_price',
        '成本价' => 'cost_price',
        '批发价' => 'trade_price',
        '进货价' => 'purchase_price',
        '金额' => 'money',
        '折扣' => 'rebate',
        '国标码' => 'gb_code',
        '子条码' => 'barcode_child',
    ),
);

