<?php

return array(
    'template' => 'report',
    'data_source'=>array(
       'model'=> 'oms/SellReturnModel',
       'method'=> 'print_data_default',
        ),
    'record' => array(
        '退单类型' => 'return_type',
        '创建时间' => 'create_time',
        '退单号' => 'sell_return_code',
        '关联订单号' => 'sell_record_code',
        '平台退单号' => 'refund_id',
        '换货单号' => 'change_record',
        '平台交易号' => 'deal_code',
//        '平台交易号列表' => 'deal_code_list',
        '业务日期' => 'stock_date',
        '退货仓库' => 'store_name',
        '商店名称' => 'shop_name',
        '销售渠道' => 'sale_channel_name',
        '退款方式' => 'return_pay_code',
        '支付方式' => 'pay_code',
//        '退单状态' => 'return_order_status',
//        '财务审核' => 'finance_check_status',
//        '配送状态' => 'return_shipping_status',
//        '订单包裹是否已出库' => 'is_package_out_stock',
//        '买家确认支付状态' => 'sell_record_checkpay_status',
        '会员代码' => 'customer_code',
        '购买人名称' => 'buyer_name',
        '退货人名称' => 'return_name',
        '退货国家' => 'return_country',
        '退货省' => 'return_province',
        '退货市' => 'return_city',
        '退货区/县' => 'return_district',
        '退货街道' => 'return_street',
//        '退货地址(无省市区)' => 'return_addr',
        '退货地址' => 'return_address',
        '邮政编码' => 'return_zip_code',
        '电话' => 'return_mobile',
        '固定电话' => 'return_phone',
        '邮箱' => 'return_email',
        '退货快递公司' => 'return_express_code',
        '快递单号' => 'return_express_no',
        '退单说明(买家)' => 'return_buyer_memo',
        '退单备注' => 'return_remark',
        '实际退款总金额' => 'refund_total_fee',
        '赔付金额' => 'compensate_money',
//        '买家承担运费金额' => 'buyer_express_money',
//        '卖家承担运费金额' => 'seller_express_money',
        '手工调整金额' => 'adjust_money',
        '换货承担运费金额' => 'adjust_money',
        '退单商品均摊总金额' => 'return_avg_money',
        '换货商品均摊总金额' => 'change_avg_money',
        '换货人' => 'change_name',
        '换货国家' => 'change_country',
        '换货省' => 'change_province',
        '换货市' => 'change_city',
        '换货区' => 'change_district',
        
        '换货街道' => 'change_street',
        '换货地址' => 'change_address', //
//        '换货地址(不包含省市区)' => 'change_addr', //
        '换货电话' => 'change_mobile', //
        '换货固定电话' => 'change_phone', //
        '换货配送方式' => 'change_express_code', //
        '退单客服' => 'service_code',
        '是否赔付' => 'is_compensate',
        '打印时间' => 'print_time',
        '退货原因' => 'return_reason_name',
    ),
        'detail' => array(
            '商品名称' => 'goods_name',
            '商品编码' => 'goods_code',
            '商品简称' => 'goods_short_name',
            '规格1' => 'spec1_name',
            '规格2' => 'spec2_name',
            '单价' => 'goods_price',
            '通知数量' => 'note_num',
            '完成数量' => 'recv_num',
            '均摊金额' => 'avg_money',
            '条形码' => 'barcode',
            
            '库位' => 'shelf_code',
//            '平台规格' => 'platform_spec',
//            '批次号' => 'lof_no',
//            '商品分类' => 'category_name',
        ),
);

